### ISSUE TITLE
DH Aldrachi Reaver does not seem to be working properly

### ISSUE THREAD

**Issue by AnthonyGrenier** [Hekili/hekili#3531] opened 2024-08-24 21:46 UTC
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Playing Havoc DH at level 80, Aldrachi Reaver Hero Talent does not seem to be working properly.
Reaver's Glaive almost never recommended.

### How to Reproduce

Regular play

### Snapshot (Link)

https://pastebin.com/EL5R0ktA

### Contact Information

ITony#8921 (Discord ID)

**Comment by MatteoLombardi** [comment] 2024-08-25 01:22
Already reported in #3450

**Comment by AnthonyGrenier** [comment] 2024-08-25 01:28
Issue in #3450 seems to be related to icons and wording only. RG will get recommend, but I believe the timing is not right.

**Comment by MatteoLombardi** [comment] 2024-08-25 01:32
The issue is exactly about recommendation not working properly, there is a problem with Hero talents overriding default spells, and Art of the Glaive does exactly that

**Comment by bsdgaming** [comment] 2024-08-25 02:34
Currently Reaver's Glaive is not even showing as an ability under Havoc or Vengeance when you go to their abilities page. So i believe Hekili has not implemented hero talents at all for DH yet.

Side not, I did see the Havoc apl updated.

**Comment by bsdgaming** [comment] 2024-08-25 03:49
Problem is still continuing after most recent update. Reavers glaive still not showing up in the abilites. and only being recommended when "Throw glaive" should be recommended. Maybe because they are sharing the same spell id?

Reavers glaive. Sigil of Doom. Abyssal Gaze. Consuming Fire.. are all not showing up in the Demon hunter abilities menu

**Comment by Hekili** [comment] 2024-08-25 03:52
Needs an updated snapshot.

**Comment by bsdgaming** [comment] 2024-08-25 03:59
https://pastebin.com/A5waGGrN

**Comment by bsdgaming** [comment] 2024-08-25 04:13
https://pastebin.com/ygk27963 he is a another snapshot of throwglaive being recommended right after throwing one.. 
I believe it is trying to apply Reaver's glaive because the conditions are being met. But i do not have a reaver's glaive procc'ed yet and throw glaive and reavers glaive share the same action on hekili. I wonder if makes Reaver's glaive its own ability in Hekili would solve this. 

Throw glaive is barely being recommended in current simc profiles. Maybe 1-2 times in a 5 minute fight. Reaver's glaive on the other hand is being thrown alot.

**Comment by Hekili** [comment] 2024-08-25 22:40
Both hero trees being active will be resolved in v11.0.2-1.0.4.  Let me know if it persists after that update.

**Comment by bsdgaming** [comment] 2024-08-25 23:23
Problem is still happening. Addon is consistently recommending "Throw Glaive" because it thinks "Reavers Glaive" is available.



Not sure if you could add reavers glaive as a separate ability. (tooltip=442294) 

https://pastebin.com/UzAn4bg1

**Comment by Hekili** [comment] 2024-08-25 23:28
Yeah, it will need to be split out.  It's on the list.

**Comment by bsdgaming** [comment] 2024-08-25 23:32
Also just tested switching hero talents. It is not recognizing the correct hero talent..

 Still requesting alrachi reaver talents on Fel Scarred. 
 
 https://pastebin.com/62WH12TY

**Comment by AnthonyGrenier** [comment] 2024-08-26 13:18
Can confirm, Throw Glaive being constantly recommend thinking it's Reaver's Glaive.

**Comment by Hekili** [comment] 2024-08-26 19:17
> Still requesting alrachi reaver talents on Fel Scarred.

What makes you think this, based on the snapshot?

**Comment by bsdgaming** [comment] 2024-08-26 19:21
It is checking for Thrill of the Fight buff. Which is a talent for Alrachi Reaver,not for Fel-scarred.

**Closed as completed** 2024-08-26 19:21 UTC
Labels: 📈 recommendations, 🧑‍⚕️ triage

**Comment by Hekili** [comment] 2024-08-26 19:23
That's totally fine, you just won't have the buff.  Priorities are written with hero trees/sub specs both accounted for.

**Comment by bsdgaming** [comment] 2024-08-26 19:23
Ah ok. thanks for clarifying!

**Comment by Hekili** [comment] 2024-08-26 19:31
Throw Glaive and Reaver's Glaive will be fully distinct in 11.0.2-1.0.5.

**Comment by AnthonyGrenier** [comment] 2024-08-26 20:03
Thanks for the follow up and quick responses @Hekili!

**Comment by AnthonyGrenier** [comment] 2024-08-26 23:36
Does not seem to be working still. See issue #3558

**Comment by AnthonyGrenier** [comment] 2024-08-27 03:01
Please re-open issue if possible.
