### ISSUE TITLE
Shadow Priest Vampiric Touch not recognized on mob

### ISSUE THREAD

**Issue by Amortalist** [Hekili/hekili#2604] opened 2023-05-14 15:11 UTC
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

since the latest update hekili tries to refresh vampiric touch when it's like 20s left on the mob

### How to Reproduce

play shadow priest with shadow crash talented and fight mobs

### Snapshot (Link)

https://pastebin.com/SjXqDxi4

### Contact Information

Nibana#6011

**Comment by Hekili** [comment] 2023-05-14 18:00
Duplicate of #2600; this is largely resolved with `1.0.0l` and has an additional fix coming in `1.0.1`.

**Closed as completed by Hekili** 2023-05-14 18:00 UTC
Labels: 📈 recommendations, 🧑‍⚕️ triage
