### ISSUE TITLE
Error in the display of the Upheaval spell. Augmentatio

### ISSUE THREAD

**Issue by geraint425** [Hekili/hekili#2740] opened 2023-07-16 14:24 UTC
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Upheaval doesn't display charges correctly when using the ability. While determining how many targets we have, it may show 4 as in the screenshot, but if we click use ability, it shows 1 charge to use instead of 4 charges. Logically it should be so that when we press it we have 4 charges left to show and not 1 charge to use.
![1](https://github.com/Hekili/hekili/assets/32466458/1b5ec29c-cf82-4de7-b4a5-f83df212bd72)
![image](https://github.com/Hekili/hekili/assets/32466458/dce1d775-b392-4ee4-822c-0a908337eb70)

### How to Reproduce

1. Start a battle with multiple targets.
2. Use Fire Breath first to determine how many targets you have in front of you.
3. The Upheaval will show how many charges to use, click on the Upheaval and you will see that the charge will always show 1, no matter how many targets there are.

### Snapshot (Link)

https://pastebin.com/mTYDYRiN

**Comment by Hekili** [comment] 2023-07-16 14:47
The problem is actually the inverse of what you think it is.  Upheaval is generally used at 1 empowerment, or the lowest level of empowerment that will hit all potential targets.  The addon can't really see that kind of positioning data, so it just assumes that larger clusters of enemies have more spread.

I can *probably* alleviate this, but I may revert to having Upheaval always recommended at 1 empowerment stage instead.

**Comment by Livvvvvvven** [comment] 2023-07-16 16:52
By the way, From the simc file, it seems that Fire breath only has empower to max, unlike EvokerDevastation which has 4 levels, Always to max is better?

**Comment by Livvvvvvven** [comment] 2023-07-16 16:53
> By the way, From the simc file, it seems that fire_breath only has empower to max, unlike EvokerDevastation which has 4 empowerment stages, Always to max is better?

**Comment by Hekili** [comment] 2023-07-16 18:31
> By the way, From the simc file, it seems that fire_breath only has empower to max, unlike EvokerDevastation which has 4 empowerment stages, Always to max is better?

Yes, but also no.  Technically, it's only true with Leaping Flames talented, since the extra Living Flames can heal and proc Essence Burst.

This will be addressed in next release.

**Closed as completed by Hekili** 2023-07-16 18:31 UTC
Labels: 📈 recommendations, 🧑‍⚕️ triage
