### ISSUE TITLE
[REC] ELEMENTAL SHAMAN - TRINKET + LEGENDARY

### ISSUE THREAD

**Issue by NobeUnited** [Hekili/hekili#1175] opened 2021-07-21 22:56 UTC
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Hello.

I think the addon has 2 ussiues which I think are important.

1. The trinket of the first boss of Sanctum (https://es.wowhead.com/item=186422/escrito-sobre-construcciones-monstruosas?bonus=6805) and it's making me cast it on the same target again and again, when it is like Vantus buff. Once is targeted one time, buff remains always up on the same target (I don't know if it applies on adds of the same boss). But it affects on single target.
2. I think windspeaker legendary is not being tracked aswell. Lava burst proc doesn't appear until I cast earth shock, and probably it doesn't works well if you have Master of Elements.

### How to Reproduce

1. Check if you have the trinket buff for make it not appear on the rotation of Hekili
2 Check if it's possible to modify the proc of the windspeaker to put it on rotation.

### Snapshot (Link)

https://pastebin.com/dLfqRkBv

### Additional Information

European account-

### Contact Information

nobe#2100

**Comment by Hekili** [comment] 2021-07-22 00:19
You reported two distinct issues that really belong in separate tickets.

The trinket issue is interesting because, looking at my code, `tome_of_monstrous_constructions` is set up with `nobuff = "studious_comprehension",` which is exactly what you're asking for.  It shouldn't be treated as ready when you have a Studious Comprehension buff applied.

I'll have to try to test this further.

---

For the Windspeaker's Lava Resurgence, this is a good catch and will be fixed in the next release.

**Comment by NobeUnited** [comment] 2021-07-22 14:25
Thank you for your nice work :)

**Comment by claybarrett** [comment] 2021-07-23 03:11
I can confirm both of these issues.

The trinket appears to go off rec because it's on cooldown. It sticks in the recs otherwise even when I'm targeting the mob it was cast on (at first I thought it was target swapping).

**Comment by Hekili** [comment] 2021-07-25 13:49
These should both be resolved.

**Closed as completed by Hekili** 2021-07-25 13:49 UTC
Labels: 📈 recommendations, 🧑‍⚕️ triage
