### ISSUE TITLE
Feral in dungeon, Recommendation will be stucked sometimes

### ISSUE THREAD

**Issue by soze2k** [Hekili/hekili#2059] opened 2022-12-01 16:08 UTC
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

When I use feral in the dungeon, if I encounter an AOE scene, hekili's recommendation will always remind me that all ability needs to wait for 1 second, and this Recommendation Issue may last for more than 10 seconds.

Here is my talents code
BcGAYhlYdy9RJ6ROrphOEi69vCAAAAAAIk0STikkEJl0OAaJRikAAAAAAgmAICgkISChkQLhWiAAAAAAASA 

### How to Reproduce

1. Use Feral
2. Enter Dungeon
3. Encounter an big AOE
4. Open hekili -- Delays -- Extend sprial or Fade as Unusable
5. First recommendation ability stuck, it shows player needs to wait for 1 sec.

### Snapshot

https://pastebin.com/99VYf3Ba

### Additional Information

In the snapshot, What I report is that primal wrath keeps prompting to wait for 1 second, and this problem will also happen to other abilities.

### Contact Information

dlii0032@student.monash.edu

**Comment by W8ink** [comment] 2022-12-01 17:33
same issue in Auto mod. in duo mod its ok

**Comment by zetusx** [comment] 2022-12-01 20:09
having a similar issue with all druid specs if incarn is talented. either does what you said, or only shows incarn as the next spell, even while on full 3min cd. will post snapshot when i get home. may attempt to try the "show cds separately" function to see if that fixes in meantime ad well.

**Comment by Hekili** [comment] 2022-12-03 17:34
> In the snapshot, What I report is that primal wrath keeps prompting to wait for 1 second, and this problem will also happen to other abilities.

Have you seen this since 1.9.3 was released yesterday?  I *think* I see it occasionally, but I'm not sure.

> having a similar issue with all druid specs if incarn is talented. either does what you said, or only shows incarn as the next spell, even while on full 3min cd. will post snapshot when i get home. may attempt to try the "show cds separately" function to see if that fixes in meantime ad well.

I believe I've found the root cause of this issue and it will be resolved in the next release.

**Comment by W8ink** [comment] 2022-12-03 19:04
in 1.9.3 it still happens
https://pastebin.com/vxp4faQ0
issue only in Auto mod, and i think it couse of this:
31.  thrash_cat ( aoe - 10 )
        The action is not ready in time ( 1.08 vs. 1.08 ) [ Clash: 0.00 vs. 0.00 ] - padded by 0.05s.
        Time spent on this action:  0.02ms
        TimeData:Feral-aoe-10:thrash_cat:0.02:Ability Known, Enabled(0.02)
        Exiting aoe with recommendation of NO ACTION at +10.00s.
        Returned from list (aoe), current recommendation is thrash_cat (+1.08).
        - [aoe]
        Added aoe to blocklist as it was called via RAL.

**Comment by W8ink** [comment] 2022-12-03 19:10
1.9.4 issue still here
https://pastebin.com/f1ywr9t8
Dev version: https://pastebin.com/SwU7HKFX

**Comment by Hekili** [comment] 2022-12-03 21:58
Thanks for the snapshots.

> issue only in Auto mod, and i think it couse of this:

What is your interpretation of that?  What makes you think that is the cause?

**Comment by Hekili** [comment] 2022-12-03 22:04
I think this has helped find the underlying issue; there is cached data not being reset between recommendations.  Testing a fix now.

**Comment by Hekili** [comment] 2022-12-04 15:22
Can anyone confirm if they've seen this issue in the 2.0.0 release?

**Comment by W8ink** [comment] 2022-12-04 20:09
2.0.1 everything works perfectly. thank you maestro!

**Closed as completed** 2022-12-05 02:51 UTC
Labels: 📈 recommendations, retail
