### ISSUE TITLE
Game Stuttering FPS Loss after 12/23 Update

### ISSUE THREAD

**Issue by PaulCotton42** [Hekili/hekili#2194] opened 2022-12-23 19:04 UTC
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### WoW Version

Retail (Dragonflight)

### Describe the Issue

When using Hekili after updating to the 12/23 version I am experiencing fps and screen tearing it is when it is grabbing the next skill for the main skill while in combat. This happened to me in blood and unholy. I paused hekili and I no longer had the issue. I movced back to the 12/19 version and no longer have the issue.

### How to Reproduce

I entered the game on both a unholy dk and blood dk 
attacked a mob in dungeon or just in world
watch as my game studders.

### Player Information (Link)

```Text
I already rolled back my version and it works fine.
```

### Error Messages (Link)

```Text
I already rolled back my version and it works fine.
```

**Comment by Hekili** [comment] 2022-12-23 22:33
You'll need to provide snapshots or more data for me to do anything with this ticket.

**Comment by Tzuyume** [comment] 2022-12-24 00:29
same issue but with snapshot during lag https://pastebin.com/SXP39fQG

**Comment by cheribou** [comment] 2022-12-24 04:11
Having this issue too. The game started screen tearing with the newest update. I don't even have to be in combat, walking around Valdrakkan gives me horrible stuttering. I disabled Hekili and the game returned to normal, and I rolled back to the previous update and that was also fine.

**Comment by garodin** [comment] 2022-12-24 07:36
I am having the same issue. Any class, stutters every 1-2seconds

**Comment by mSterian** [comment] 2022-12-24 09:49
I have the issue too and I found what is causing it. Toggle off Potions in the Hekili menu. Not sure why that's causing issues but as soon as I turn it off it's all good.

**Comment by mSterian** [comment] 2022-12-24 09:58
Actually I retract that statement. While turning off potions is improving the issue a lot, it still doesn't fix it completely. Still have frape drops/spikes when Hekili is loaded.

**Comment by Zaxx-is** [comment] 2022-12-24 13:29
I confirm that I have the same issue on both Enhancement and Elemental. Resetting the profile to default helped reduce the stuttering, but not completely. It only happens in combat.

**Comment by Hekili** [comment] 2022-12-24 13:47
What are the actual version numbers where you do/don't have this issue?

**Comment by cheribou** [comment] 2022-12-24 13:48
I have issues on the "Hekili-v10.0.2-2.0.9.zip" - no issues on "Hekili-v10.0.2-2.0.8c.zip"

**Comment by mSterian** [comment] 2022-12-24 18:45
Same here, Hekili-v10.0.2-2.0.9.zip frame drops and Hekili-v10.0.2-2.0.8c.zip not.
I have only tested on monk brewmaster.

**Comment by mynamefield** [comment] 2022-12-25 09:54
Problem: Hekili-v10.0.2-2.0.9.zip
Works fine: Hekili-v10.0.2-2.0.8c.zip

Not sure if this helps but some insight.

The problem is especially bad with these settings:
Class: Death Knight
Spec: Frost
Display Mode: Dual //very noticeable difference when you switch to single mode

Additional stuff: When constantly moving lets stay left to right while spamming abilities, it is very bad. The stutter spikes FEEL like they come in at specific intervals.


ps. Thank you so much for your hard work. Happy holidays!

**Comment by mSterian** [comment] 2022-12-25 18:26
I have the fps drops even while standing still. I am also using dual display. I wish there was a Hekili mode that ONLY tracks cooldowns, and disable all "situational monitoring/triggers". So don't check ranges, or combat state, or health, or anything. I don't really need those anyway. What I mostly use Hekili for is showing me the skill priority, and filtering only for skills that are off cooldown. Looking at the ability bar is way too messy and distracting. With such an option there shouldn't ever be any more performance issues as just tracking cooldown should be a very low effort task.

**Comment by Tzuyume** [comment] 2022-12-25 18:27
Can confirm it works to rollback to v10.0.2-2.0.8

**Comment by Hekili** [comment] 2022-12-25 20:44
> I have the fps drops even while standing still. I am also using dual display. I wish there was a Hekili mode that ONLY tracks cooldowns, and disable all "situational monitoring/triggers". So don't check ranges, or combat state, or health, or anything. I don't really need those anyway. What I mostly use Hekili for is showing me the skill priority, and filtering only for skills that are off cooldown. Looking at the ability bar is way too messy and distracting. With such an option there shouldn't ever be any more performance issues as just tracking cooldown should be a very low effort task.

Use WeakAuras to sort your abilities by cooldowns without considering all those other factors.  That's not the purpose of this addon.

**Comment by Hekili** [comment] 2022-12-25 21:12
This may be addressed in 2.0.9a; let me know if you still observe an issue.  Thanks!

**Comment by vond82** [comment] 2022-12-26 01:45
No issues for me with 2.0.9a

**Comment by Zaxx-is** [comment] 2022-12-26 10:46
Fixed in 2.0.9a for me too :) GJ Hekili :)

**Comment by Tzuyume** [comment] 2022-12-26 12:59
Been trying on several specs for over a day and seems completely gone. Thanks for the quick update over the holidays Hekili!

**Closed as completed** 2022-12-26 13:55 UTC
Labels: 🐛 Bug, retail

**Comment by mSterian** [comment] 2022-12-28 19:43
While the effect is a lot less noticeable now, it still has an impact. For example, with Hekili, my fps is very stable at 118 fps. When I enable it it starts fluctuating between 115 and 120. Can I change something so that it doesn't impact the FPS at all? All I want is a cooldown tracker / rotation suggester. No fancy dynamic stuff.

**Comment by Bios777** [comment] 2023-01-31 08:50
I found this is occuring on my druid, but my death knight doesn't seem to be affected.
