### ISSUE TITLE
[BUG] GCD Timer Glitchy on Demo Lock (Mostly in raid)

### ISSUE THREAD

**Issue by Raven7576** [Hekili/hekili#1489] opened 2022-04-24 14:13 UTC
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

As the title describes, I've noticed now that I'm playing a caster (was a Warrior main beforehand) that the GCD sweep seems to bug out and really lag behind on recommendations. It will flicker and go an "off GCD" state and dial back to the fractions of a second left in the GCD. Its really throwing off my ability to queue up spells. Im not sure if its haste effecting the GCD or if the number of actions going on are bogging something down (either on my side or in your code?). Just seems like the GCD timer is constantly trying to self correct too much. 

I've gotten a new, much more power CPU since I first noticed this, so I'm writing off hardware issues.

I don't have much for a video as proof but I can work on it if absolutely necessary. 

### How to Reproduce

1. Play Demo lock
2. Enter LFR or some world content
3. Hand of Guldan
4. Demon Bolt
5. Hand of Guldan
6. repeat until GCD correction lags behind

### Player Information (Link)

https://pastebin.com/HtdBScbt

### Error Messages (Link)

https://pastebin.com/Vgc0rDbX

### Additional Information

The error messages link is just the latest "warnings" read out as of 3 mins before typing up this thread. Could be completely unrelated.

### Contact Information

Razør#0394

**Comment by Hekili** [comment] 2022-04-24 17:35
This is convenient timing for a ticket, as this has annoyed the hell out of me for some time.  So I fixed it in my working copy but haven't put it in a release yet.

This should be fixed in the next few days.

**Comment by Raven7576** [comment] 2022-04-24 18:19
Glad I wasnt just imagining it then, Haha and good timing too

**Comment by Hekili** [comment] 2022-04-24 18:22
Today's release will include my fix.  Feel free to reopen if the issue is unresolved for you.

**Closed as completed by Hekili** 2022-04-24 18:22 UTC
Labels: 🐛 Bug

**Comment by Raven7576** [comment] 2022-04-28 02:42
Sorry to necro but, any time line on a release? maybe a beta push?

**Comment by Hekili** [comment] 2022-04-28 03:46
I've pushed it out as an alpha for -17 now.  I've been busy with work and haven't had time to merge other changes.
