### ISSUE TITLE
FPS in combat drops after update

### ISSUE THREAD

**Issue by Matrichniy** [Hekili/hekili#1046] opened 2021-04-05 11:54 UTC
Hello. I really like your addon, but after the last update, fps in combat began to fall by 20-30. 
I tried to reduce the display of icons from 3 to 1, it helped a little. But before this was not, I would like to understand the problem, here is all the necessary data for this:

Issue Report:
https://pastebin.com/V9ZVuxU3

Snapshot:
https://pastebin.com/6jvd1K9a

CPU: AMD Ryzen 2700x
GPU: GTX 1080 Ti
RAM: 32Gb

After conducting my investigation to find the source of fps drops, I left only the standard interface and Hekili and the problem was found. Apparently this is the problem of rogue, because in the warrior there are no such fps drops.
I hope we find and fix the problem.

**Comment by Hekili** [comment] 2021-04-05 12:10
What was the last version that didn't have issues for you?  What was the version that this started to happen?  I need actual version numbers and snapshots from both, taken when you would have the reported issue.

**Comment by Hekili** [comment] 2021-04-05 12:23
Also, was that snapshot taken when you were actually experiencing a slowdown?  Nothing looks particularly bad about it.  Snapshots need to be taken when the problem is occurring, if they are to be useful.

**Comment by Matrichniy** [comment] 2021-04-05 12:25
> What was the last version that didn't have issues for you? What was the version that this started to happen? I need actual version numbers and snapshots from both, taken when you would have the reported issue.

I put it a little wrong. Until the last update, I played on the warrior and on rogue - there were no problems in the warrior (there are no problems now), but there are fps drops when switching to rogue.
I initially thought that the problem was in the update, but as it turned out, after reading a few topics here - the problem is not the update, but in the class.

**Comment by Matrichniy** [comment] 2021-04-05 12:34
> Also, was that snapshot taken when you were actually experiencing a slowdown? Nothing looks particularly bad about it. Snapshots need to be taken when the problem is occurring, if they are to be useful.

Oops. Sorry.
Here is a snapshot of fps drops: 
https://pastebin.com/iDaey74p

and screenshots of fps drops:
combat
![image_2021-04-05_15-29-54](https://user-images.githubusercontent.com/81965982/113574224-568cf700-9624-11eb-8b90-666510ecc622.png)

no combat
![image_2021-04-05_15-30-01](https://user-images.githubusercontent.com/81965982/113574261-63114f80-9624-11eb-9a4a-075501cff48e.png)

**Comment by Squeeeps** [comment] 2021-04-06 23:31
I've actually been experiencing this same problem on multiple characters, it started about 2 updates ago (that includes the one from 2 days ago).  As soon as combat is entered FPS drops to between 25-30 (lowest it has dipped was 15 FPS while in Raid Finder).  I've had to disable it across my account as it's simply unusable.  So far this has affected my Druid, Mage, Shaman, Paladin, Rogue and Hunter.

**Comment by Hekili** [comment] 2021-04-07 00:00
You'd still need to supply the same information required for any ticket, @Squeeeps.

**Comment by Hekili** [comment] 2021-04-07 00:26
If you are having this issue, please provide the following information, together, **after** a fight that is at least 60 seconds long.

`/dump HekiliDisplayPrimary.combatTime`
`/dump HekiliDisplayPrimary.combatUpdates`

**Comment by Matrichniy** [comment] 2021-04-07 08:34
> If you are having this issue, please provide the following information, together, **after** a fight that is at least 60 seconds long.
> 
> `/dump HekiliDisplayPrimary.combatTime`
> `/dump HekiliDisplayPrimary.combatUpdates`

![D](https://user-images.githubusercontent.com/81965982/113835998-2a44b800-9795-11eb-9586-e7078b4d65d3.PNG)
![D2](https://user-images.githubusercontent.com/81965982/113836002-2add4e80-9795-11eb-8dbc-8aa2a6f1bbe5.PNG)

**Comment by Matrichniy** [comment] 2021-04-07 08:43
here's a bigger fight
![D](https://user-images.githubusercontent.com/81965982/113837448-86f4a280-9796-11eb-88b0-2f74ba5d5c92.PNG)
![D2](https://user-images.githubusercontent.com/81965982/113837452-878d3900-9796-11eb-9290-df80e175fa84.PNG)

**Comment by toddctc76** [comment] 2021-04-07 17:01
I'm just leaving a comment as I've put in a bug report before on the FPS drops when in combat as subtlety rogue.  I am still seeing this in sub and assassination rogue (outlaw okay for now) and am now seeing in unholy DK and balance druid.  For the rogue, been ongoing for several versions.  Not sure when it started for unholy DK.  For balance druid, I have not played in a while, but noticed today when going against a dummy.  FPS drops anywhere from 20 to 40 when in combat.

**Comment by Hekili** [comment] 2021-04-07 17:29
@toddctc76 I will still need snapshots and the other information requested above for each spec you're experiencing this on.  Thanks!

**Comment by toddctc76** [comment] 2021-04-07 18:36
Hi.  Here are the screen shots and dumps.  I did them for assassination and subtlety rogue as well as destruction warlock.  I know I mentioned balance and unholy before, but am less concerned about those.  I know proximity to target  can also have an affect on frames.
![subtlety rogue dumps](https://user-images.githubusercontent.com/80970815/113916849-1a819f80-97a6-11eb-96cd-576a40421f48.png)
![assassination rogue dumps](https://user-images.githubusercontent.com/80970815/113916892-25d4cb00-97a6-11eb-9525-c3db4e60eadc.png)

**Comment by Hekili** [comment] 2021-04-07 18:36
@toddctc76 Snapshots, not screenshots.  But thanks for the other details.

**Comment by toddctc76** [comment] 2021-04-07 18:38
Oh shoot, sorry!  Is this what you mean?  This is the sub rogue one.

build: v9.0.5-1.0.6
level: 60 (60)
class: ROGUE
spec: subtlety

talents: deeper_stratagem
    elusiveness
    enveloping_shadows
    premeditation
    prey_on_the_weak
    secret_technique
    shadow_focus

pvptalents: none

covenant: venthyr

conduits: deeper_daggers = 5
   fade_to_nothing = 4
   planned_execution = 5
   recuperator = 4

soulbinds: [nadjia_the_mistblade]
   agent_of_chaos = 1
   familiar_predicaments = 1
   friends_in_low_places = 1
   thrill_seeker = 1

sets: none

gear: ardent_sunstar_signet = 1
    darkmoon_deck_voracity = 1
    decanter_of_animacharged_winds = 1
    drape_of_twisted_loyalties = 1
    ebony_death_shroud_belt = 1
    ebony_death_shroud_bindings = 1
    ebony_death_shroud_breeches = 1
    ebony_death_shroud_gloves = 1
    ebony_death_shroud_hood = 1
    miasmalacquered_jerkin = 1
    ritual_bone_band = 1
    sinful_aspirants_dagger = 1
    sinful_gladiators_sinedged_dirk = 1
    umbrahide_pauldrons = 1
    valeshroud_torque = 1
    vanquished_usurpers_footpads = 1

legendaries: celerity = 1

itemIDs: 172319, 173087, 175740, 178470, 178797, 178861, 178870, 180123, 180909, 180915, 180919, 180927, 180931, 182401, 183009, 183035

settings: aoe = 2
    buffPadding = 0
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = false
    cycle_min = 6
    damage = true
    damageDots = false
    damageExpiration = 6
    damagePets = false
    damageRange = 0
    debuffPadding = 0
    enabled = true
    enhancedRecheck = false
    gcdSync = true
    maxRefresh = 10
    maxTime = 33
    nameplateRange = 8
    nameplates = true
    package = Subtlety
    petbased = false
    potion = phantom_fire
    potionsReset = 20180919.1
    throttleRefresh = false
    throttleTime = false
    mfd_points = 3
    priority_rotation = false
    solo_vanish = false

toggles: cooldowns = true
    custom1 = false
    custom2 = false
    defensives = false
    essences = true
    interrupts = false
    mode = automatic
    potions = false

**Comment by Hekili** [comment] 2021-04-07 18:39
2.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot.  This is not a screenshot.  A snapshot can be generated by binding the Pause feature on the Toggles tab.  When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab.  Copy and paste this to pastebin.com and provide the link here.
 
**PUT SNAPSHOT LINK HERE:**

**Comment by toddctc76** [comment] 2021-04-07 18:58
Hi, okay I think I got it.  Here is the sub rogue one https://pastebin.com/rHEEywuC
and the destruction lock one https://pastebin.com/Zr5PcfBf

Thanks for your patience!

**Comment by Hekili** [comment] 2021-04-07 19:05
Just to confirm, those two snapshots were taken *at the time you felt performance was degraded, using the addon*?  The sub rogue one has full energy and no combo points, which makes me think it's out of combat.  Weren't you reporting that FPS goes down in combat?

**Comment by toddctc76** [comment] 2021-04-07 19:37
Here is another one.  I did the previous one thinking the snapshot would collect data as I was in combat; therefore I started it before entering combat.  Now I know that is not the case.  This one was taken while in combat.  https://pastebin.com/4cWhFRqU

**Comment by ijoihlhnn** [comment] 2021-04-07 20:15
Here is the Snapshot and combatTime//combatUpdates dump.

/dump HekiliDisplayPrimary.combatTime ->> https://i.imgur.com/jx1fHee.png
/dump HekiliDisplayPrimary.combatUpdates ->> https://i.imgur.com/aBOPaRM.png

-------------------------------------------------------
AOE Window Snapshot: https://pastebin.com/QfMb2JB8
Primary Window Snapshot: https://pastebin.com/uuR0VrJn

**Comment by Karalum** [comment] 2021-04-07 23:34
i can confirm, just come here to tell you this problem but i saw someone open this thread. game is stuttering in combat. im dk. also using ryzen cpu 3600X. if i disable addon, everything goes perfect.

**Comment by Hekili** [comment] 2021-04-07 23:50
The other information that would help for troubleshooting purposes is if folks could help pin down exactly which version of the addon represents when the performance decrease started.  I'd do it myself except...I don't get any performance decrease.  :|

**Comment by toddctc76** [comment] 2021-04-08 00:27
Tomorrow I will go back through old versions and see if I can find the last one that didn’t cause it.  Seems like it started happening a few months ago.  I will start further back, however.  I also have a Ryzen 5 1600x CPU.

**Comment by Matrichniy** [comment] 2021-04-08 07:57
> The other information that would help for troubleshooting purposes is if folks could help pin down exactly which version of the addon represents when the performance decrease started. I'd do it myself except...I don't get any performance decrease. :|

I can assume that the point is to optimize the addon for Ryzen CPU's

**Comment by Lipstopica** [comment] 2021-04-08 08:15
> > The other information that would help for troubleshooting purposes is if folks could help pin down exactly which version of the addon represents when the performance decrease started. I'd do it myself except...I don't get any performance decrease. :|
> 
> I can assume that the point is to optimize the addon for Ryzen CPU's

I honestly don't think it works like that, doesn't matter what brand of CPU that you use. I mean, it wouldn't make sense.

**Comment by Matrichniy** [comment] 2021-04-08 11:22
> > > The other information that would help for troubleshooting purposes is if folks could help pin down exactly which version of the addon represents when the performance decrease started. I'd do it myself except...I don't get any performance decrease. :|
> > 
> > 
> > I can assume that the point is to optimize the addon for Ryzen CPU's
> 
> I honestly don't think it works like that, doesn't matter what brand of CPU that you use. I mean, it wouldn't make sense.

But the performance problems are mostly with the owners of Ryzen, if you look at the reviews and open topics.

**Comment by Hekili** [comment] 2021-04-08 12:51
There's literally nothing I can do within WoW itself to deal with CPU architecture at all.  But it's definitely interesting that Ryzen seems to be a common factor here.  I think I have a Ryzen box somewhere I can do some testing with.  Are folks experiencing issues using DX11 or DX12?

I still need to pin down if there's really one version that works fine and then the next version that slows down.  Can someone backtrack through recent releases?

**Comment by toddctc76** [comment] 2021-04-08 15:03
I tested a handful as far back as I could go and still had FPS issues.  Here are the versions I tried.
feb 13 v9.0.2-1.0.40 
feb 14 v9.0.2-1.0.40a
mar 10 v9.0.5-1.0

I've been using DX12.  I just tried DX11 and noticed my overall FPS was up.  Using my sub rogue in combat against a training dummy with DX11 and the issues still were there and using the latest version of Hekili.

I understand that Ryzen might be a common denominator, but the issues are not occurring on every spec and class, just some.

**Comment by toddctc76** [comment] 2021-04-08 15:04
If you have some older ones that are not available on the site, I am willing to try.  I would like to try back at the beginning of Shadowlands.  I don't remember having issues then or during BFA.

**Comment by Hekili** [comment] 2021-04-08 15:10
Every version ever released is right here on GitHub.

**Comment by toddctc76** [comment] 2021-04-08 17:42
I don't know if anyone else has tried any of the older versions yet, but I tried the following with DX12:
Oct 31, v9.0.1-1.0.18 - FPS drops by 20 to 30, game stuttering.
Nov 6, v9.0.1-1.0.24 - same as above
Nov 17, v9.0.2-1.0.0 - same as above. Tried with DX11 on this one and slightly better.
Nov 23, v9.0.2-1.0.4 - same as above.
Dec 6, v9.0.2-1.0.16 - same as above.
Tried the latest version (just to re-verify) and noticed the same.  However, I'm seeing less dips into the 50s during combat vs some version prior to latest, so that is great.

Appreciate all the hard work you're doing with this amazing addon!  Not sure what a good donation is, but I made one.  Thanks again for the great addon.

**Comment by Matrichniy** [comment] 2021-04-08 18:49
DX12 > DX11 drops equally for me and my Ryzen 2700x

**Comment by Hekili** [comment] 2021-04-08 19:28
@toddctc76 Thanks for the research and the support.  I'm going to have to try some gimmicky stuff to work around, I think it's just the WoW doesn't multithread well on Ryzen.  I may be able to split the work of generating recommendations across multiple frames.  Maybe.

**Comment by toddctc76** [comment] 2021-04-11 13:17
I ran wow with Hekili on an intel core i5 laptop and had no issues with FPS drops or stuttering.  Not sure this will make a difference, but this week I will try disabling cores on my ryzen pc and see what happens.  Probably nothing, but worth a shot.

**Comment by DavidIFWS423A** [comment] 2021-04-11 14:33
i created an account to report the same issues:

On FireMage, i have HEAVY drops on HEKILI but this is due to the fire mage spec.
On  MM hunter, i have none to very low drops - like 20 from 120 to 100ish
On Boomie my fps drops to like 70 at all - probably like fire mage

since about one week its dropping way harder on every char. im using an 9700k at 5ghz

**Comment by Hekili** [comment] 2021-04-11 14:38
@pirotess66 Boomkin is fairly complex as well, so having more usage isn't surprising.  If it's worsened on every character, what I'd need to hear from you is:

What is the last version of the addon that doesn't have this issue for you?  What is the first version that starts to have this performance impact for you?

**Comment by DavidIFWS423A** [comment] 2021-04-11 14:55
@Hekili 
yea i thought boomie rotation will use much more then MM for example,im fine with that at all.

i think it happened since the last update. on  v9.0.5-1.0.5 i hadnt that performance issues.

im rolling back on the previous version. 

Do you have any solutions for boomie ? On Balance -> performance there are some options like throttle updates or something but i dont have any clue what to do there

**Comment by Hekili** [comment] 2021-04-11 15:23
No, no real recommendations regarding different settings.

If you provide more information, it really has to be specific and confirmed.  That is, not that you think it happened with a particular version, rather that you are using version A and seeing X FPS, but when you switch to version B you see Y FPS.

**Comment by DavidIFWS423A** [comment] 2021-04-11 16:08
ive changed nothing at all, just can tell that the fps drops on all chars that are using hekili were harder since about 5-7 days.

**Comment by Hekili** [comment] 2021-04-11 16:10
Okay, someone else will have to help provide version numbers then.

**Comment by DavidIFWS423A** [comment] 2021-04-11 18:59
what version number do you want from me? i posted to you that with version v9.0.5-1.0.5 EVERYTHING was fine. 

AFTER v9.0.5-1.0.6 i have harder framedrops then usual

isnt this enough info for you? i mean several people are reporting issues here for the last 5-6 days. and the addon was updated 7 days ago. idk what u want me to provide you

**Comment by Hekili** [comment] 2021-04-11 19:26
Hey, I don't want anything from you that you're going to get upset about.  Thanks.  I'll continue to research on my own.  Take care.

**Comment by DavidIFWS423A** [comment] 2021-04-11 19:49
no i want to help you fix the problems. i mean ive used ur addon for quite a time and i want to provide any informations u need to make it better in any case

**Comment by SlipsknuteN97** [comment] 2021-04-11 21:06
Hey I have huge FPS and lag issues with this addon. I have the latest updates aswell. 
AMD Ryzen 7 1700
Corsair Vengence 16GB RAM
GTX 1070

EDIT: I bought a new GPU (RTX 3060) becouse I thought it was my GPU giving up on me but I had same issues on the 3060. I had this problem for around 4 weeks.

**Comment by Hekili** [comment] 2021-04-11 21:27
@SlipsknuteN97 If you look back in the thread, I'd ask you to try different versions of the addon and let me know if/when there's a previous version that works better.  Ideally with FPS numbers and the other regular ticket information (i.e., a snapshot taken in combat, read the instructions re: snapshots).

**Comment by Matrichniy** [comment] 2021-04-12 07:51
after practicing on the mannequin, I can say that there are no special fps drops on warrior, but as soon as I switch to rogue, the fps drops to 30-40

**Comment by pirotess66** [comment] 2021-04-12 09:28
And he says to me that it has to be a personal Problem. Its pretty obvious Right now that there is something wrong/ consuming more cpu than usual since the new update from the 04th april.

**Comment by Hekili** [comment] 2021-04-12 12:12
@pirotess66 I absolutely didn't say it's a personal problem. Please don't make things up. I said I can't replicate it, myself, which is why I ask for data to help sort it out. If you aren't contributing specific measurable data that can help diagnose or solve the issue, please don't post again. Thanks.

**Comment by Hekili** [comment] 2021-04-12 12:15
@Matrichniy Which rogue spec(s)? They're all different. If you go back to an older version, at what point does the issue go away?

**Comment by pirotess66** [comment] 2021-04-12 12:44
xd if you dont want any help, just dont wonder yourself if your addon is losing more and more people due to heavy performance problems. first time for 2 years now where i uninstall it instead of disabling it and waiting for some fixes.

**Comment by SlipsknuteN97** [comment] 2021-04-12 16:04
@Hekili Hey thanks for the response. Not really sure how I can do that but I will try to research that. I love this addon, totally amazing so I hope I will be able to fix it. Amazing work.

**Comment by Dajova** [comment] 2021-04-13 20:34
I can chip in here and can confirm that Hekili is indeed making a huge fps spike on certain class/specs. Here's the actual CPU usage after 1 fight with 2 mobs on my Fire Mage (literally just 10 sec, does not happen in Arcane Spec):
![image](https://i.imgur.com/WIjyWS9.png)
[GIF](https://dl.dropboxusercontent.com/s/xd8o64i4x6u19ms/2021-04-13_22-35-39.gif)

**Comment by Hekili** [comment] 2021-04-13 20:45
@Dajova Fire Mage doesn't count, because the Fire APL is ridiculous.  For the record, and to avoid any confusion, I'm not debating that the addon uses CPU (and more than most).  Folks are reporting that CPU usage has increased recently, but I'm struggling to get responses that indicate **when** an increase has occurred vs. a previous version.

**Comment by Hekili** [comment] 2021-04-14 02:37
1.0.7-beta1 will be available in a little bit.  I've found that, while Fire Mage's computation time was high, it was also refreshing more often than is necessary for accuracy.  I'll be interested to hear if any difference is noted in performance.

**Comment by SlipsknuteN97** [comment] 2021-04-14 14:35
@Hekili Thanks mate, might be the problem for me aswell since I main Fire Mage too

**Comment by Hekili** [comment] 2021-04-15 14:04
The latest release has all the performance enhancements that were underway.  I'm going to close this ticket and create a new kind of ticket for performance related concerns.

**Closed as completed by Hekili** 2021-04-15 14:04 UTC
Labels: 🐛 Bug
