### ISSUE TITLE
Odyn Fury not showing up in rotation

### ISSUE THREAD

**Issue by Vardrack** [Hekili/hekili#2010] opened 2022-11-21 13:30 UTC
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [ ] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

With default priority, Odyn Fury is ignored.

### How to Reproduce

1. Play as Fury Warrior
2. Take Odyn Fury talent
3. it doesn't appear on rotation

### Talent Loadout

BgEAR5QSZgdnGefDo4ho9ZGXKHAAAAAAAAAAAIJFKBQEEiEcANiEiABhkQEJJBCJJJRaRAEJBAAAA

### Snapshot

https://pastebin.com/KeGy4czG

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/fY9EU6USxj2hr2xLBWgZMd

### Contact Information

Vardrack#1431

**Comment by Hekili** [comment] 2022-11-21 15:42
Duplicate of #2009

**Closed as completed by Hekili** 2022-11-21 15:42 UTC
Labels: 📈 recommendations, 🧑‍⚕️ triage
