### ISSUE TITLE
Stops suggesting spells after certain amount of time.

### ISSUE THREAD

**Issue by jankozilla** [Hekili/hekili#1957] opened 2022-11-14 23:13 UTC
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### WoW Version

Retail (Dragonflight)

### Describe the Issue

For now I have played with my rogue and BM hunter and noticed that sometimes the addon would just not show any spells after a certain time. A bit inconsistent of when it does it so hard to show.

### How to Reproduce

1.Log in to WoW.
2.Play BM hunter.
3. Follow rotation while fighting boss mobs, notice addon doesn't show any more spells.

### Player Information (Link)

```Text
build: v10.0.0-11.2
level: 60 (60)
class: ROGUE
spec: assassination

talents: acrobatic_strikes
    alacrity = 2/2
    blackjack = 1/1
    blind = 1/1
    bloody_mess = 2/2
    cheat_death = 1/1
    cloak_of_shadows = 1/1
    crimson_tempest = 1/1
    cut_to_the_chase = 1/1
    deadly_poison = 1/1
    deadly_precision = 2/2
    deathmark = 1/1
    deeper_stratagem = 1/1
    doomblade = 1/1
    elaborate_planning = 2/2
    evasion = 1/1
    feint = 1/1
    fleet_footed = 1/1
    gouge = 1/1
    improved_garrote = 1/1
    improved_poisons = 1/2
    improved_shiv = 1/1
    indiscriminate_carnage = 1/1
    iron_wire = 1/1
    leeching_poison = 1/1
    lethal_dose = 2/2
    lightweight_shiv = 1/1
    master_assassin = 1/1
    numbing_poison = 1/1
    prey_on_the_weak = 1/1
    sap = 1/1
    scent_of_blood = 3/3
    seal_fate = 2/2
    serrated_bone_spike = 1/1
    shadowstep = 1/1
    shadowstep_2 = 1/1
    shiv = 1/1
    thiefs_versatility = 2/2
    thrown_precision = 1/1
    tight_spender = 1/1
    venomous_wounds = 1/1
    vigor = 1/1
    virulent_poisons = 1/1

pvptalents: none

covenant: none

conduits: none

soulbinds: [nadjia_the_mistblade]

sets: none

gear: airstream_treads = 1
    brokers_lucky_coin = 1
    deadly_sinvyr_ring = 1
    doomhide_gauntlets = 1
    drape_of_benediction = 1
    enlightened_dagger = 1
    leafmender_robes = 1
    logic_loop_of_division = 1
    mad_kings_sporran = 1
    shadebound_armguards = 1
    shadebound_greaves = 1
    shadebound_helm = 1
    shadebound_pauldrons = 1
    ticking_sack_of_terror = 1
    versatile_solenium_necklace = 1

legendaries: none

itemIDs: 109897, 143983, 150382, 150417, 168986, 169157, 172253, 172254, 172255, 172257, 173134, 173144, 188042, 190389, 190652

settings: aoe = 3
    buffPadding = 0
    combatRefresh = 0.1
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = false
    cycle_min = 6
    damage = true
    damageDots = false
    damageExpiration = 6
    damageOnScreen = true
    damagePets = false
    damageRange = 0
    debuffPadding = 0
    enabled = true
    enhancedRecheck = false
    gcdSync = true
    maxRefresh = 10
    maxTime = 33
    nameplateRange = 8
    nameplates = true
    noFeignedCooldown = false
    package = Assassination
    petbased = false
    potion = phantom_fire
    potionsReset = 20180919.1
    regularRefresh = 0.5
    throttleRefresh = false
    throttleTime = false
    envenom_pool_pct = 50
    mfd_points = 3
    mfd_waste = true
    priority_rotation = false
    solo_vanish = false

toggles: cooldowns = true 
    custom1 = false 
    custom2 = false 
    defensives = false [separate]
    essences = true [overridden]
    interrupts = false 
    mode = automatic 
    potions = false 

keybinds: 
    ambush                 = 1   [07]
    cheap_shot             = 2   [07]
    cloak_of_shadows       = F10 [06]
    crimson_tempest        = 5   [01]
    crimson_vial           = F8  [06]
    deathmark              = F5  [06]
    distract               = 5   [07]
    envenom                = 3   [01], 3   [07]
    evasion                =
    fan_of_knives          = F6  [06]
    feint                  = F9  [06]
    flagellation           = =   [06]
    garrote                = F2  [06]
    indiscriminate_carnage = F3  [06]
    kick                   = M3  [01], M3  [07]
    kidney_shot            = Z   [05]
    mutilate               = 1   [01]
    rupture                = 2   [01]
    sap                    = 9   [07]
    serrated_bone_spike    =
    shiv                   = 4   [01]
    shroud_of_concealment  = 6   [07]
    slice_and_dice         = F1  [06]
    sprint                 = -   [06]
    stealth                = F11 [06]
    vanish                 =

warnings: none
```

### Error Messages (Link)

```Text
-
```

### Contact Information

Janko#2971

**Comment by Hekili** [comment] 2022-11-15 02:20
There shouldn't be anything preventing an actual snapshot from being taken -- they're likely generated automatically when this is happening.

I'm going to close this ticket since I'm posting 11.3 which will make it obsolete.  If you have the same issue again, please submit a Recommendations ticket and include a snapshot (or snapshots) when the issue is occurring.  Thanks!

**Closed as completed by Hekili** 2022-11-15 02:20 UTC
Labels: 🐛 Bug, 🧑‍⚕️ triage
