### ISSUE TITLE
[REC] Mind Flay being mis-recommended in Voidform windows

### ISSUE THREAD

**Issue by dubudevs** [Hekili/hekili#3993] opened 2024-10-20 02:28 UTC
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Priest - Shadow

### Describe the Issue

Unempowered Mind flay is being recommended when other buttons are available (namely DP/MB) which is often resulting in shorter voidform windows and lower dps output. 

In the snapshot it appears to be calling the MFI action list but recommending mind flay. This does not happen in the sim, mind flay is always called as part of [filler] and MFI is always called by [empowered_filler]. Mind Flay is being called by [empowered_filler] which should not be possible. Here's a second one that shows 2 recommendations close to eachother with no charges of MFI ready, and no casts of DP between the first and second one so no way to get a charge of MFI. https://pastebin.com/dp7gYEwp

Sims generally get about 50 seconds of VF on pull with my character and anecdotally I find that I need to manually intervene/deviate from recommendations to get this much (or more) uptime. 

Apologies for the errors in the snapshot lol

### How to Reproduce

Play ST talents and blast. 

The only time MF should be recommended is with no insanity for DP, no mind blast ready to cast, no void bolt, no free charge of DP with Mind Devourer, and obviously no MFI.

### Snapshot (Link)

https://pastebin.com/zMSYvSXw

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/bRT7fM7oWmxNBHoCyNKzCC/simc

**Comment by Hekili** [comment] 2024-10-22 02:16
The quick fix for this is to edit the `empowered_filler` entries:

The first needs to require `buff.mind_spike_insanity.up`; the second needs to require `buff.mind_flay_insanity.up`.

(The issue is, essentially, that Mind Spike and Mind Flay and their buffed forms are currently interchangeable.)

**Comment by Hekili** [comment] 2024-10-23 16:57
This is resolved.

**Closed as completed by Hekili** 2024-10-23 16:57 UTC
Labels: 📈 recommendations, 🧑‍⚕️ triage
