### ISSUE TITLE
Balance Druid keeps recommending Starsurge when I don't have enough Astral Power to cast.

### ISSUE THREAD

**Issue by Dazdruid** [Hekili/hekili#1755] opened 2022-10-28 06:21 UTC
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Balance Druid keeps recommending Starsurge when I don't have enough Astral Power to cast.

### How to Reproduce

1. Enter the game as a Balance Druid
2. Just follow the priority and it will recommend Starsurge even though you don't have enough AP.

### Snapshot (Link)

https://pastebin.com/befRje9Q

**Comment by Hekili** [comment] 2022-10-28 12:23
Can you post your talent string please?  Thanks.

**Comment by Dazdruid** [comment] 2022-10-28 14:00
BYGAGX1kx6Mci9Zl2t+S+sRoPCAAAAAAAAAAAAAAAAAAAoAQSiIQChkEkIgWCJ5ARayBIEISaJJESDgA

**Comment by woefulwabbit** [comment] 2022-10-28 18:43
Duplicate of #1684 
PR at #1734

**Closed as completed** 2022-10-30 20:08 UTC
Labels: 📈 recommendations, 🧑‍⚕️ triage
