### ISSUE TITLE
[BUG] Provide a short, clear title for your Bug Report

### ISSUE THREAD

**Issue by fttf7** [Hekili/hekili#3359] opened 2024-07-24 19:47 UTC
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

My DK blood rotation is broken! Only offer a magic shield and burst CD upon engagement, and nothing afterward :D
When Blood and decay is up, it is displayed. Nothing else?
If i use the Nerien rotation, its "fine", but not up to date.

### How to Reproduce

DK spec and combat

### Player Information (Link)

https://pastebin.com/crERyCGW

### Error Messages (Link)

no error

**Comment by syrifgit** [comment] 2024-07-24 19:51
This is a duplicate of [this ticket](https://github.com/Hekili/hekili/issues/3337)

**Closed as not planned** 2024-07-24 20:15 UTC
Labels: 🐛 Bug, 🧑‍⚕️ triage
