### ISSUE TITLE
Microstuttering after leaving Combat, Looting and switching Zones

### ISSUE THREAD

**Issue by Creaper87** [Hekili/hekili#2020] opened 2022-11-22 14:11 UTC
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### WoW Version

Retail (Dragonflight)

### Describe the Issue

Microstutters after Combat / Looting its happends not only on Demolock i tested it on other Builds/Chars too.
Disabled all Addons to check it and its Hekili, first i thought its ElvUI but i can exclude it.

### How to Reproduce

Everytime i leave combat and loot corpses it stutters for a split second 

### Player Information (Link)

```Text
build: v10.0.2-1.8
level: 60 (60)
class: WARLOCK
spec: demonology

talents: annihilan_training
    antoran_armaments = 1/1
    burning_rush = 1/1
    call_dreadstalkers = 1/1
    carnivorous_stalkers = 1/1
    curses_of_enfeeblement = 1/1
    dark_accord = 1/1
    dark_pact = 1/1
    demon_skin = 2/2
    demonbolt = 1/1
    demonic_calling = 1/2
    demonic_circle = 1/1
    demonic_embrace = 1/1
    demonic_fortitude = 1/1
    demonic_gateway = 1/1
    demonic_inspiration = 1/1
    demonic_knowledge = 1/1
    demonic_meteor = 1/1
    demonic_strength = 1/1
    dread_calling = 1/1
    dreadlash = 1/1
    fel_and_steel = 1/1
    fel_armor = 2/2
    fel_domination = 1/1
    fel_might = 1/1
    fel_sunder = 1/1
    fel_synergy = 1/1
    frequent_donor = 1/1
    from_the_shadows = 1/1
    grimoire_felguard = 1/1
    grimoire_of_synergy = 2/2
    implosion = 1/1
    infernal_command = 2/2
    lifeblood = 2/2
    mortal_coil = 1/1
    ripped_through_the_portal = 2/2
    shadowfury = 1/1
    shadows_bite = 1/1
    soul_conduit = 2/2
    soul_link = 1/1
    soul_strike = 1/1
    summon_demonic_tyrant = 1/1
    sweet_souls = 1/1
    the_expendables = 1/1
    wrathful_minion = 1/1

pvptalents: fel_obelisk
   master_summoner
   precognition

covenant: none

conduits: none

soulbinds: []

sets: none

gear: ancient_crosswrapped_sandals = 1
    catastrophe_signet = 1
    cloudburst_bindings = 1
    cloudburst_hood = 1
    cloudburst_mantle = 1
    cloudburst_mitts = 1
    cloudburst_robes = 1
    cloudburst_sash = 1
    firestorm_cape = 1
    miners_sturdy_trousers = 1
    raiders_lost_spire = 1
    seal_of_elemental_disasters = 1
    storm_hunters_insignia = 1
    torc_of_calamities = 1
    versatile_storm_lure = 1

legendaries: none

itemIDs: 193806, 193810, 199348, 199350, 199351, 199353, 199354, 199355, 199381, 199382, 199383, 199386, 199555, 199645, 201307

settings: aoe = 3
    buffPadding = 0
    combatRefresh = 0.1
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = true
    cycle_min = 6
    damage = true
    damageDots = false
    damageExpiration = 6
    damageOnScreen = true
    damagePets = false
    damageRange = 0
    debuffPadding = 0
    enabled = true
    enhancedRecheck = false
    gcdSync = true
    maxTime = 14.860174179077
    nameplateRange = 8
    nameplates = false
    noFeignedCooldown = false
    package = Demonology
    petbased = false
    potion = spectral_intellect
    regularRefresh = 0.5
    throttleRefresh = false
    throttleTime = false
    dcon_imps = 0

toggles: cooldowns = false 
    custom1 = false 
    custom2 = false 
    defensives = false 
    essences = true 
    interrupts = false 
    mode = automatic 
    potions = false 

keybinds: 
    blood_fury              = G   [01]
    burning_rush            = MwU [03]
    call_dreadstalkers      = 2   [01]
    curse_of_exhaustion     = S4  [02]
    curse_of_tongues        = S5  [02]
    dark_pact               = R   [03]
    demonbolt               = S1  [02]
    demonic_circle_teleport = MwD [03]
    demonic_gateway         = SMwU[01]
    demonic_strength        = F1  [03]
    drain_life              = SF  [04]
    fear                    = ST  [04]
    fel_domination          = M3  [01]
    grimoire_felguard       = F2  [03]
    hand_of_guldan          = ^   [03]
    health_funnel           = SX  [04]
    healthstone             = T   [02]
    implosion               = 5   [01]
    mortal_coil             = F   [02]
    shadow_bolt             = 1   [01]
    shadowfury              = ,   [01]
    soul_strike             = 3   [01]
    summon_demonic_tyrant   = 4   [01]
    summon_felguard         = F4  [03]
    summon_pet              = F4  [03]
    unending_breath         = AS1 [04]
    unending_resolve        = SR  [03]

warnings: none
```

### Error Messages (Link)

```Text
I got no Error msgs
```

**Comment by Hekili** [comment] 2022-11-22 14:22
Please fill out "Describe the Issue" and "How to Reproduce" correctly.  I will investigate.

**Comment by Jandengit** [comment] 2022-11-26 21:39
Just wanted to add I'm having the exact same issue and after enabling/disabling different addons I narrowed it down to it being this one

**Comment by Hekili** [comment] 2022-11-26 22:02
You're welcome to provide more details to help with investigation of the issue.

**Comment by Jandengit** [comment] 2022-11-26 23:23
Some info and more testing:

I only have Hekili addon enabled, everything else disabled.
It happens on all specs and characters I have tried with since noticing the issue.
I can't be certain but I believe it only started happening with a recent update as I didn't notice it previously, but can't say for sure.
For me the stutter seem to only happen when I loot things or when I zone into instances/new areas, but no stutter on dropping or entering combat.
The stutter for me usually comes in 2. My character kneels down to loot mobs (or chests as well) and I get the first stutter, then 1 second later the second stutter happens.
I've tried pausing the addon and it still happens.

Clip of it happening. It's very subtle you can see it as my character moves away after looting, two microstutters with about a secon between them. https://www.youtube.com/watch?v=kGioLHgaAuc

I will continue to try different things, sorry if it's not very helpful

**Comment by marekCs** [comment] 2022-11-27 12:40
It’s really not caused by Hekili. Try 1) https://www.wowhead.com/news/a-quick-bandaid-solution-for-fps-stutter-issues-329579 2) switch to Directx11

**Comment by vond82** [comment] 2022-11-27 14:13
The fix on that link is not a thing since a day or two after that post was made as Blizzard force-changed that setting for everyone. So unless someone manually changed that back after, it will already be set

**Comment by Creaper87** [comment] 2022-11-27 15:18
i tried both solutions and it doesnt change anything same stuttering on the things as before.
Tested it today on classic since i have seen that hekili works for it too and there it no stutter after combat drops but on looting and zone switching it happens like on retail tho.
This was with only Hekili active and no other Addon.

**Comment by marekCs** [comment] 2022-11-27 17:11
Okay. The only thing I can think of next is that the addon keeps track of the nameplates around it. Try disabling the nameplates if you see any change. And also try to disable Recommended switching function. I'm just shooting this from the hip but maybe there will be a change.

**Comment by Creaper87** [comment] 2022-11-27 17:51
I tried some things now and none of it fixed it

- Disabled Enemy Nameplates
- Switched off Recommended setting
- Turned on only Single Target Rotation
- Pause Hekili
- Disabled Hekili in Hekili options (Addon was still loaded in background)

**Comment by marekCs** [comment] 2022-11-27 17:52
How many Haste you have?

**Comment by Creaper87** [comment] 2022-11-27 17:56
This is on all chars, live, beta level 70 and wotlk so its diffrent

**Comment by marekCs** [comment] 2022-11-27 17:59
Then I don't know. But it doesn't do it to me, and I think you're probably alone because someone else would have come forward too. It did for me on Frost Mage in Beta but it was because a small Haste (about 2%) and calculating about GCD.

**Comment by Creaper87** [comment] 2022-11-27 18:03
there is actually a guy  some posts above with the same problem he posted a video clip of it and its exactly the same issue, but ya it seems pretty rare. my friends didnt have this bug

**Comment by Jandengit** [comment] 2022-11-27 18:07
> there is actually a guy some posts above with the same problem he posted a video clip of it and its exactly the same issue, but ya it seems pretty rare. my friends didnt have this bug

Yep. and I also just tried that wowhead quickfix, did nothing to solve it. :(

**Comment by Creaper87** [comment] 2022-11-27 19:54
I fixed the stutters after leaving combat, i was using the addon Auto Healthstone Macro and even if you disable the addon you still have the macro for it in your bars. This addon has some trouble togther with hekili at least for me.

But still got stutter while looting and zoning like Jandengit was showing in the clip.

**Comment by Hekili** [comment] 2022-11-28 06:19
Version 10.0.2-1.8.6 has some updates that may address this issue.

**Comment by Jandengit** [comment] 2022-11-28 07:21
Confirmed for me: The loot lag is now completely gone! (v10.0.2-1.8.8) I can still feel a slight stutter on zoning but that is nothing that bothers me personally. Thank you for the addon, and the fix :)

**Comment by Hekili** [comment] 2022-11-28 16:39
Thanks.  There are some lingering issues I'm addressing, but I'll close this ticket in favor of the other.

**Closed as completed by Hekili** 2022-11-28 16:39 UTC
Labels: 🐛 Bug, retail

**Comment by brett1337** [comment] 2022-12-22 22:40
Just curious if you have implemented anything addressing those lingering issues? I'm in a strange situation where I am completely freezing for a full second every 5 minutes or so. I've been debugging this heavily for the last week and determined it was hekili. I assume I am 1/million situation.
