### ISSUE TITLE
[REC] Beast cleave buff is not recogniszed by addon

### ISSUE THREAD

**Issue by Drizzt1990** [Hekili/hekili#3340] opened 2024-07-24 10:07 UTC
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Addon recommends multishot during AoE situations even though beast cleave is still up and has enough duration.

Pausing recommendations show buff.beast_cleave.remains as 0 
![grafik](https://github.com/user-attachments/assets/edecd708-d2dd-494e-a759-fc2d7b7646e6)

### How to Reproduce

1. Enter game as BM
2. pick multishot and beast cleave talents
3. go to multi target dummys
4. multishot

### Snapshot (Link)

https://pastebin.com/yyd9cqxX

**Comment by syrifgit** [comment] 2024-07-24 14:57
This is a duplicate of [This ticket](https://github.com/Hekili/hekili/issues/3341) which is more detailed. You can add your info there.

**Closed as not planned** 2024-07-24 15:12 UTC
Labels: 📈 recommendations, 🧑‍⚕️ triage
