### ISSUE TITLE
[Warlock Demo] Reconsider priority taking into account Felguard spell executions not allowing other casts like DStr or Guillotine

### ISSUE THREAD

**Issue by humidboot** [Hekili/hekili#2047] opened 2022-11-29 19:23 UTC
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

The default priority for Warlock Demonology doesn't take into consideration if the felguard pet is executing the Felstorm / Guillotine or not to cast other felguard spells. If during the rotation it coincides that Hekili asks you to execute Demonic Strength (or Guillotine) but the felsguard has started to execute Felstorm / Guillotine, you will end with Hekili suggesting an spell you cannot execute for some time (until felsguard finishes Felstorm or Guillotine).
From my point of view, hekili should take into consideration what Felguard is doing:
- If Felstorm is being executed -> Guillotine or Demonic Strength cannot be cast
- If Guillotine is being executed -> Demonic Strength cannot be cast

### How to Reproduce

1. Enter the game as Warlock Demonology
2. Take the talents Demonic Strength, Guillotine
3. Summon Felguard
4. Start normal AOE rotation
5. There will be sometimes when Hekili ask you to execute Demonic Strength or Guillotine, but you are not able to, because felstorm is being executed by felguard

### Talent Loadout

BoQAbtPS25JQs0VfQSDmhm+p3ggkkkIBSTjg0SSSkGAAAAA0igECJSiEJSLtkkgAAAAAAA

### Snapshot

*unreadable snapshot deleted*

### Additional Information

You cab see the problem in steps 39 (guillotine) and 41 (Demonic Strength) of the Snapshop: You cannot executed the recommendation of Demonic Strength because guillotine is being executed

### Contact Information

Discord: HumiD#4780

**Comment by Hekili** [comment] 2022-12-02 00:23
There's a reason snapshots are supposed to be put on Pastebin and linked; yours was stripped of all line-breaks and unreadable.

But yes, Demonic Strength and Guillotine should not be recommended while the Felguard is Felstorming.  Will fix.

**Comment by Tzuyume** [comment] 2022-12-02 18:30
Having the same issue atm, here is a snapshot if it helps. https://pastebin.com/jewQS3cp

**Comment by Hekili** [comment] 2022-12-02 19:53
This will be addressed in the next release.

**Closed as completed by Hekili** 2022-12-02 19:53 UTC
Labels: 📈 recommendations, retail

**Comment by xinni** [comment] 2022-12-02 21:27
I got the same issue, and thanks for addressing this. However, in my case, Demonic Strength is recommended while the Guillotine takes effect.
> If Guillotine is being executed -> Demonic Strength cannot be cast

I think the possible solution is to put Guillotine as a pet buff just like the felstorm.

**Comment by xinni** [comment] 2022-12-03 08:14
@Hekili I tested the latest version which contains [this change](https://github.com/Hekili/hekili/commit/5f1fb96cc39a6d6e0f29360dfa7da3bc496ff48a). The issue still exists. Root cause ^^
Also, I tested that soul_strike can be cast during the felstorm.

**Comment by Hekili** [comment] 2022-12-06 17:04
@xinni 

> Root cause ^^

?

**Comment by xinni** [comment] 2022-12-06 21:36
Never mind. I mean the root cause described in the previous comment. I saw you addressed this issue.
