### ISSUE TITLE
Arcane Mage using Evocation at high mana w/o Siphon Storm

### ISSUE THREAD

**Issue by chiraino** [Hekili/hekili#2326] opened 2023-01-25 20:40 UTC
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Arcane Mage recommends Evocation when at full mana and without Siphon Storm talent.  Without Siphon Storm, there's no reason to use Evocation except at very low mana.

### How to Reproduce

1. Spec arcane.
2. Don't spec Siphon Storm.

### Player Information (Link)

https://pastebin.com/p8041bYm

### Error Messages (Link)

https://pastebin.com/p8041bYm

**Comment by Hekili** [comment] 2023-01-25 20:56
This should've been a ticket for recommendations, not a bug report.  You'll need to provide a snapshot.

## Snapshot

Please supply a Snapshot of the addon's decision-making when you are seeing this issue in-game. This is not a screenshot. To generate a Snapshot, please complete the following steps.

 * Log into your WoW character.
 * Recreate the issue you are reporting (i.e., generate 5 Holy Power).
 * When you see the recommendation you disagree with, press ALT-SHIFT-P to Pause and Snapshot (or use ALT-SHIFT-[ to Snapshot without pausing).
   * You can change these keybindings in /hekili > Toggles if needed.
   * If you take the snapshot at a different time, it will not be useful and you'll be asked to submit a new one.
 * Type /hekili and press Enter.
 * Open the Snapshots section on the left side.
 * Select the snapshot that shows the recommendation that you disagree with.
   * Snapshots are labeled with your specialization, the display in question (usually, you'll choose Primary), and the recommendations the addon made with their timings.
 * Click in the Export Snapshot box, press CTRL+A to select all text including hidden text and press CTRL+C to copy.
 * Open [https://pastebin.com](https://github.com/Hekili/hekili/issues/Pastebin), use CTRL+V to paste the snapshot text, then click Create New Paste.
 * Provide the Pastebin ***link*** in a new comment.

This step is essential, as most issues are related to specific classes, specializations, gear, talent choices, or other game systems.  If you do not provide this information, I cannot triage your problem.

**Comment by chiraino** [comment] 2023-01-26 01:29
https://pastebin.com/QqRv4GvA

**Comment by Hekili** [comment] 2023-01-26 02:30
Thanks.  I've adjusted that entry for Evocation as I don't believe it is accomplishing what the theorycrafters intended for it.  This is addressed in 1.0.3.  Thanks!

**Closed as completed by Hekili** 2023-01-26 02:30 UTC
Labels: 📈 recommendations, 🧑‍⚕️ triage
