### ISSUE TITLE
LUA Error on Login

### ISSUE THREAD

**Issue by grand-lotus-iroh** [Hekili/hekili#662] opened 2020-12-09 21:16 UTC
here is pastebin of error below: https://pastebin.com/01XDzWH6

```
Message: Interface\AddOns\Hekili\Options-Options.lua:3943: attempt to concatenate local 'k' (a nil value)
Time: Wed Dec  9 16:14:40 2020
Count: 1
Stack: Interface\AddOns\Hekili\Options-Options.lua:3943: attempt to concatenate local 'k' (a nil value)
[string "@Interface\AddOns\Hekili\Events.lua"]:56: in function <Interface\AddOns\Hekili\Events.lua:50>

Locals: self = <unnamed> {
 0 = <userdata>
}
event = "GET_ITEM_INFO_RECEIVED"
eventHandlers = <table> {
 1 = <function> defined @Interface\AddOns\Hekili\Events.lua:213
}
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
 1 = <function> defined @Interface\AddOns\Hekili\Events.lua:213
}
(for control) = 1
i = 1
handler = <function> defined @Interface\AddOns\Hekili\Events.lua:213
handlers = <table> {
 SOULBIND_ACTIVATED = <table> {
 }
 PLAYER_ENTERING_WORLD = <table> {
 }
 ACTIONBAR_PAGE_CHANGED = <table> {
 }
 VARIABLES_LOADED = <table> {
 }
 SOULBIND_NODE_UNLEARNED = <table> {
 }
 CVAR_UPDATE = <table> {
 }
 UPDATE_SHAPESHIFT_FORM = <table> {
 }
 PLAYER_SPECIALIZATION_CHANGED = <table> {
 }
 EXECUTE_CHAT_LINE = <table> {
 }
 PLAYER_TOTEM_UPDATE = <table> {
 }
 ACTIONBAR_SHOWGRID = <table> {
 }
 SOULBIND_FORGE_INTERACTION_STARTED = <table> {
 }
 DISPLAY_SIZE_CHANGED = <table> {
 }
 PLAYER_CONTROL_LOST = <table> {
 }
 SOULBIND_PATH_CHANGED = <table> {
 }
 SOULBIND_NODE_UPDATED = <table> {
 }
 UNIT_SPELLCAST_SENT = <table> {
 }
 SOULBIND_FORGE_INTERACTION_ENDED = <table> {
 }
 SOULBIND_NODE_LEARNED = <table> {
 }
 SOULBIND_PENDING_CONDUIT_CHANGED = <table> {
 }
 PLAYER_REGEN_ENABLED = <table> {
 }
 SOULBIND_CONDUIT_UNINSTALLED = <table> {
 }
 SOULBIND_CONDUIT_INSTALLED = <table> {
 }
 PLAYER_TARGET_CHANGED = <table> {
 }
 SOULBIND_CONDUIT_CHARGES_UPDATED = <table> {
 }
 SPELL_DATA_LOAD_RESULT = <table> {
 }
 UPDATE_BINDINGS = <table> {
 }
 COMBAT_LOG_EVENT_UNFILTERED = <table> {
 }
 ENCOUNTER_START = <table> {
 }
 GET_ITEM_INFO_RECEIVED = <table> {
 }
 PLAYER_STARTED_MOVING = <table> {
 }
 ACTIONBAR_SLOT_CHANGED = <table> {
 }
 PLAYER_TALENT_UPDATE = <table> {
 }
 PLAYER_CONTROL_GAINED = <table> {
 }
 PLAYER_EQUIPMENT_CHANGED = <table> {
 }
 PLAYER_STOPPED_MOVING = <table> {
 }
 ENCOUNTER_END = <table> {
 }
 BARBER_SHOP_CLOSE = <table> {
 }
 BARBER_SHOP_OPEN = <table> {
 }
 ACTIONBAR_HIDEGRID = <table> {
 }
 PLAYER_REGEN_DISABLED = <table> {
 }
}
handlerCount = <table> {
 GET_ITEM_INFO_RECEIVED_1 = 68
 COMBAT_LOG_EVENT_UNFILTERED_1 = 138
 UNIT_AURA_player_1 = 1
 COMBAT_LOG_EVENT_UNFILTERED_2 = 138
 ACTIONBAR_SLOT_CHANGED_1 = 7
 PLAYER_ENTERING_WORLD_3 = 1
 UNIT_SPELLCAST_SUCCEEDED_player_1 = 1
 PLAYER_ENTERING_WORLD_1 = 1
 PLAYER_ENTERING_WORLD_2 = 1
 UNIT_INVENTORY_CHANGED_player_1 = 63
 SPELL_DATA_LOAD_RESULT_1 = 1701
}
```

**Comment by Hekili** [comment] 2020-12-09 21:41
Duplicate of #660

**Closed as completed by Hekili** 2020-12-09 21:41 UTC
Labels: 🐛 Bug

**Comment by DiscordGregory** [comment] 2021-11-02 20:46
I'm getting this error, using the current version 9.1.5-1.0.0

1x Hekili\Events.lua:115: Attempt to register unknown event "SOULBIND_CONDUIT_CHARGES_UPDATED"
[string "=[C]"]: in function `RegisterEvent'
[string "@Hekili\Events.lua"]:115: in function `RegisterEvent'
[string "@Hekili\Shadowlands\SoulbindConduits.lua"]:518: in main chunk

Locals:
(*temporary) = <unnamed> {
 0 = <userdata>
}
(*temporary) = "SOULBIND_CONDUIT_CHARGES_UPDATED"
