### ISSUE TITLE
C_Traits.GetTreeInfo LUA Error

### ISSUE THREAD

**Issue by whoaisjustin** [Hekili/hekili#1863] opened 2022-11-03 00:06 UTC
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### WoW Version

Retail (Dragonflight)

### Describe the Issue

LUA Error (included below) upon logging in with any specialization (supported). 

### How to Reproduce

Enter game as any supported specialization.

### Player Information (Link)

```Text
build: v10.0.0-06.3
level: 60 (60)
class: SHAMAN
spec: enhancement

talents: ancestral_guidance
    ashen_catalyst = 1/1
    astral_shift = 1/1
    brimming_with_life = 1/1
    capacitor_totem = 1/1
    chain_lightning = 1/1
    crash_lightning = 1/1
    crashing_storms = 1/1
    earth_elemental = 1/1
    elemental_spirits = 1/1
    elemental_warding = 2/2
    elemental_weapons = 2/2
    feral_spirit = 1/1
    fire_and_ice = 1/1
    fire_nova = 1/1
    flurry = 1/1
    frost_shock = 1/1
    guardians_cudgel = 1/1
    healing_stream_totem = 1/1
    hot_hand = 2/2
    improved_lightning_bolt = 2/2
    improved_maelstrom_weapon = 2/2
    lashing_flames = 1/1
    lava_burst = 1/1
    lava_lash = 1/1
    maelstrom_weapon = 1/1
    molten_assault = 2/2
    natures_fury = 2/2
    overflowing_maelstrom = 1/1
    primordial_wave = 1/1
    raging_maelstrom = 1/1
    spirit_walk = 1/1
    stormstrike = 1/1
    sundering = 1/1
    swirling_currents = 2/2
    swirling_maelstrom = 1/1
    thundershock = 1/1
    thunderstorm = 1/1
    wind_rush_totem = 1/1
    wind_shear = 1/1
    windfury_weapon = 1/1
    winds_of_alakir = 2/2
    witch_doctors_ancestry = 2/2

pvptalents: none

covenant: night_fae

conduits: condensed_anima_sphere = 1
   essential_extraction = 1
   refreshing_waters = 1
   thunderous_paws = 1
   totemic_surge = 1
   unruly_winds = 1

soulbinds: [korayn]
   first_strike = 1
   get_in_formation = 1
   horn_of_the_wild_hunt = 1
   hunts_exhilaration = 1
   wild_hunt_strategem = 1
   wild_hunt_tactics = 1

sets: cache_of_acquired_treasures = 1

gear: cache_of_acquired_treasures = 1
    cartels_larcenous_toecaps = 1
    confiscated_bracers_of_concealment = 1
    elegy_of_the_eternals = 1
    girdle_of_the_first_gate = 1
    key_to_the_immortal_hearth = 1
    masterful_phaedrum_ring = 1
    shadowghast_necklace = 1
    shadowghast_ring = 1
    shroud_of_the_penitent = 1
    theurgic_starspeakers_adornment = 1
    theurgic_starspeakers_howl = 1
    theurgic_starspeakers_ringmail = 1
    theurgic_starspeakers_runebindings = 1
    theurgic_starspeakers_tassets = 1

legendaries: seeds_of_rampant_growth = 1
    witch_doctors_wolf_bones = 1

itemIDs: 173132, 178926, 178927, 184141, 185816, 188265, 188270, 188920, 188922, 188923, 188924, 188925, 189776, 189779, 190629

settings: aoe = 2
    buffPadding = 0
    combatRefresh = 0.1
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = false
    cycle_min = 6
    damage = false
    damageDots = false
    damageExpiration = 8
    damageOnScreen = true
    damagePets = false
    damageRange = 0
    debuffPadding = 0
    enabled = true
    enhancedRecheck = false
    gcdSync = true
    maxRefresh = 10
    maxTime = 10
    nameplateRange = 8
    nameplates = true
    noFeignedCooldown = true
    package = Enhancement
    petbased = false
    potion = potion_of_spectral_agility
    potionsReset = 20180919.1
    regularRefresh = 0.5
    throttleRefresh = false
    throttleTime = false
    filler_shock = true
    pad_lava_lash = true
    pad_windstrike = true

toggles: cooldowns = true 
    custom1 = false 
    custom2 = false 
    defensives = false 
    essences = true [overridden]
    interrupts = true [separate]
    mode = automatic 
    potions = false 

keybinds: 
    astral_shift                = S2  [02]
    cache_of_acquired_treasures = M4  [01]
    capacitor_totem             = SS  [02]
    chain_lightning             = 1   [03]
    crash_lightning             = SD  [02]
    earthbind_totem             = SMwD[01]
    fae_transfusion             = M5  [01]
    feral_spirit                = S1  [02]
    fire_nova                   = SX  [02]
    fireblood                   = SM3 [01]
    flame_shock                 = A   [03]
    frost_shock                 = X   [03]
    ghost_wolf                  = SF  [02]
    healing_stream_totem        = SMwU[01]
    healing_surge               = SA  [02]
    lava_burst                  = 2   [03]
    lava_lash                   = W   [03]
    lightning_bolt              = D   [03]
    primordial_wave             = SM5 [01]
    purge                       = SM4 [01]
    stormstrike                 = S   [03]
    sundering                   = F   [03]
    wind_shear                  = SW  [02]
    windstrike                  = S   [03]

warnings: none
```

### Error Messages (Link)

```Text
23x Usage: local treeInfo = C_Traits.GetTreeInfo(configID, treeID)
[string "=[C]"]: ?
[string "@Interface/AddOns/Blizzard_SharedTalentUI/Blizzard_SharedTalentUtil.lua"]:253: in function `GetTreeInfo'
[string "@Interface/AddOns/Blizzard_SharedTalentUI/Blizzard_SharedTalentFrame.lua"]:919: in function `UpdateTreeInfo'
[string "@Interface/AddOns/Hekili/Dragonflight/Classes.lua"]:72: in function <Interface/AddOns/Hekili/Dragonflight/Classes.lua:66>

Locals:
(*temporary) = "Usage: local treeInfo = C_Traits.GetTreeInfo(configID, treeID)"
```

### Contact Information

SMARF#4578

**Comment by FallsC0ming** [comment] 2022-11-03 00:37
Received same error on Shadow Priest and Balance Druid.

build: v10.0.0-06.2
level: 55 (55)
class: DRUID
spec: balance

talents: BYGAGX1kx6Mci9Zl2t+S+sRoPCAAAAAAAAAAAAAAAAAAAoAQiICSChkEkIAQSSkmAkDgUSkEEUAI
    astral_influence = 2/2
    celestial_alignment = 1/1
    circle_of_life_and_death = 1/1
    convoke_the_spirits = 1/1
    eclipse = 1/1
    frenzied_regeneration = 1/1
    fungal_growth = 1/1
    improved_barkskin = 1/1
    improved_sunfire = 1/1
    ironfur = 1/1
    lunar_shrapnel = 1/1
    lycaras_teachings = 3/3
    matted_fur = 1/1
    moonkin_form = 1/1
    natures_balance = 1/1
    natures_grace = 1/1
    nurturing_instinct = 3/3
    orbit_breaker = 1/1
    shooting_stars = 1/1
    solstice = 2/2
    soothe = 1/1
    stampeding_roar = 1/1
    starfall = 1/1
    starfire = 1/1
    starlord = 2/2
    starsurge = 1/1
    starweaver = 1/1
    stellar_flare = 1/1
    sunfire = 1/1
    swipe = 1/1
    syzygy = 1/1
    thick_hide = 2/2
    thrash = 1/1
    twin_moons = 1/1
    umbral_embrace = 1/2
    verdant_heart = 1/1
    waning_twilight = 2/2
    wild_charge = 1/1
    wild_mushroom = 1/1

pvptalents: none

covenant: venthyr

conduits: none

soulbinds: []

sets: none

gear: ascendent_valor_signet = 1
    burnished_warden_staff = 1
    eternal_will_of_the_martyr = 1
    inherited_cape_of_the_black_baron = 1
    inherited_insignia_of_the_horde = 1
    renowned_guild_tabard = 1
    rookies_gloves = 1
    runetender_boots = 1
    soulbearers_belt = 1
    sprigthistle_loop = 1
    stained_shadowcraft_cap = 1
    stained_shadowcraft_pants = 1
    stained_shadowcraft_spaulders = 1
    stained_shadowcraft_tunic = 1
    starshroud_bracers = 1
    swift_hand_of_justice = 1

legendaries: none

itemIDs: 122248, 122254, 122261, 122358, 122361, 122363, 122370, 122383, 122668, 134675, 175678, 175713, 181406, 181587, 181721, 69210

settings: aoe = 3
    buffPadding = 0
    combatRefresh = 0.1
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = false
    cycle_min = 6
    damage = true
    damageDots = true
    damageExpiration = 6
    damageOnScreen = true
    damagePets = false
    damageRange = 0
    debuffPadding = 0
    enabled = true
    enhancedRecheck = true
    gcdSync = true
    maxTime = 10
    nameplateRange = 8
    nameplates = false
    noFeignedCooldown = false
    package = Balance
    petbased = false
    potion = spectral_intellect
    regularRefresh = 0.5
    throttleRefresh = false
    throttleTime = false
    delay_berserking = false
    starlord_cancel = false

toggles: cooldowns = false 
    custom1 = false 
    custom2 = false 
    defensives = true 
    essences = true 
    interrupts = true 
    mode = automatic 
    potions = false 

keybinds: 
    brutal_slash          = 3   [07], 1   [09]
    ferocious_bite        = 4   [07]
    frenzied_regeneration = S1  [09]
    growl                 = S2  [09]
    ironfur               = 4   [09]
    mangle                = 2   [09]
    moonfire              = 1   [01], S1  [10]
    regrowth              = -   [01], -   [10]
    shred                 = 1   [07]
    starfall              = S3  [01], S3  [10]
    starfire              = S1  [01], 1   [10]
    starsurge             = S2  [01], S2  [10]
    stellar_flare         = 3   [01], 3   [10]
    sunfire               = 4   [01], 4   [10]
    swipe                 = 3   [07], 1   [09]
    swipe_bear            = 3   [07], 1   [09]
    swipe_cat             = 3   [07], 1   [09]
    thrash                = 2   [07], 3   [09]
    thrash_bear           = 2   [07], 3   [09]
    thrash_cat            = 2   [07], 3   [09]
    wild_charge           = S1  [07]
    wild_mushroom         = S4  [01], S4  [10]
    wrath                 = 2   [01], 2   [10]

warnings: none



**ERROR**


Message: Usage: local treeInfo = C_Traits.GetTreeInfo(configID, treeID)
Time: Wed Nov  2 20:22:34 2022
Count: 5
Stack: Usage: local treeInfo = C_Traits.GetTreeInfo(configID, treeID)
[string "=[C]"]: ?
[string "@Interface/AddOns/Blizzard_SharedTalentUI/Blizzard_SharedTalentUtil.lua"]:253: in function `GetTreeInfo'
[string "@Interface/AddOns/Blizzard_SharedTalentUI/Blizzard_SharedTalentFrame.lua"]:919: in function `UpdateTreeInfo'
[string "@Interface/AddOns/Hekili/Dragonflight/Classes.lua"]:72: in function <Interface/AddOns/Hekili/Dragonflight/Classes.lua:66>

Locals: (*temporary) = "Usage: local treeInfo = C_Traits.GetTreeInfo(configID, treeID)"

**Comment by alexnaumovich** [comment] 2022-11-03 08:06
Getting the same error with every class so far, every time I loot something.

Update: issue is reproduced both with v10.0.0-06.2 and v10.0.0-06.3. Downgrading to v10.0.0-06.1 resolves the issue.

**Comment by Fugaz1** [comment] 2022-11-03 08:30
Same here:

```
Message: Usage: local treeInfo = C_Traits.GetTreeInfo(configID, treeID)
Time: Thu Nov  3 09:27:15 2022
Count: 4
Stack: Usage: local treeInfo = C_Traits.GetTreeInfo(configID, treeID)
[string "=[C]"]: ?
[string "@Interface/AddOns/Blizzard_SharedTalentUI/Blizzard_SharedTalentUtil.lua"]:253: in function `GetTreeInfo'
[string "@Interface/AddOns/Blizzard_SharedTalentUI/Blizzard_SharedTalentFrame.lua"]:919: in function `UpdateTreeInfo'
[string "@Interface/AddOns/Hekili/Dragonflight/Classes.lua"]:72: in function <Interface/AddOns/Hekili/Dragonflight/Classes.lua:66>

Locals: (*temporary) = "Usage: local treeInfo = C_Traits.GetTreeInfo(configID, treeID)"
```

This happens on load (I run SL tables for gold) on all characters (I have all classes) since yesterday (so I would point at v10.0.0-06+).

**Comment by Eziair** [comment] 2022-11-03 11:27
Every class when log-in 
![Hekili](https://user-images.githubusercontent.com/43756971/199709397-e4c63f78-7eb5-42e5-b9c6-239fd0834ab4.jpg)

**Comment by karpana** [comment] 2022-11-03 13:27
Can confirm that I too am getting the same issue on login.
![image](https://user-images.githubusercontent.com/15716173/199732703-e1a041f0-c41b-4758-ad25-a0d2eb43afcd.png)

I had upgrded from 10.0.0-06.1 where it wasn't occuring to 10.0.0-06.3 where it is happening.

**Comment by Hekili** [comment] 2022-11-03 14:12
Duplicate of #1861

**Closed as completed by Hekili** 2022-11-03 14:12 UTC
Labels: 🐛 Bug, duplicate
