### ISSUE TITLE
Since today Unholy DK wants to use Apocalypse even if not possible

### ISSUE THREAD

**Issue by McWohlsen** [Hekili/hekili#640] opened 2020-12-07 13:57 UTC
build: v9.0.2-1.0.16
level: 60 (60)
class: DEATHKNIGHT
spec: unholy

talents: all_will_serve
    army_of_the_damned
    asphyxiate
    death_pact
    soul_reaper
    unholy_blight
    unholy_pact

pvptalents: cadaverous_pallor
   decomposing_aura
   necrotic_aura

covenant: venthyr

azerite: none

essences: [none], none

sets/legendaries/artifacts: none

gear: artisan_officers_shirt = 1
    bloodoath_signet = 1
    bracers_of_the_tenebrous_retinue = 1
    breastplate_of_brutal_dissonance = 1
    drape_of_inscrutable_purpose = 1
    grim_codex = 1
    guilewind_stone_talons = 1
    halberd_of_agthia = 1
    phial_of_putrefaction = 1
    plague_handlers_greathelm = 1
    ritual_bone_band = 1
    scarred_bloodbound_girdle = 1
    shadowghast_greaves = 1
    sin_stained_pendant = 1
    tabard_of_the_lightbringer = 1
    vile_butchers_pauldrons = 1
    warboots_of_ruthless_conviction = 1

legendaries: reanimated_shambler = 1

itemIDs: 171416, 178749, 178771, 178773, 178811, 178827, 178840, 178870, 178871, 178931, 180099, 180101, 184661, 184758, 184803, 52252, 89195

settings: aoe = 2
    buffPadding = 0
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = true
    cycle_min = 6
    damage = true
    damageDots = true
    damageExpiration = 8
    damagePets = true
    damageRange = 0
    debuffPadding = 0
    enabled = true
    gcdSync = true
    maxRefresh = 10
    maxTime = 33
    nameplateRange = 8
    nameplates = true
    package = Unholy
    petbased = false
    potion = superior_battle_potion_of_strength
    potionsReset = 20180919.1
    throttleRefresh = false
    throttleTime = false
    festermight_cycle = false

toggles: cooldowns = false
    custom1 = false
    custom2 = false
    defensives = false
    essences = true
    interrupts = true
    mode = automatic
    potions = false

**Comment by Hekili** [comment] 2020-12-07 14:07
**BEFORE SUBMITTING AN ISSUE:**

1.  Check to see if you are using the latest version of the addon.  If there is a newer alpha/beta/release version, see if your problem exists with the new version.

2.  Check to see if someone else has already opened an issue report here.  Please don't submit repeat reports.

**Describe the Bug/Issue**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
- Go to '...'
- Click on '....'
- Scroll down to '....'
- See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**WHEN SUBMITTING AN ISSUE:**

Please provide the following information.  Leaving it out may result in your ticket being ignored (because I won't have the information needed to explore your report).

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here.

**PUT ISSUE REPORT LINK HERE:**

2.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot.  This is not a screenshot.  A snapshot can be generated by binding the Pause feature on the Toggles tab.  When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab.  Copy and paste this to pastebin.com and provide the link here.
 
**PUT SNAPSHOT LINK HERE:**

3.  If reporting an error (i.e., the addon freezes and/or disables itself), please install the BugSack and BugGrabber addons as they will enable you to paste the exact error message, with detail that will help me identify where the code error is located.  You can paste the error information here or use pastebin.com for that as well.

**PUT ERROR MESSAGE(S) HERE:**

**Comment by McWohlsen** [comment] 2020-12-07 14:24
Hope this works. Sorry

Click here and press CTRL+A, CTRL+C to copy the snapshot.

build: v9.0.2-1.0.16
level: 60 (60)
class: DEATHKNIGHT
spec: unholy

talents: all_will_serve
    army_of_the_damned
    asphyxiate
    death_pact
    soul_reaper
    unholy_blight
    unholy_pact

pvptalents: cadaverous_pallor
   decomposing_aura
   necrotic_aura

covenant: venthyr

azerite: none

essences: [none], none

sets/legendaries/artifacts: none

gear: artisan_officers_shirt = 1
    bloodoath_signet = 1
    bracers_of_the_tenebrous_retinue = 1
    breastplate_of_brutal_dissonance = 1
    drape_of_inscrutable_purpose = 1
    grim_codex = 1
    guilewind_stone_talons = 1
    halberd_of_agthia = 1
    phial_of_putrefaction = 1
    plague_handlers_greathelm = 1
    ritual_bone_band = 1
    scarred_bloodbound_girdle = 1
    shadowghast_greaves = 1
    sin_stained_pendant = 1
    tabard_of_the_lightbringer = 1
    vile_butchers_pauldrons = 1
    warboots_of_ruthless_conviction = 1

legendaries: reanimated_shambler = 1

itemIDs: 171416, 178749, 178771, 178773, 178811, 178827, 178840, 178870, 178871, 178931, 180099, 180101, 184661, 184758, 184803, 52252, 89195

settings: aoe = 2
    buffPadding = 0
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = true
    cycle_min = 6
    damage = true
    damageDots = true
    damageExpiration = 8
    damagePets = true
    damageRange = 0
    debuffPadding = 0
    enabled = true
    gcdSync = true
    maxRefresh = 10
    maxTime = 33
    nameplateRange = 8
    nameplates = true
    package = Unholy
    petbased = false
    potion = superior_battle_potion_of_strength
    potionsReset = 20180919.1
    throttleRefresh = false
    throttleTime = false
    festermight_cycle = false

toggles: cooldowns = false
    custom1 = false
    custom2 = false
    defensives = false
    essences = true
    interrupts = true
    mode = automatic
    potions = false

New Recommendations for [ Primary ] requested at 15:20:38 ( 917344.41 ); using built-in ( Unholy ) priority.

RECOMMENDATION #1 ( Offset: 0.00, GCD: 0.00, Casting: 0.00 ).

    Resources: runes[ 6.00 / 6.00 ], runic_power[ 40.00 / 100.00 ]
    Checking if I'm casting ( No ) and if it is a channel ( No ).
    No whitelist.
    
    Processing precombat action list [ Unholy - precombat ].
        
        Current recommendation was NO ACTION at +60.00s.
        
        1.   potion ( precombat - 1 ) - ability disabled ( toggle )
        Time spent on this action:  0.02ms
        TimeData:Unholy-precombat-1:potion:0.02
        
        2.   azsharas_font_of_power ( precombat - 2 ) - IsUsableItem
        Time spent on this action:  0.04ms
        TimeData:Unholy-precombat-2:azsharas_font_of_power:0.04
        
        3.   raise_dead ( precombat - 3 )
        The action (raise_dead) is unusable at (0.00 + 0.00) because ability 'usable' function returned false without explanation.
        Time spent on this action:  0.11ms
        TimeData:Unholy-precombat-3:raise_dead:0.11:Post-TTR and Essential:0.05:Post Cycle:0.00:Post Usable:0.03
    
    Completed precombat action list [ Unholy - precombat ].
    
    Processing default action list [ Unholy - default ].
        
        Current recommendation was NO ACTION at +60.00s.
        
        4.   mind_freeze ( default - 1 )
        The action is not ready ( 3600.00 ) before our maximum delay window ( 17.92 ) for this query.
        Time spent on this action:  0.02ms
        TimeData:Unholy-default-1:mind_freeze:0.02
        
        5.   variable ( default - 2 )
         - variable.pooling_for_gargoyle will check this script entry ( Unholy:default:2 )
        cooldown.summon_gargoyle.remains[180.00] < 5 & talent.summon_gargoyle.enabled[false]
        Time spent on this action:  0.03ms
        TimeData:Unholy-default-2:variable:0.03:Post-TTR and Essential:0.02
        
        6.   variable ( default - 3 )
         - variable.st_planning will check this script entry ( Unholy:default:3 )
        active_enemies[1.00] = 1 & ( ! raid_event.adds.exists[false] | raid_event.adds.in[3600.00] > 15 )
        Time spent on this action:  0.02ms
        TimeData:Unholy-default-3:variable:0.02:Post-TTR and Essential:0.01
        
        7.   arcane_torrent ( default - 4 )
        The action (arcane_torrent) is usable at (0.00 + 0.00).
         - the action is ready before the current recommendation (at +0.00 vs. +60.00).
         - this entry's criteria FAILS: runic_power.deficit[60.00] > 65 & ( pet.gargoyle.active[false] | ! talent.summon_gargoyle.enabled[false] ) & rune.deficit[0.00] >= 5
        0.01 - true
        There are 1 recheck events.
        Recheck #1 ( +0.01 ) NOT MET: runic_power.deficit[60.00] > 65 & ( pet.gargoyle.active[false] | ! talent.summon_gargoyle.enabled[false] ) & rune.deficit[0.00] >= 5
        Time spent on this action:  0.24ms
        TimeData:Unholy-default-4:arcane_torrent:0.24:Post-TTR and Essential:0.03:Post Cycle:0.00:Post Usable:0.01:Post Ready/Clash:0.01:Post Stack:0.00:Pre-Script:0.00:Post-Script:0.00:Pre-Recheck:0.07:Post-Recheck Times:0.02:Pre-Recheck Loop:0.00:Recheck Loop Start:0.00:Recheck Post-Usable:0.01:Recheck Post-Stack:0.00:Recheck Post-Script:0.00:Recheck Post-Channel:0.00:Recheck Loop End:0.06:Post Recheck Loop:0.00:Post Recheck:0.00
        
        8.   blood_fury ( default - 5 ) - ability unknown
        Time spent on this action:  0.02ms
        TimeData:Unholy-default-5:blood_fury:0.02
        
        9.   berserking ( default - 6 ) - ability unknown
        Time spent on this action:  0.02ms
        TimeData:Unholy-default-6:berserking:0.02
        
        10.  lights_judgment ( default - 7 ) - ability unknown
        Time spent on this action:  0.02ms
        TimeData:Unholy-default-7:lights_judgment:0.02
        
        11.  ancestral_call ( default - 8 ) - ability unknown
        Time spent on this action:  0.02ms
        TimeData:Unholy-default-8:ancestral_call:0.02
        
        12.  arcane_pulse ( default - 9 ) - ability unknown
        Time spent on this action:  0.02ms
        TimeData:Unholy-default-9:arcane_pulse:0.02
        
        13.  fireblood ( default - 10 ) - ability unknown
        Time spent on this action:  0.02ms
        TimeData:Unholy-default-10:fireblood:0.02
        
        14.  bag_of_tricks ( default - 11 ) - ability unknown
        Time spent on this action:  0.02ms
        TimeData:Unholy-default-11:bag_of_tricks:0.02
        
        15.  outbreak ( default - 12 )
        The action (outbreak) is usable at (0.00 + 0.00) with cost of 1 runes.
         - the action is ready before the current recommendation (at +0.00 vs. +60.00).
         - this entry's criteria FAILS: dot.virulent_plague.refreshable[true] & ! talent.unholy_blight.enabled[true] & ! raid_event.adds.exists[false]
        There were no recheck events to check.
        Time spent on this action:  0.14ms
        TimeData:Unholy-default-12:outbreak:0.14:Post-TTR and Essential:0.04:Post Cycle:0.00:Post Usable:0.01:Post Ready/Clash:0.01:Post Stack:0.00:Pre-Script:0.00:Post-Script:0.01:Pre-Recheck:0.04:Post-Recheck Times:0.00:Post Recheck:0.00
        
        16.  outbreak ( default - 13 )
        The action (outbreak) is usable at (0.00 + 0.00) with cost of 1 runes.
         - the action is ready before the current recommendation (at +0.00 vs. +60.00).
         - this entry's criteria FAILS: dot.virulent_plague.refreshable[true] & ( ! talent.unholy_blight.enabled[true] | talent.unholy_blight.enabled[true] & cooldown.unholy_blight.remains[30.70] ) & active_enemies[1.00] >= 2
        There were no recheck events to check.
        Time spent on this action:  0.17ms
        TimeData:Unholy-default-13:outbreak:0.17:Post-TTR and Essential:0.02:Post Cycle:0.00:Post Usable:0.01:Post Ready/Clash:0.01:Post Stack:0.00:Pre-Script:0.00:Post-Script:0.02:Pre-Recheck:0.08:Post-Recheck Times:0.01:Post Recheck:0.00
        
        17.  outbreak ( default - 14 )
        The action (outbreak) is usable at (0.00 + 0.00) with cost of 1 runes.
         - the action is ready before the current recommendation (at +0.00 vs. +60.00).
         - this entry's criteria FAILS: runeforge.superstrain.enabled[false] & ( dot.frost_fever.refreshable[true] | dot.blood_plague.refreshable[true] )
        There were no recheck events to check.
        Time spent on this action:  0.11ms
        TimeData:Unholy-default-14:outbreak:0.11:Post-TTR and Essential:0.02:Post Cycle:0.00:Post Usable:0.01:Post Ready/Clash:0.01:Post Stack:0.00:Pre-Script:0.00:Post-Script:0.00:Pre-Recheck:0.05:Post-Recheck Times:0.00:Post Recheck:0.00
        
        18.  call_action_list ( default - 15 )
        There is no criteria for covenants.
        Action list (covenants) was found.
        + covenants
        Current recommendation was NO ACTION at +60.00s.
        
        19.  swarming_mist ( covenants - 1 )
        The action is not ready ( 44.20 ) before our maximum delay window ( 17.92 ) for this query.
        Time spent on this action:  0.02ms
        TimeData:Unholy-covenants-1:swarming_mist:0.02
        
        20.  swarming_mist ( covenants - 2 )
        The action is not ready ( 44.20 ) before our maximum delay window ( 17.92 ) for this query.
        Time spent on this action:  0.01ms
        TimeData:Unholy-covenants-2:swarming_mist:0.01
        
        21.  abomination_limb ( covenants - 3 ) - ability unknown
        Time spent on this action:  0.02ms
        TimeData:Unholy-covenants-3:abomination_limb:0.02
        
        22.  abomination_limb ( covenants - 4 ) - ability unknown
        Time spent on this action:  0.01ms
        TimeData:Unholy-covenants-4:abomination_limb:0.01
        
        23.  abomination_limb ( covenants - 5 ) - ability unknown
        Time spent on this action:  0.01ms
        TimeData:Unholy-covenants-5:abomination_limb:0.01
        
        24.  shackle_the_unworthy ( covenants - 6 ) - ability unknown
        Time spent on this action:  0.02ms
        TimeData:Unholy-covenants-6:shackle_the_unworthy:0.02
        
        25.  shackle_the_unworthy ( covenants - 7 ) - ability unknown
        Time spent on this action:  0.01ms
        TimeData:Unholy-covenants-7:shackle_the_unworthy:0.01
        Returned from list (covenants), current recommendation is NO ACTION (+60.00).
        - covenants
        
        26.  call_action_list ( default - 16 )
        There is no criteria for cooldowns.
        Action list (cooldowns) was found.
        + cooldowns
        Current recommendation was NO ACTION at +60.00s.
        
        27.  potion ( cooldowns - 1 ) - ability disabled ( toggle )
        Time spent on this action:  0.01ms
        TimeData:Unholy-cooldowns-1:potion:0.01
        
        28.  inscrutable_quantum_device ( cooldowns - 2 ) - IsUsableItem
        Time spent on this action:  0.03ms
        TimeData:Unholy-cooldowns-2:inscrutable_quantum_device:0.03
        
        29.  macabre_sheet_music ( cooldowns - 3 ) - IsUsableItem
        Time spent on this action:  0.03ms
        TimeData:Unholy-cooldowns-3:macabre_sheet_music:0.03
        
        30.  dreadfire_vessel ( cooldowns - 4 ) - IsUsableItem
        Time spent on this action:  0.03ms
        TimeData:Unholy-cooldowns-4:dreadfire_vessel:0.03
        
        31.  darkmoon_deck_voracity ( cooldowns - 5 ) - IsUsableItem
        Time spent on this action:  0.03ms
        TimeData:Unholy-cooldowns-5:darkmoon_deck_voracity:0.03
        
        32.  use_items ( cooldowns - 6 )
        Criteria for ??? FAIL at +0.00 - cooldown.apocalypse.remains[0.00] & ( ! equipped.inscrutable_quantum_device[false] | cooldown.inscrutable_quantum_device.remains[0.00] )
        
        33.  army_of_the_dead ( cooldowns - 7 ) - ability disabled ( toggle )
        Time spent on this action:  0.04ms
        TimeData:Unholy-cooldowns-7:army_of_the_dead:0.04
        
        34.  unholy_blight ( cooldowns - 8 )
        The action is not ready ( 30.70 ) before our maximum delay window ( 17.92 ) for this query.
        Time spent on this action:  0.02ms
        TimeData:Unholy-cooldowns-8:unholy_blight:0.02
        
        35.  unholy_blight ( cooldowns - 9 )
        The action is not ready ( 30.70 ) before our maximum delay window ( 17.92 ) for this query.
        Time spent on this action:  0.01ms
        TimeData:Unholy-cooldowns-9:unholy_blight:0.01
        
        36.  unholy_blight ( cooldowns - 10 )
        The action is not ready ( 30.70 ) before our maximum delay window ( 17.92 ) for this query.
        Time spent on this action:  0.01ms
        TimeData:Unholy-cooldowns-10:unholy_blight:0.01
        
        37.  dark_transformation ( cooldowns - 11 )
        The action is not ready ( 47.05 ) before our maximum delay window ( 17.92 ) for this query.
        Time spent on this action:  0.02ms
        TimeData:Unholy-cooldowns-11:dark_transformation:0.02
        
        38.  dark_transformation ( cooldowns - 12 )
        The action is not ready ( 47.05 ) before our maximum delay window ( 17.92 ) for this query.
        Time spent on this action:  0.01ms
        TimeData:Unholy-cooldowns-12:dark_transformation:0.01
        
        39.  apocalypse ( cooldowns - 13 )
        The action (apocalypse) is usable at (0.00 + 0.00).
         - the action is ready before the current recommendation (at +0.00 vs. +60.00).
        List ( cooldowns ) called from ( Unholy:default:16 ) would PASS at 0.00.
        NONE
        festering_wound.stack ... Cycling? false, cycle_debuff.stack = 0 [ 0.00 | 0 | 0 | n/a ]
        festering_wound.up ... Cycling? false, cycle_debuff.up = false [ 0.00 | 0 | 0 | n/a ]
        festering_wound.remains ... Cycling? false, cycle_debuff.remains = 0 [ 0.00 | 0 | 0 | n/a ]
        festering_wound.expires ... Cycling? false, cycle_debuff.expires = 0 [ 0.00 | 0 | 0 | n/a ]
         - this entry's criteria FAILS: active_enemies[1.00] = 1 & debuff.festering_wound.stack[0.00] >= 4 & talent.unholy_blight.enabled[true] & talent.army_of_the_damned.enabled[true] & runeforge.deadliest_coil.enabled[false] & conduit.convocation_of_the_dead.rank[0.00] >= 5
        festering_wound.stack ... Cycling? false, cycle_debuff.stack = 0 [ 0.00 | 0 | 0 | n/a ]
        festering_wound.up ... Cycling? false, cycle_debuff.up = false [ 0.00 | 0 | 0 | n/a ]
        festering_wound.remains ... Cycling? false, cycle_debuff.remains = 0 [ 0.00 | 0 | 0 | n/a ]
        There were no recheck events to check.
        Time spent on this action:  0.35ms
        TimeData:Unholy-cooldowns-13:apocalypse:0.35:Post-TTR and Essential:0.01:Post Cycle:0.00:Post Usable:0.01:Post Ready/Clash:0.01:Post Stack:0.02:Pre-Script:0.00:Post-Script:0.04:Pre-Recheck:0.21:Post-Recheck Times:0.03:Post Recheck:0.00
        
        40.  apocalypse ( cooldowns - 14 )
        The action (apocalypse) is usable at (0.00 + 0.00).
         - the action is ready before the current recommendation (at +0.00 vs. +60.00).
        List ( cooldowns ) called from ( Unholy:default:16 ) would PASS at 0.00.
        NONE
        festering_wound.stack ... Cycling? false, cycle_debuff.stack = 0 [ 0.00 | 0 | 0 | n/a ]
        festering_wound.up ... Cycling? false, cycle_debuff.up = false [ 0.00 | 0 | 0 | n/a ]
        festering_wound.remains ... Cycling? false, cycle_debuff.remains = 0 [ 0.00 | 0 | 0 | n/a ]
         - this entry's criteria FAILS: debuff.festering_wound.stack[0.00] >= 4 & active_enemies[1.00] = 1 & talent.unholy_blight.enabled[true] & conduit.convocation_of_the_dead.rank[0.00] >= 5 & talent.army_of_the_damned.enabled[true] & runeforge.deadliest_coil.enabled[false] & debuff.unholy_blight_debuff.up[false]
        festering_wound.stack ... Cycling? false, cycle_debuff.stack = 0 [ 0.00 | 0 | 0 | n/a ]
        festering_wound.up ... Cycling? false, cycle_debuff.up = false [ 0.00 | 0 | 0 | n/a ]
        festering_wound.remains ... Cycling? false, cycle_debuff.remains = 0 [ 0.00 | 0 | 0 | n/a ]
        There were no recheck events to check.
        Time spent on this action:  0.28ms
        TimeData:Unholy-cooldowns-14:apocalypse:0.28:Post-TTR and Essential:0.02:Post Cycle:0.00:Post Usable:0.01:Post Ready/Clash:0.01:Post Stack:0.01:Pre-Script:0.00:Post-Script:0.02:Pre-Recheck:0.17:Post-Recheck Times:0.03:Post Recheck:0.00
        
        41.  apocalypse ( cooldowns - 15 )
        The action (apocalypse) is usable at (0.00 + 0.00).
         - the action is ready before the current recommendation (at +0.00 vs. +60.00).
        List ( cooldowns ) called from ( Unholy:default:16 ) would PASS at 0.00.
        NONE
        festering_wound.stack ... Cycling? false, cycle_debuff.stack = 0 [ 0.00 | 0 | 0 | n/a ]
        festering_wound.up ... Cycling? false, cycle_debuff.up = false [ 0.00 | 0 | 0 | n/a ]
        festering_wound.remains ... Cycling? false, cycle_debuff.remains = 0 [ 0.00 | 0 | 0 | n/a ]
         - this entry's criteria PASSES: active_enemies[1.00] = 1 & debuff.festering_wound.stack[0.00] >= 4 & ! talent.unholy_blight.enabled[true] | talent.army_of_the_damned.enabled[true] & ( ! runeforge.deadliest_coil.enabled[false] | conduit.convocation_of_the_dead.rank[0.00] < 5 ) | talent.unholy_assault.enabled[false] & conduit.convocation_of_the_dead.rank[0.00] >= 5
        festering_wound.stack ... Cycling? false, cycle_debuff.stack = 0 [ 0.00 | 0 | 0 | n/a ]
        festering_wound.up ... Cycling? false, cycle_debuff.up = false [ 0.00 | 0 | 0 | n/a ]
        festering_wound.remains ... Cycling? false, cycle_debuff.remains = 0 [ 0.00 | 0 | 0 | n/a ]
        Action chosen:  apocalypse at 0.00!
        Returned from list (cooldowns), current recommendation is apocalypse (+0.00).
        - cooldowns
        The recommended action (apocalypse) is ready in less than 0.2s; exiting list (default).
    
    Completed default action list [ Unholy - default ].
    Recommendation is apocalypse at 0.00 + 0.00.
    Recommendation #1 is apocalypse at 0.00s (0.00s).
    Time spent generating recommendations:  3.68ms

**Comment by Hekili** [comment] 2020-12-07 16:11
This should be resolved in 1.0.17

**Closed as completed by Hekili** 2020-12-07 16:11 UTC
Labels: 🐛 Bug
