### ISSUE TITLE
Warlock - Affliction - Unstable affliction treated as a stackable debuff

### ISSUE THREAD

**Issue by r3d5h1f7** [Hekili/hekili#463] opened 2020-10-15 13:03 UTC
**BEFORE SUBMITTING AN ISSUE:**

1.  Check to see if you are using the latest version of the addon.  If there is a newer alpha/beta/release version, see if your problem exists with the new version.
v9.0.1-1.0.6

2.  Check to see if someone else has already opened an issue report here.  Please don't submit repeat reports.
Saw a similar issue report closed for incorrect submission.

**Describe the Bug/Issue**
In the latest version of Hekili, Unstable Affliction is, I believe, treated as a stackable debuff again.

**To Reproduce**
 - Initiate combat
 - Execute cast sequence up until Unstable Affliction recommendation shows up

**Expected behavior**
Previous version had UA treated more appropriately (as a non-stackable debuff like Agony, Corruption, etc.)

**Screenshots**
Cooldowns toggled off:
![image](https://user-images.githubusercontent.com/72924841/96129713-aacdde80-0eff-11eb-87d6-a22c8a517d04.png)

Cooldowns toggled on:
![image](https://user-images.githubusercontent.com/72924841/96129607-8245e480-0eff-11eb-9e5c-60060adb553a.png)

Unstable Affliction recommended to cast more than once:
![image](https://user-images.githubusercontent.com/72924841/96128632-44948c00-0efe-11eb-97b2-a1f32595fa35.png)

**WHEN SUBMITTING AN ISSUE:**

Please provide the following information.  Leaving it out may result in your ticket being ignored (because I won't have the information needed to explore your report).

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here.

https://pastebin.com/9BjFdtVN

2.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot.  This is not a screenshot.  A snapshot can be generated by binding the Pause feature on the Toggles tab.  When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab.  Copy and paste this to pastebin.com and provide the link here.
 
**https://pastebin.com/cpaREbb4**

3.  If reporting an error (i.e., the addon freezes and/or disables itself), please install the BugSack and BugGrabber addons as they will enable you to paste the exact error message, with detail that will help me identify where the code error is located.  You can paste the error information here or use pastebin.com for that as well.

**PUT ERROR MESSAGE(S) HERE:**

**Comment by Hekili** [comment] 2020-10-15 13:37
Great report.  The issue is that the addon isn't modeling the application of Cascading Calamity from your Azerite.  It's fixed in the next build.

**Closed as completed by Hekili** 2020-10-15 13:37 UTC

**Comment by Vanrot** [comment] 2020-10-15 13:47
sorry，My English is very poor, I try my best to express what I mean
1.   I have the same problem，the spell '**Unstable Affliction**' is always shows multiple
![problem1](https://user-images.githubusercontent.com/72926216/96137821-b33e0d80-0f2f-11eb-90ea-3cef801088f4.png)

2.   'Current Mode' is not running correctly。No matter how i choose the 'Display Mode'，it always use “Single”，the spell '**Seed of Corruptionhas**' never been shown
![problem2](https://user-images.githubusercontent.com/72926216/96137872-c2bd5680-0f2f-11eb-8d59-57fa891c6746.png)

thx

**Comment by Hekili** [comment] 2020-10-15 13:53
Target detection for ranged classes are based on things you've hit.  You can't count targets at range otherwise.  The Unstable Affliction piece is addressed in the next release.

**Comment by Vanrot** [comment] 2020-10-15 14:35
> Target detection for ranged classes are based on things you've hit. You can't count targets at range otherwise. The Unstable Affliction piece is addressed in the next release.

hi，Regarding my second question：
I have selected the target
if i choose the '**Auto**'，it always use “**Single**”，the spell '**Seed of Corruptionhas**' never been shown
![problem3](https://user-images.githubusercontent.com/72926216/96142463-b38cd780-0f34-11eb-8d3f-874d6f9b9365.png)
![problem6](https://user-images.githubusercontent.com/72926216/96142746-01094480-0f35-11eb-8832-bdbc8237e5cb.png)


if i choose the '**AOE**'，It works well
![problem4](https://user-images.githubusercontent.com/72926216/96142663-ed5dde00-0f34-11eb-95ea-6966ee22c160.png)
![problem5](https://user-images.githubusercontent.com/72926216/96143536-c358eb80-0f35-11eb-8394-8c44465e0b35.png)

**Comment by Hekili** [comment] 2020-10-15 14:41
Auto = Addon makes recommendations based on how many targets it has detected.
Single = Addon makes recommendations as though there is only 1 target even if there are multiple detected.
AOE = Addon makes recommendations as though there are X or more targets (set in spec options), even if fewer are detected.
Dual = Addon has 2 displays, one for single-target, one for multiple targets.
Reactive = Addon has 2 displays, one for single-target, one that appears when multiple targets are detected.

You can set a keybinding to manually swap between those modes, if you want to manually control.

Or you can leave it Auto, hit things you want to hit, and the addon will follow your lead.

**Comment by r3d5h1f7** [comment] 2020-10-15 15:00
> Great report. The issue is that the addon isn't modeling the application of Cascading Calamity from your Azerite. It's fixed in the next build.

Just checked myself. Yes, this appears to be exactly the case. After Cascading Calamity proc, UA disappears from queue for the entire duration of the UA debuff/CC buff.
