### ISSUE TITLE
Vengeance DH Fel Desolation/Fel Devastation Hangs on Fel Devastation

### ISSUE THREAD

**Issue by thykk3r** [Hekili/hekili#3665] opened 2024-09-05 19:45 UTC
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Hands on fel desolation when its actually on CD. Its either thinking it has multiple charges, is screwing up logic with fel devastation, but likely is missing a Cancel Meta Buff before it ( although sometimes that logic works)

### How to Reproduce

Just play vengeance with my talents long enough and it will happen quickly.
![896796796](https://github.com/user-attachments/assets/32477cef-46ac-46bc-9852-458492fbe745)

### Snapshot (Link)

https://pastebin.com/vttwUgV5

**Comment by Redstoner875** [comment] 2024-09-05 19:54
I have this same issue as well. Also in large pulls, it'll reccomend a LOT of soul cleave which is unoptimal afaik, and instead should build up souls for spirit bombs esp in meta. For example in the rookery, after you drop down after first boss, when I pull the entire area down to the second boss, it reccomends 2-3 spirit bombs, and then just says to spam soul cleaves.

**Comment by dannym314** [comment] 2024-09-10 19:42
Yes I have had this issue (perhaps fixed now?), and Redstoner's issue. Also it often is recommending my next 2 abilities to be Fracture even though I am capped on souls and fury. If there's some complex interplay that makes 2x Fracture my best option, I cannot find it, and it feels like it can't be the case.

Edit - I have captured the 2x Fracture issue:

- https://imgur.com/gallery/2x-fracture-PhWx47S  -- screenshot. Green arrow points at 5 souls, fury bar beneath at 170. Red arrow points to Hekili suggestion.

- https://pastebin.com/YAqk7WCh  -- snapshot

I would make this a unique post, but there seems to be quite a few problems with VDH - such as not taking advantage of the new Demonsurge talent after you use Fel Devestation (ie. one spirit bomb, one soul cleave before leaving demon form to trigger the big AOE). There is also an order in which you should be using empowered abilities to take advantage of Demonsurge when in Meta, but it's a complex interplay of requirements.

I will try and capture the others when I have more time.

**Comment by Hekili** [comment] 2024-09-10 21:02
> Also in large pulls, it'll reccomend a LOT of soul cleave which is unoptimal afaik, and instead should build up souls for spirit bombs esp in meta.

Open a ticket for that with snapshots of it happening.  I have to see why the addon is arriving at the recommendation to be able to analyze and resolve it.

The root cause of this ticket is likely that Fel Dev and Fel Des need to be distinguished from one another.  I'll take a look.

**Comment by Hekili** [comment] 2024-09-12 18:31
> * [pastebin.com/YAqk7WCh](https://pastebin.com/YAqk7WCh)  -- snapshot

Fracture is recommended here because `demonsurge_hardcast` isn't applied, which is a virtual aura.  I'll check to see that it is implemented/triggered correctly.

**Comment by Hekili** [comment] 2024-09-13 06:41
1.0.13 will have major updates for Demonsurge builds.

**Comment by dannym314** [comment] 2024-09-13 18:40
FWIW all of the issues (including ones I hadn't mentioned yet) seem to have been fixed by this major update. Seems very smooth now.

**Closed as completed** 2024-09-16 00:56 UTC
Labels: 📈 recommendations, 🧑‍⚕️ triage
