### ISSUE TITLE
[BUG] Assassination repeatedly fails to make recommendations

### ISSUE THREAD

**Issue by aaronlilla** [Hekili/hekili#3863] opened 2024-09-26 07:03 UTC
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

During dungeons and raids (can't seem to replicate it on just the dummies) while playing assassination rogue it will fail to make recommendations quite often, and will very often automatically take snapshots. 

### How to Reproduce

Enter game as Assassination rogue, enter key, do key

### Player Information (Link)

https://pastebin.com/Ns2AxrsA

### Error Messages (Link)

https://pastebin.com/Ns2AxrsA

### Additional Information

Here are some pastebin's from a few packs in a key that automatically generated

https://pastebin.com/Ns2AxrsA
https://pastebin.com/ahfHKeAQ
https://pastebin.com/n8NHS8fT
https://pastebin.com/kg2u0DqD

**Comment by syrifgit** [comment] 2024-09-26 13:36
![image](https://github.com/user-attachments/assets/d071d3c6-2109-4a10-a46d-883f197dcd26)


This is a duplicate of https://github.com/Hekili/hekili/issues/3853 , please add your snapshots there.

**Closed as not planned by syrifgit** 2024-09-26 13:36 UTC
Labels: 🐛 Bug, 🧑‍⚕️ triage
