### ISSUE TITLE
 [Surv hunter] Lost in trinket rotation

### ISSUE THREAD

**Issue by Dragonfo** [Hekili/hekili#1430] opened 2022-03-16 11:19 UTC
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Doesn't show [Cache of Acquired Treasures](https://www.wowhead.com/item=188265/cache-of-acquired-treasures?bonus=6805) trinket in Surv rotation .

### How to Reproduce

Start rotation from the pool and there is no recommendation.

### Snapshot (Link)

https://pastebin.com/2U27k9UT

**Comment by Hekili** [comment] 2022-03-16 13:43
Duplicate of #1428; investigating.

**Closed as completed by Hekili** 2022-03-16 13:43 UTC
Labels: 📈 recommendations, 🧑‍⚕️ triage
