### ISSUE TITLE
[REC] druid/balance. the presence of debuffs on the target is ignored

### ISSUE THREAD

**Issue by n-r-w** [Hekili/hekili#2601] opened 2023-05-14 08:29 UTC
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

The presence of Moonfire and Sunfire debuffs on the target is ignored. The addon constantly offers to apply them again.

### How to Reproduce

Follow the recommendations of the addon. At some point, he will offer to apply debuffs despite the fact that they have more than 15-20 seconds left.
In the attached snapshot, the addon suggests using Sunfire, despite the fact that it already exists on the target.

### Snapshot (Link)

https://pastebin.com/MY4U5XJQ

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/utT3Tbhb4AAaVxiCxpua1D

### Additional Information

A similar problem with Moonfire recommendation: https://pastebin.com/NtZFXhqx

### Contact Information

RomanN#2950

**Comment by n-r-w** [comment] 2023-05-14 09:29
I returned to v10.1.0-1.0.0j and everything started working correctly.

**Comment by cameronstubber** [comment] 2023-05-14 15:09
Had the exact same issue tonight with Feral Druid.

Main noticeable issues:
- Recommending Prowl while in combat and unable to use it
- Not recognizing DoTs already applied to targets and asking to apply it again early when already ticking (Rake, Thrash etc)
- Recommending Ferocious Bite to be cast with only 1 CP
- Not recommending Night Elf Shadowmeld for extra stealth damage when enabled in the addon options.

Just tried now with 10.1.0-1.0.0j and everything seems to be working fine apart from Shadowmeld.

**Comment by Hekili** [comment] 2023-05-14 16:00
Duplicate of #2600; resolved in `v10.1.0-1.0.0l`.

**Comment by Hekili** [comment] 2023-05-14 16:00
#

**Closed as completed by Hekili** 2023-05-14 16:00 UTC
Labels: 📈 recommendations, 🧑‍⚕️ triage
