### ISSUE TITLE
[Feral]  Circle of Life and Death Legendary causes Hekili to recommend Rip over Primal Wrath in multi-target

### ISSUE THREAD

**Issue by groooooooooooot** [Hekili/hekili#971] opened 2021-03-12 18:20 UTC
Using latest build for Hekili.

Feral specc'd: 2-3-1-2-1-3-2

With the Circle of Life and Death legendary equipped Hekili is consistently recommending Rip over Primal Wrath when 3+ targets are engaged.  This is consistent at Target dummies or with real mobs.  When the Circle of Life and Death legendary is removed or replaced, Primal Wrath is consistently recommended as expected.

**To reproduce**

Spec Primal Wrath
Equip Circle of Life and Death legendary
Go to target dummies
Attack target dummies.
Build 5 combo points
Hekili recommends Rip instead of Primal Wrath.
Repeat building 5 combo points.
Hekili variably recommends Ferocious Bite or Rip but not Primal Wrath
Unequip Circle of Life and Death legendary
Attack target dummies.
Build 5 combo points
Hekili recommends Primal Wrath as expected.

**Expected Behavior**

Hekili should recommend Primal Wrath over Rip when there are multiple targets in range

**Screenshot**

https://imgur.com/PNoEC9k

**Issue Reporting Tab**

build: v9.0.5-1.0
level: 60 (60)
class: DRUID
spec: feral

talents: balance_affinity
    bloodtalons
    mass_entanglement
    primal_wrath
    sabertooth
    soul_of_the_forest
    wild_charge

pvptalents: none

covenant: night_fae

conduits: conflux_of_elements = 5
   front_of_the_pack = 5
   taste_for_blood = 5
   wellhoned_instincts = 5

soulbinds: [niya]
   grove_invigoration = 1
   natures_splendor = 1
   niyas_tools_poison = 1
   run_without_tiring = 1

sets: sinful_gladiators_badge_of_ferocity = 1

gear: chalice_nobles_signet = 1
    chiropteran_leggings = 1
    corpsehide_belt = 1
    freshly_embalmed_jerkin = 1
    gargontamers_spear = 1
    inscrutable_quantum_device = 1
    mantle_of_manifest_sins = 1
    nobles_birthstone_pendant = 1
    oakheart_anklewraps = 1
    ring_of_perpetual_conflict = 1
    rocket_chicken_handlers = 1
    sinful_gladiators_badge_of_ferocity = 1
    soulstalker_bindings = 1
    umbrahide_helm = 1
    wicked_flankers_gorget = 1

legendaries: circle_of_life_and_death = 1

itemIDs: 172317, 175921, 178744, 178872, 179336, 179350, 179527, 179766, 181187, 181218, 181678, 182993, 183029, 183033, 183039

settings: aoe = 2
    buffPadding = 0
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = false
    cycle_min = 6
    damage = true
    damageDots = false
    damageExpiration = 3
    damagePets = false
    damageRange = 0
    debuffPadding = 0
    enabled = true
    enhancedRecheck = false
    gcdSync = true
    maxRefresh = 10
    maxTime = 33
    nameplateRange = 50
    nameplates = true
    package = Feral
    petbased = false
    potion = spectral_agility
    potionsReset = 20180919.1
    throttleRefresh = false
    throttleTime = false
    brutal_charges = 2
    owlweave_cat = false

toggles: cooldowns = true
    custom1 = false
    custom2 = false
    defensives = true
    essences = true
    interrupts = true
    mode = automatic
    potions = false

**Snapshot**

https://pastebin.com/gzqDsDUs

**Comment by Hekili** [comment] 2021-03-12 19:03
Fill out the ticket completely, please.

**BEFORE SUBMITTING AN ISSUE:**

1.  Check to see if you are using the latest version of the addon.  If there is a newer alpha/beta/release version, see if your problem exists with the new version.

2.  Check to see if someone else has already opened an issue report here.  Please don't submit repeat reports.

**Describe the Bug/Issue**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
- Go to '...'
- Click on '....'
- Scroll down to '....'
- See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**WHEN SUBMITTING AN ISSUE:**

Please provide the following information.  Leaving it out may result in your ticket being ignored (because I won't have the information needed to explore your report).

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here.

**PUT ISSUE REPORT LINK HERE:**

2.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot.  This is not a screenshot.  A snapshot can be generated by binding the Pause feature on the Toggles tab.  When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab.  Copy and paste this to pastebin.com and provide the link here.
 
**PUT SNAPSHOT LINK HERE:**

3.  If reporting an error (i.e., the addon freezes and/or disables itself), please install the BugSack and BugGrabber addons as they will enable you to paste the exact error message, with detail that will help me identify where the code error is located.  You can paste the error information here or use pastebin.com for that as well.

**PUT ERROR MESSAGE(S) HERE:**

**Comment by groooooooooooot** [comment] 2021-03-12 20:48
updated original post

**Comment by Hekili** [comment] 2021-03-15 03:27
This may be resolved in v9.0.5-1.0.1-beta4, but I'm not sure yet.

**Comment by p4nchez** [comment] 2021-03-15 11:56
sometimes i had the same error that i get rip recommended in aoe situations even on dummy like grooooooooooot with circle

testet few minutes with beta4 
seems fixed.. no miss recommended rip

thx <3

**Comment by Hekili** [comment] 2021-04-03 14:32
Thanks!

**Closed as completed by Hekili** 2021-04-03 14:32 UTC
Labels: 🐛 Bug
