### ISSUE TITLE
Trinket is not showing as part of priority

### ISSUE THREAD

**Issue by Envidiosa** [Hekili/hekili#1588] opened 2022-08-19 18:17 UTC
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

I have imported a priority scheme from Simulation Craft - I can't seem to get the Enforcer's Stun Grenade to show up as part of the rotation.  I replaced the Stun grenade with the first sigil and the sigil did appear as part of the recommended rotation.  This seems to be just affecting the Enforcer's Stun Grenade.

### How to Reproduce

1. Load priority for frost dk
2. Attack training dummy
3. Recommended rotation is suggested but does not include Enforcer's Stun Grenade

### Snapshot (Link)

https://pastebin.com/fUwQphei

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/oTTM6ccvAUty97DkP44NVT

### Contact Information

Ennvee#5697

**Comment by Hekili** [comment] 2022-08-19 18:23
Duplicate of #1586.  I'll be adding it soon.

**Closed as completed by Hekili** 2022-08-19 18:23 UTC
Labels: 📈 recommendations, 🧑‍⚕️ triage
