### ISSUE TITLE
[REC] REPLACE THIS TEXT WITH YOUR CLASS/SPEC AND BRIEF ISSUE DETAILS

### ISSUE THREAD

**Issue by UltiDeeps** [Hekili/hekili#1300] opened 2021-12-02 03:47 UTC
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Fire Rotation disappearing at points in the rotation.  Also seems to not be recommend fire blast even during combust.  Only snapshot auto generated is for AOE for some reason when I'm referencing ST.

### How to Reproduce

Just follow display of add on as is.  More common during initial Combust windows

### Snapshot (Link)

https://pastebin.com/1qjgrDwt

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/iTPz5dCF76tsC12vVKztfx

### Contact Information

Ulti#3784

**Comment by UltiDeeps** [comment] 2021-12-02 03:48
Manually added ST Snapshot for reference can replicate aoe if necessary.

**Comment by Hekili** [comment] 2021-12-02 03:52
The snapshot has to be taken when the problem is occurring, or it is useless. Please update the ticket title and add a snapshot of the problem occurring. Keep in mind, you're using an alpha testing release (already one version behind), so I appreciate the report but you'll need to update again to confirm whether you're having the issue or not.

**Comment by Hekili** [comment] 2021-12-02 04:06
> Fire Rotation disappearing at points in the rotation. 

So, by default, if the addon fails to generate all its recommendations, it will automatically take a snapshot.  I'd need that snapshot, which will show where and why it failed to generate a recommendation.

> Also seems to not be recommend fire blast even during combust. 

I'll need a snapshot that's taken when this is happening.

> Only snapshot auto generated is for AOE for some reason when I'm referencing ST.

That's odd, but may be an issue with -alpha6 that may be fixed in alpha7.  Let me know.

There's no need to have your display show the next 10 actions, especially for a volatile, crit-sensitive spec like Fire.

**Comment by UltiDeeps** [comment] 2021-12-02 04:09
I completely forgot what you were capable of seeing haha.  I switched my
release type and thought curse would auto download the previous install
again but I realize now it didn't.  Going back to live fixed my issue.  The
10 icons was more so to see if Fire Blast was initially suggested and
changed based off something I was doing incorrectly or not.

**Comment by Hekili** [comment] 2021-12-02 04:25
K, I have fixed the Fire Blast part, but if you end up testing the latest alpha (-alpha8, at time of posting) and the addon doesn't give recommendations, those snapshots would be useful info.

**Closed as completed by Hekili** 2021-12-02 04:25 UTC
Labels: 📈 recommendations, 🧑‍⚕️ triage
