### ISSUE TITLE
[REC] Enh: Thorim's Invocation can delay Ascendance with changes in # of targets

### ISSUE THREAD

**Issue by geraint425** [Hekili/hekili#3955] opened 2024-10-11 18:03 UTC
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Shaman - Enhancement

### Describe the Issue

I already wrote to you earlier. https://github.com/Hekili/hekili/issues/3912 I opened a new ticket since you closed that one. I added a new message there, but you didn't see it. I decided to duplicate it again with a screenshot and a new Snapshot. You can try in the city on manikins to do it. You need to first start a fight with 5 manikins and AOE, then stop and stand next to them, then go switch to 1 target, and start following the recommendations of the addon and it will recommend in AOE opener and rotation on 1 target. But I'll tell you right away it is not to repeat the first time sometimes you need 3-6 attempts at me so it worked out in the city. And on the boss ovinax enough to do every time opener and after doing Vipe and with a few attempts you will definitely get opener in AOE with 1 target when there will be only 1 boss.

### How to Reproduce

For the city:
1. Start combat with 5 dummies.
2. stop rotation.
3. Approach another dummy that is 1 standing.
4. Start following the recommendations.
5. If there is a ST opener, repeat the steps from step 1.
For the boss ovinax:
1. Start a fight with the boss
2. After the opener, go and do Vipe on the boss.
3. Repeat from 6 point, until there are no AOE recommendations on the boss.

### Snapshot (Link)

https://pastebin.com/WpeuQZ26

### Additional Information

https://imgur.com/a/2kn8Fjg

**Comment by syrifgit** [comment] 2024-10-11 18:18
You are multiple versions behind, update your addon first then you can resubmit the ticket if the issue is still happening.

`build: v11.0.2-1.0.19`

![image](https://github.com/user-attachments/assets/6451ba80-c475-4d01-a9df-75303afc45b6)

**Comment by geraint425** [comment] 2024-10-13 05:22
The problem persists. I've already updated, I've been testing the same thing for a long time and it still keeps repeating. We've already made 100+ attempts on bos and for all these times the problem kept repeating and repeating. Only helped if you do /relog after every vipe of the boss. I just don't know how else to explain that opener while boss 1 is not recommended as ST to do the sequence Pwave->Wolves->Ascendance. 

I'm attaching the picture and screenshot again that the error is repeating. I'm just like I wrote above. Went first to 5 dummies, made opener in AOE. Then when Ascendance was over I went to a single dummy standing next to him without attacking him just stood there and waited for Ascendance to be ready. As soon as it was ready, I started to follow the addon recommendations, and the addon recommended rotation as in AOE. Here is a screenshot and Snapshot.  https://pastebin.com/UTe5BhHS https://imgur.com/a/uMgpgNY

**Comment by syrifgit** [comment] 2024-10-13 06:03
This is not an AoE rotation ... I think you just don't understand the rotation. I would recommend checking out the class guides: https://www.icy-veins.com/wow/enhancement-shaman-pve-dps-rotation-cooldowns-abilities

All 3 things it chose in your snapshot were from the single target list. Non issue, closing ticket. If you can get a snapshot where the issue is actually happening, you can open a new ticket. You can review the snapshot instructions in-game or on the wiki. You need to press it when the issue is actually happen on your screen and the addon is showing the wrong thing.

```
        45.  elemental_blast ( single - 14 )
        The action (elemental_blast) is usable at (0.00 + 0.01) with cost of 15000 mana (have 2500000).
         - the action is ready before the current recommendation (at +0.01 vs. +10.00).
        List ( single ) called from ( Enhancement:default:21 ) would PASS at 0.01.
        active_enemies[1.00] = 1
         - this entry's criteria PASSES: buff.maelstrom_weapon.stack[7.00] >= 7 & feral_spirit.active[3.00] >= 1 & ( buff.icy_edge.stack[1.00] + buff.molten_weapon.stack[0.00] >= 1 ) & charges_fractional[2.00] >= 1.8 & cooldown.feral_spirit.remains[79.35] >= 3
        Action chosen:  elemental_blast at 0.01!
```

```
        59.  stormstrike ( single - 28 )
        The action (stormstrike) is usable at (0.01 + 1.16) with cost of 50000 mana (have 2500000).
         - the action is ready before the current recommendation (at +1.16 vs. +10.00).
        List ( single ) called from ( Enhancement:default:21 ) would PASS at 1.16.
        active_enemies[1.00] = 1
         - this entry's criteria PASSES: talent.elemental_spirits.enabled[true] & ( buff.doom_winds.up[false] | talent.deeply_rooted_elements.enabled[false] | talent.ascendance.enabled[true] | ( talent.stormblast.enabled[false] & buff.stormbringer.up[true] ) )
        Action chosen:  stormstrike at 1.16!
```

```
 71.  lava_lash ( single - 40 )
        The action (lava_lash) is usable at (1.54 + 0.78) with cost of 20000 mana (have 2479629).
         - the action is ready before the current recommendation (at +0.78 vs. +10.00).
        List ( single ) called from ( Enhancement:default:21 ) would PASS at 0.78.
        active_enemies[1.00] = 1
         - this entry's criteria PASSES: talent.elemental_assault.enabled[true] & talent.tempest.enabled[true] & talent.molten_assault.enabled[true] & dot.flame_shock.ticking[true]
        Action chosen:  lava_lash at 0.78!
```

**Comment by geraint425** [comment] 2024-10-13 06:34
![image](https://github.com/user-attachments/assets/f94b3d4b-117b-412b-87dc-77f0e5f55fe6)
It's not an opener. You yourself just indicated to look at it. Well, here's a screenshot of how it should be. I didn't. The fight was reset and I got 5 targets too far away. Like I said Pwave->Wolves->Ascendance.

**Comment by syrifgit** [comment] 2024-10-13 06:36
Then you need to provide a snapshot of THAT being wrong not mid combat while all those buttons are on cooldown.

You need to make the snapshot when the issue is happening on your screen, not 10 seconds later.

**Comment by geraint425** [comment] 2024-10-13 06:51
It's not 10 seconds later. Have you tried my actions described above on the shaman? I'll say it again. I start a fight with dummies where there are 5 of them in the city. I made an opener to Ascendance. And I go far away from them to another dummy who is 1 standing. I wait for the fight to reset. After waiting when all abilities including Ascendance are ready and I start the fight again but with 1 target and I reach the recommendation when Ascendance and press snapshot. What else do I need to do ? I do not understand just I have already described my actions and described how you need to repeat yourself to make sure, and snapshots threw a bunch of snapshots already. Here's another one of the same thing. https://pastebin.com/DQCyhCVF 

Here's a screenshot of https://imgur.com/a/z7CPcov I don't see the opener listed on the site. I have already specially made a screenshot of what happens when I do those actions. Here is just a Snapshot of the idle time before the fight starts. https://pastebin.com/6bs4U3wi

**Comment by syrifgit** [comment] 2024-10-13 12:37
Now that you've explained more, it's because of your thorims invocation talent. Because you were fighting in AoE, your Thorims talent is set to Chain Lightning. This is affecting the logic for ascendance because you don't want to use a chain lightning TI in single target. 

This is expected behaviour. This is also why it doesn't happen every time. Sometimes you may have ended the fight with lightning bolt as the last spell instead of chain lightning.

Casting lightning bolt would probably fix it. I imagine reloading/relogging fixes it because it wipes the variable in the addon?

`ti_chain_lightning[true] & active_enemies[1.00] > 1`


Maybe some sort of override for TI is appropriate for this situation? @Hekili 

Allow ascendance regardless of TI state if `raid & boss`


```
actions+=/ascendance,if=dot.flame_shock.ticking&((ti_lightning_bolt&active_enemies=1&raid_event.adds.in>=action.ascendance.cooldown%2)|(ti_chain_lightning&active_enemies>1))
```

To
```
actions+=/ascendance,if=dot.flame_shock.ticking&((ti_lightning_bolt&active_enemies=1&raid_event.adds.in>=action.ascendance.cooldown%2)|(ti_chain_lightning&active_enemies>1)|raid&boss&active_enemies=1)
```

**Comment by Hekili** [comment] 2024-10-16 01:20
This is correct, I suspect that you could encounter this issue in a HecticAddCleave simulation if Ascendance comes off CD soon after the adds expire.

I'll take a look with some comparison sims. There's likely a point at which delaying Ascendance by X seconds costs more DPS than (eventually) firing off a Lightning Bolt before popping Ascendance.

**Comment by Hekili** [comment] 2024-10-16 01:25
I feel obligated to note: @geraint425, you've submitted enough tickets by now that you know the snapshots are required and when to take them. Please be considerate of devs' time and don't make us ask you multiple times for required info. Thanks.

**Comment by Hekili** [comment] 2024-10-17 22:01
I have run some sims and found a small DPS improvement by forcing LB/CL as Ascendance comes off cooldown in Hectic Add Cleave scenarios.  This will be in the next release.

```diff
 actions+=/surging_totem
+actions+=/lightning_bolt,if=talent.thorims_invocation&!ti_lightning_bolt&buff.maelstrom_weapon.stack>4&cooldown.ascendance.remains<2*gcd.max&active_enemies=1
+actions+=/chain_lightning,if=talent.thorims_invocation&!ti_chain_lightning&buff.maelstrom_weapon.stack>4&cooldown.ascendance.remains<2*gcd.max&active_enemies>1
 actions+=/ascendance,if=dot.flame_shock.ticking&((ti_lightning_bolt&active_enemies=1&raid_event.adds.in>=action.ascendance.cooldown%2)|(ti_chain_lightning&active_enemies>1))
```

In sims, this saves about ~6.5 sec of wasted Ascendance CD in Hectic Add Cleave.

**Closed as completed by Hekili** 2024-10-17 22:01 UTC
Labels: 📈 recommendations
