### ISSUE TITLE
Balance Druid, Incarnation over Celestial Alignment being issued even with Incarnation not taken as talent.

### ISSUE THREAD

**Issue by Bdrood** [Hekili/hekili#1937] opened 2022-11-14 03:11 UTC
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

For my balance druid, it is telling me to cast Incarnation Chosen of Elune instead of Celestial Alignment even though Incarnation is not a talent I have selected for this build.  Celestial Alignment is never shown to cast even with Incarnation disabled in the add on menu.  In the Balance talent tree, its either Convoke or Incarn.  I have convoke selected.  Addon does still have me cast convoke.  Also noticed in the build loadout code in add on, shows Incarnation=1/1. 

### How to Reproduce

Enter game as Balance druid
Have Convoke the Spirits selected as a talent instead of Incarnation Chosen of Elune
Enter moonkin form
Begin cast rotation with dots as normal
Incarnation will pop to cast on Hekili bar 

### Talent Loadout

build: v10.0.0-10.3 level: 60 (60) class: DRUID spec: balance  talents: astral_communion     astral_influence = 2/2     balance_of_all_things = 1/2     celestial_alignment = 1/1     convoke_the_spirits = 1/1     eclipse = 1/1     elunes_guidance = 1/1     frenzied_regeneration = 1/1     fury_of_elune = 1/1     improved_barkskin = 1/1     improved_sunfire = 1/1     incarnation = 1/1     incarnation_chosen_of_elune = 1/1     innervate = 1/1     ironfur = 1/1     lunar_shrapnel = 1/1     lycaras_teachings = 3/3     mass_entanglement = 1/1     matted_fur = 1/1     moonkin_form = 1/1     natures_balance = 1/1     natures_vigil = 1/1     new_moon = 1/1     nurturing_instinct = 3/3     orbit_breaker = 1/1     power_of_goldrinn = 1/1     primordial_arcanic_pulsar = 1/1     rattle_the_stars = 1/1     shooting_stars = 1/1     solstice = 2/2     soothe = 1/1     soul_of_the_forest = 1/1     stampeding_roar = 1/1     starfall = 1/1     starfire = 1/1     starlord = 2/2     starsurge = 1/1     starweaver = 1/1     stellar_flare = 1/1     sunfire = 1/1     swipe = 1/1     syzygy = 1/1     thick_hide = 2/2     thrash = 1/1     tiger_dash = 1/1     twin_moons = 1/1     typhoon = 1/1     umbral_embrace = 1/2     ursols_vortex = 1/1     waning_twilight = 2/2     wild_charge = 1/1  pvptalents: malornes_swiftness    moonkin_aura    star_burst  covenant: none  conduits: none  soulbinds: [niya]  sets: ring_of_collapsing_futures = 1     shadowed_orb_of_torment = 1  gear: antumbra_shadow_of_the_cosmos = 1     bracers_of_the_fixed_stars = 1     cabalists_hymnal = 1     chestguard_of_the_fixed_stars = 1     choker_of_barbed_reins = 1     footwraps_of_the_fixed_stars = 1     handwraps_of_the_fixed_stars = 1     headpiece_of_the_fixed_stars = 1     lavender_mageweave_shirt = 1     leggings_of_the_fixed_stars = 1     lyre_of_decadent_frivolity = 1     renowned_guild_tabard = 1     ring_of_collapsing_futures = 1     shadowed_orb_of_torment = 1     shadowghast_ring = 1     shoulderpads_of_the_fixed_stars = 1     umbrahide_waistguard = 1     wrap_of_the_fixed_stars = 1  legendaries: none  itemIDs: 10054, 142173, 142174, 172320, 178926, 179566, 184028, 186428, 188847, 188848, 188849, 188850, 188851, 188853, 188854, 188871, 189852, 69210  settings: aoe = 3     buffPadding = 0     combatRefresh = 0.1     custom1Name = Custom 1     custom2Name = Custom 2     cycle = false     cycle_min = 6     damage = true     damageDots = true     damageExpiration = 6     damageOnScreen = true     damagePets = false     damageRange = 0     debuffPadding = 0     enabled = true     enhancedRecheck = true     gcdSync = true     maxTime = 10     nameplateRange = 8     nameplates = false     noFeignedCooldown = false     package = Balance     petbased = false     potion = spectral_intellect     potionsReset = 20180919.1     regularRefresh = 0.5     throttleRefresh = false     throttleTime = false     delay_berserking = false     starlord_cancel = false  toggles: cooldowns = true      custom1 = false      custom2 = false      defensives = true      essences = true [overridden]     interrupts = true      mode = automatic      potions = false   keybinds:      barkskin                = M3  [07], M3  [09], -   [10]     convoke_the_spirits     = M3  [10]     dash                    = 8   [07]     ferocious_bite          = 4   [07]     frenzied_regeneration   = 7   [09]     full_moon               = 8   [10]     growl                   = 4   [09]     half_moon               = 8   [10]     innervate               = -   [09]     ironfur                 = 9   [09]     mangle                  = 2   [09]     moonfire                = 2   [01], 2   [10]     new_moon                = 8   [10]     prowl                   = R   [07]     regrowth                = 2   [08], M4  [09]     rejuvenation            = 0   [09]     shadowed_orb_of_torment = 7   [10]     shred                   = 2   [07]     soothe                  = 1   [01]     stampeding_roar         = 7   [07], 8   [09]     starfire                = 8   [01], 4   [10]     starsurge               = R   [01], 1   [10]     sunfire                 = M4  [01], R   [10]     thrash                  = 3   [07]     thrash_bear             = 3   [07]     thrash_cat              = 3   [07]     typhoon                 = M4  [10]     ursols_vortex           = 0   [10]     wild_charge             = 1   [07], 1   [09]     wrath                   = 3   [10]  warnings: [#1] Unknown buff in [Balance:st:27]: moonkin_aura [string "@Interface/AddOns/Hekili/State.lua"]:3812: in function <Interface/AddOns/Hekili/State.lua:3803> [string "@Interface/AddOns/Hekili/State.lua"]:965: in function `addStack' [string "@Interface/AddOns/Hekili/Dragonflight/DruidBalance.lua"]:2519: in function `handler' [string "@Interface/AddOns/Hekili/State.lua"]:6051: in function `RunHandler' [string "@Interface/AddOns/Hekili/Core.lua"]:1970: in function <Interface/AddOns/Hekili/Core.lua:1483>

### Snapshot

https://pastebin.com/kHhkHewY

**Comment by Hekili** [comment] 2022-11-14 03:40
Hi, please provide your talent string.

**Comment by Bdrood** [comment] 2022-11-14 03:47
BYGAGX1kx6Mci9Zl2t+S+sRoPCAAAAAAAAAAAAAAAAAAAoAQSiIQChkEkIgWCJJhWCiDkDAFplIESBgA

**Comment by funappear** [comment] 2022-11-14 06:58
I am also having the same problem.
When testing for each version, it was confirmed that a problem occurred when updating from v10.0.0-10.2 to v10.0.0-10.3.

Problem caused by changing the code below,
Dragonflight/Classes.lua
30 -            talent.rank = data[2] > 0 and IsPlayerSpell( data[2] ) and node.activeRank or 0
30 +           talent.rank = data[2] > 0 and node.activeRank or 0

**Comment by Hekili** [comment] 2022-11-14 15:33
Yes, choice nodes were bugged -- that previous code could not differentiate Drain Soul being talented, unfortunately.

This should be resolved in the latest releases (11.1 and later).

**Closed as completed by Hekili** 2022-11-14 15:33 UTC
Labels: 📈 recommendations, 🧑‍⚕️ triage
