### ISSUE TITLE
Fire Mage priorities not following the supposed order (as in not using Phoenix Flames with Alexstrasza's Fury, not recommending Shifting Power as often as it should, and prioritizing Scorch over Fireball)

### ISSUE THREAD

**Issue by tioeduardo27** [Hekili/hekili#3068] opened 2023-12-14 19:54 UTC
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

I am still learning Fire Mage and have been watching guides, comparing logs and talking to people on Mage discord. So I'd take this with a grain of salt, but:

I have been trying to reproduce my Fire Mage simulation rotation and follow the guides and even though I know Fire is a very reactive spec and that many calculations are needed to react to those, I feel some things are weird:

- Overrecommending of Scorch instead of Fireball outside Combustion
- Underrecommending of Fireball instead of Fire Blast>Pyroblast outside Combustion
- Phoenix Flames not being expended completely and being underutilized when Alexstrasza's Fury talent is taken
- Shifting Power not being recommended consistently (this I think is a big issue because it sometimes takes longer than it's CD to be recommended and it stays available for the longest part of pulls)
- Sometimes if you crit a Dragon's Breath (then you get a Heating Up) and you cast a Fire Blast to get a Hot Streak, the addon breaks and locks into recommeding DB (been able to reproduce 2x only)

### How to Reproduce

Just basically log in a character and do the rotation recommended and this will become clear, especially the low Shifting Power and Phoenix Flames usage.

### Snapshot (Link)

https://pastebin.com/L1d4AwpQ

### Raidbots Sim Report (Link)

 https://www.raidbots.com/simbot/report/wVAC46emqW7UAvDEUqR7bB

### Contact Information

tioeduardo27

**Comment by syrifgit** [comment] 2023-12-14 20:31
**Class guide: https://www.icy-veins.com/wow/fire-mage-pve-dps-rotation-cooldowns-abilities**

First, remember that you are not wearing any tier gear and your ilevel is pretty low.

I have a suspicion a lot of this may be cause by the shifting power issue on point 5, which will hopefully be fixed with the fire blast trick we talked about on discord.

1) I noticed you said in Discord that its telling you to combust without full charges of Phoneix Flames. You have the Alexstrasza's Fury talent selected, and the guide clearly states you do not cast Phoenix Flames inside combustion. So that one is correct, you probably don't want to have full charges going into it.

**Source: During Combustion, this will be [Fire Blast](https://www.wowhead.com/spell=319836) Icon Fire Blast, Scorch Icon Scorch (or [Fireball](https://www.wowhead.com/spell=133) Icon Fireball with very high haste) and Phoenix Flames Icon Phoenix Flames (unless you have talented [Alexstrasza's Fury](https://www.wowhead.com/spell=235870) Icon Alexstrasza's Fury, in which case you only use Phoenix Flames outside of Combustion).**

2) Phoenix Flames not being expended completely and being underutilized when Alexstrasza's Fury talent is taken
Additionally, as for not casting it as filler outside of combustion, the spec guide also says that you cast it when your buff is running out and you dont have hot streak. So you aren't dumping it on CD when you use this talent. Are you confident it's being "underutilized"? This is the only condition to cast phoenix flames with your build

**Cast [Phoenix Flames](https://www.wowhead.com/spell=257541) Icon Phoenix Flames whenever [Feel the Burn](https://www.wowhead.com/spell=383391) Icon Feel the Burn is close to running out, and you do not have [Hot Streak](https://www.wowhead.com/spell=195283) Icon Hot Streak.**

3) Overrecommending of Scorch instead of Fireball outside Combustion
Fireball is your 12th lowest priority, out of 13 lines in the rotation. Scorch has 2 conditions that make you cast it before fireball. Are you 100% confident its not this causing it? Read the Scorch talents.

4) Sometimes if you crit a Dragon's Breath (then you get a Heating Up) and you cast a Fire Blast to get a Hot Streak, the addon breaks and locks into recommeding DB (been able to reproduce 2x only)
Is it telling you to dragons breath when it's on CD and not available? That would be a big issue.

5) Shifting Power not being recommended consistently (this I think is a big issue because it sometimes takes longer than it's CD to be recommended and it stays available for the longest part of pulls)
This sounds like an issue, but the condition says you need to NOT have 3 charges of fire blast before using it. Are you sure you have used the charges?

**Closed as not planned** 2023-12-18 19:22 UTC
Labels: 📈 recommendations, 🧑‍⚕️ triage
