### ISSUE TITLE
[REC] DK/FROST : Only howling blast during BOS

### ISSUE THREAD

**Issue by JGBG78** [Hekili/hekili#1770] opened 2022-10-28 16:44 UTC
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

With my frost dk, when i use Breath of sindragosa, hekili tell me to only use howling blast even without rime proc even with killing machine proc even with 2+ runes

### How to Reproduce

1 playing a frost dk
2 use Remorseless Winter + 2 x death's due (to get 60+ runic power)
3 use all cd (frost pillar+raise dead+empower rune weapon+breath of sindragosa)

### Snapshot (Link)

https://pastebin.com/E8UT8yjD

### Contact Information

Kòre#7550

**Comment by Joshywa89** [comment] 2022-10-29 01:28
having the same exact issue just basically telling me to spam howling blast.

**Comment by Hekili** [comment] 2022-10-30 04:07
This should be resolved in 05 (posting in a bit).  Comment and let me know if it persists after updating.  If it does, provide a new snapshot when the issue is occurring, and include your talent string.  Thanks!

**Closed as completed by Hekili** 2022-10-30 04:07 UTC
Labels: 📈 recommendations, 🧑‍⚕️ triage

**Comment by JGBG78** [comment] 2022-10-30 09:57
Yeah it seems fixed, but now addon doesnt recommand Breath of sindragosa anymore

**Comment by Joshywa89** [comment] 2022-10-30 10:04
Im at work atm but it's not recommending ghoul or Death and Decay when more then 1 target

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Hekili** [comment] 2022-10-30 11:29
> Comment and let me know if it persists after updating. If it does, provide a new snapshot when the issue is occurring, and include your talent string.

**Comment by Joshywa89** [comment] 2022-10-30 14:50
build: v10.0.0-05
level: 60 (60)
class: DEATHKNIGHT
spec: frost

talents: acclimation
    antimagic_barrier = 1/1
    antimagic_shell = 1/1
    antimagic_zone = 1/1
    biting_cold = 1/1
    breath_of_sindragosa = 1/1
    brittle = 1/1
    chains_of_ice = 1/1
    cleaving_strikes = 1/1
    death_strike = 1/1
    deaths_echo = 1/1
    empower_rune_weapon = 1/1
    enduring_strength = 2/2
    enfeeble = 1/1
    frigid_executioner = 1/1
    frost_strike = 1/1
    frostreaper = 1/1
    gathering_storm = 1/1
    gloom_ward = 1/1
    howling_blast = 1/1
    icebound_fortitude = 1/1
    icebreaker = 2/2
    icecap = 1/1
    icy_talons = 2/2
    improved_obliterate = 1/1
    improved_rime = 1/1
    insidious_chill = 1/1
    invigorating_freeze = 2/2
    killing_machine = 1/1
    merciless_strikes = 1/1
    might_of_thassarian = 1/1
    mind_freeze = 1/1
    murderous_efficiency = 1/1
    obliterate = 1/1
    permafrost = 1/1
    pillar_of_frost = 1/1
    raise_dead = 1/1
    remorseless_winter = 1/1
    rime = 1/1
    runic_attenuation = 1/1
    runic_command = 2/2
    unholy_bond = 1/2
    unholy_endurance = 1/1
    unholy_ground = 1/1
    unleashed_frenzy = 1/1
    veteran_of_the_third_war = 2/2

pvptalents: none

covenant: night_fae

conduits: accelerated_cold = 13
   condensed_anima_sphere = 13
   everfrost = 13
   fleeting_wind = 13
   hardened_bones = 13
   spirit_drain = 13

soulbinds: [korayn]
   first_strike = 1
   get_in_formation = 1
   horn_of_the_wild_hunt = 1
   hunts_exhilaration = 1
   wild_hunt_strategem = 1
   wild_hunt_tactics = 1

sets: inscrutable_quantum_device = 1
    tier28 = 3

gear: carapace_of_the_first_eidolon = 1
    chausses_of_the_first_eidolon = 1
    gauntlets_of_the_first_eidolon = 1
    girdle_of_the_first_eidolon = 1
    gorestained_cleaver = 1
    inscrutable_quantum_device = 1
    most_regal_signet_of_sire_denathrius = 1
    old_warriors_soul = 1
    origin = 1
    plague_handlers_greathelm = 1
    precious_ribbon = 1
    ring_of_perpetual_conflict = 1
    shadowghast_armguards = 1
    shadowghast_sabatons = 1
    sinsmasher = 1
    spires_of_broken_hope = 1
    tabard_of_the_lightbringer = 1
    tier28 = 3
    worldkiller_iris = 1

legendaries: rage_of_the_frozen_champion = 1
    rampant_transference = 1

itemIDs: 171413, 171419, 178773, 178855, 178863, 178872, 179350, 183036, 186349, 186438, 188863, 188864, 188866, 188870, 189859, 190334, 52019, 52252

settings: aoe = 2
    buffPadding = 0
    combatRefresh = 0.1
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = true
    cycle_min = 6
    damage = true
    damageDots = false
    damageExpiration = 8
    damageOnScreen = true
    damagePets = false
    damageRange = 0
    debuffPadding = 0
    enabled = true
    enhancedRecheck = true
    gcdSync = true
    maxTime = 10
    nameplateRange = 8
    nameplates = true
    noFeignedCooldown = false
    package = Frost DK
    petbased = false
    potion = potion_of_spectral_strength
    regularRefresh = 0.5
    throttleRefresh = true
    throttleTime = false
    bos_rp = 50

toggles: cooldowns = true
    custom1 = false
    custom2 = false
    defensives = false
    essences = true [overridden]
    interrupts = true
    mode = automatic
    potions = false

keybinds:
    arcane_torrent      = =   [01]
    death_grip          = 1   [02]
    death_strike        = 7   [01]
    empower_rune_weapon = 6   [01]
    frost_strike        = 3   [01], 7   [02]
    howling_blast       = 4   [01], 3   [02]
    mind_freeze         = 1   [01]
    obliterate          = 2   [01], 5   [02]
    remorseless_winter  = 5   [01]

warnings: none





thats my character data


BsPAdLUHklrTr3hBIcYWdbnCGnIAIhkwBiIREikECIJRSQAiIIRSSSSKBAAAAAAAAAAAAA

thats my Talents.


seems to no longer want to recommend ghoul summon on pull/close to start of fight, and never tells me to use Death and Decay when there is 2 or more targets for obliteration cleave while standing in Death and Decay, seems to register properly when using the Night Fae version of DnD but not the actual DnD when not in Shadowlands
________________________________

**Comment by Joshywa89** [comment] 2022-10-30 14:53
also feel its asking for empower rune weapon to early into burst window
________________________________
