### ISSUE TITLE
[REC] BALANCE DRUID, PROCS AND DOTS

### ISSUE THREAD

**Issue by Silvkai** [Hekili/hekili#2602] opened 2023-05-14 09:06 UTC
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

The presence of Moonfire and Sunfire debuffs on the target is ignored. The addon constantly offers to apply them again. (As per previous submission by another user).

With Starweaver talent also, recommending both starfall and starsurge with not enough astral power to use, also more starsurge while in AoE, Starweaver proc's a "free" starsurge of starfall but this isnt proc related.

### How to Reproduce

1. Enter Game as Balance Druid.
2. Hit training dummy or targets
3. Dot up as normal, start burst. 
4. Addon recommneds dotting again while still active and long uptime and to use starsurge/fall with not enough Astral Power.

### Snapshot (Link)

https://pastebin.com/mVAz1thv

**Comment by n-r-w** [comment] 2023-05-14 09:11
Same issue https://github.com/Hekili/hekili/issues/2601

**Comment by Hekili** [comment] 2023-05-14 18:00
Duplicate of #2600; this is largely resolved with `1.0.0l` and has an additional fix coming in `1.0.1`.

**Closed as completed by Hekili** 2023-05-14 18:00 UTC
Labels: 📈 recommendations, 🧑‍⚕️ triage
