### ISSUE TITLE
Unholy DK. Default primary rotation tells me to spam outbrak single target

### ISSUE THREAD

**Issue by Vanadin1** [Hekili/hekili#2295] opened 2023-01-17 18:27 UTC
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### WoW Version

Retail (Dragonflight)

### Describe the Issue

When I am in my default icy veins raiding spec running heklili on unholy DK, the rotation tells me to proc army of the dead, then spam outbreak until I die. I fixed the issue by going into settings and disabling outbreak.

It also tells me to use anti magic shell on my primary rotation bar even though AMS doesnt do damage. Yes I have defensives enabled, but it's in the primary bar, not in the top left defensive area.

### How to Reproduce

Unholy dk, single target

### Player Information (Link)

```Text
build: v10.0.2-2.0.15a
level: 70 (70)
class: DEATHKNIGHT
spec: unholy

talents: antimagic_barrier
    antimagic_shell = 1/1
    antimagic_zone = 1/1
    apocalypse = 1/1
    army_of_the_damned = 1/1
    army_of_the_dead = 1/1
    assimilation = 1/1
    brittle = 1/1
    chains_of_ice = 1/1
    clawing_shadows = 1/1
    cleaving_strikes = 1/1
    coil_of_devastation = 1/1
    coldthirst = 1/1
    commander_of_the_dead = 1/1
    dark_transformation = 1/1
    death_rot = 1/1
    death_strike = 1/1
    deaths_echo = 1/1
    empower_rune_weapon = 1/1
    enfeeble = 1/1
    eternal_agony = 1/1
    festering_strike = 1/1
    festermight = 2/2
    gloom_ward = 1/1
    icebound_fortitude = 1/1
    icy_talons = 2/2
    improved_death_coil = 2/2
    improved_festering_strike = 2/2
    infected_claws = 1/1
    insidious_chill = 1/1
    magus_of_the_dead = 1/1
    march_of_darkness = 1/1
    merciless_strikes = 1/1
    might_of_thassarian = 1/1
    mind_freeze = 1/1
    outbreak = 1/1
    raise_dead = 1/1
    raise_dead_2 = 1/1
    reaping = 1/1
    runic_attenuation = 1/1
    scourge_strike = 1/1
    soul_reaper = 1/1
    sudden_doom = 1/1
    summon_gargoyle = 1/1
    unholy_assault = 1/1
    unholy_aura = 2/2
    unholy_bond = 2/2
    unholy_command = 2/2
    unholy_endurance = 1/1
    unholy_ground = 1/1
    unholy_pact = 1/1
    veteran_of_the_third_war = 2/2
    will_of_the_necropolis = 2/2

pvptalents: none

covenant: none

conduits: none

soulbinds: []

sets: ruby_whelp_shell = 1
    tier29 = 3

gear: elemental_lariat = 1
    goldscar_pelt = 1
    grasps_of_the_haunted_frostbrood = 1
    greaves_of_the_haunted_frostbrood = 1
    helmet_of_reverent_loyalty = 1
    jaws_of_the_haunted_frostbrood = 1
    jeweled_signet_of_melandrus = 1
    nhallishs_bloody_polearm = 1
    primal_molten_breastplate = 1
    ruby_whelp_shell = 1
    rumbling_ruby = 1
    scaleguards_stalwart_greatboots = 1
    signet_of_titanic_insight = 1
    thrashing_wind_vambraces = 1
    tier29 = 3
    unstable_frostfire_belt = 1

legendaries: none

itemIDs: 110036, 133639, 134513, 134542, 190495, 191623, 192999, 193001, 193698, 193728, 193757, 194303, 200407, 200409, 200410

settings: aoe = 2
    buffPadding = 0
    combatRefresh = 0.1
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = true
    cycleDebuff = festering_wound
    cycle_min = 6
    damage = true
    damageDots = false
    damageExpiration = 8
    damageOnScreen = true
    damagePets = false
    damageRange = 0
    debuffPadding = 0
    enabled = true
    enhancedRecheck = true
    gcdSync = true
    maxTime = 10
    nameplateRange = 8
    nameplates = true
    noFeignedCooldown = false
    package = Unholy
    petbased = false
    potion = potion_of_spectral_strength
    regularRefresh = 0.5
    throttleRefresh = false
    throttleTime = false
    disable_iqd_execute = false

toggles: cooldowns = true 
    custom1 = false 
    custom2 = false 
    defensives = false [separate]
    essences = false [overridden]
    interrupts = false [separate]
    mode = aoe 
    potions = false 

keybinds: 
    abomination_limb    =
    antimagic_shell     = C1  [02]
    antimagic_zone      = S5  [06]
    any_dnd             = 5   [01]
    apocalypse          = F2  [03]
    army_of_the_dead    = S3  [06]
    asphyxiate          = S7  [06]
    blood_boil          =
    chains_of_ice       = SR  [06]
    clawing_shadows     = 1   [01]
    control_undead      =
    dancing_rune_weapon =
    dark_command        = S4  [06]
    dark_transformation = F1  [03]
    death_and_decay     = 5   [01]
    death_coil          = 2   [01]
    death_gate          =
    death_grip          = M4  [05]
    death_strike        =
    deaths_advance      = M5  [05]
    deaths_caress       =
    deaths_due          = 5   [01]
    defile              = 5   [01]
    empower_rune_weapon = C3  [02]
    epidemic            = 3   [01]
    festering_strike    = 4   [01]
    gorefiends_grasp    =
    heart_strike        =
    icebound_fortitude  = C2  [02]
    lichborne           = C5  [02]
    marrowrend          =
    mind_freeze         = R   [01]
    outbreak            = F5  [03]
    raise_ally          = C4  [02]
    raise_dead          = S1  [06]
    scourge_strike      = 1   [01]
    soul_reaper         = F6  [03]
    summon_gargoyle     = F3  [03]
    tombstone           =
    unholy_assault      = F4  [03]
    unholy_blight       =
    vampiric_blood      =
    wound_spender       = 1   [01]

warnings: none
```

### Error Messages (Link)

```Text
none
```

### Contact Information

Vanadin#0001

**Comment by Hekili** [comment] 2023-01-17 18:30
This should be a recommendations ticket.  You'll need to provide the required snapshot of the issue.

## Snapshot

Please supply a Snapshot of the addon's decision-making when you are seeing this issue in-game. This is not a screenshot. To generate a Snapshot, please complete the following steps.

 * Log into your WoW character.
 * Recreate the issue you are reporting (i.e., generate 5 Holy Power).
 * When you see the recommendation you disagree with, press ALT-SHIFT-P to Pause and Snapshot (or use ALT-SHIFT-[ to Snapshot without pausing).
   * You can change these keybindings in /hekili > Toggles if needed.
   * If you take the snapshot at a different time, it will not be useful and you'll be asked to submit a new one.
 * Type /hekili and press Enter.
 * Open the Snapshots section on the left side.
 * Select the snapshot that shows the recommendation that you disagree with.
   * Snapshots are labeled with your specialization, the display in question (usually, you'll choose Primary), and the recommendations the addon made with their timings.
 * Click in the Export Snapshot box, press CTRL+A to select all text including hidden text and press CTRL+C to copy.
 * Open [https://pastebin.com](https://github.com/Hekili/hekili/issues/Pastebin), use CTRL+V to paste the snapshot text, then click Create New Paste.
 * Provide the Pastebin ***link*** in a new comment.

This step is essential, as most issues are related to specific classes, specializations, gear, talent choices, or other game systems.  If you do not provide this information, I cannot triage your problem.

**Comment by Brutaljuice** [comment] 2023-01-18 05:12
Don't have a snapshot, but just wanted to confirm I saw this updated behaviour in raid after updating Hekili today.  Weird stuff in Single-Target Unholy DK, like spamming clawing shadows nonstop, even though no plague or wounds were on the target, anti-magic shell showing up over and over, etc.

**Comment by Hekili** [comment] 2023-01-18 18:22
This will not be resolved without a snapshot.  Please be sure to provide one as soon as you can manage.  Thanks!

**Comment by xNeptune** [comment] 2023-01-19 01:43
https://pastebin.com/kiX335DT
Went ahead and got a snapshot of this happening as I've also noticed this issue and haven't dove into the cause yet but the default action list definitely appears to have changed from what I remember with tinkering and looking at entrys for actions.
Replicated on target dummy in valdrakken.
//- It looks like the action list from simcraft has actually updated and AMS is used to generate runic power, as a DPS spell.

**Comment by Hekili** [comment] 2023-01-23 17:17
This snapshot does not show Outbreak being recommended multiple times.

Edit:  Oh, yes, using AMS is part of the DPS priority now.  You can disable the ability if you'd prefer it not be recommended.

**Comment by Hekili** [comment] 2023-01-23 17:21
No snapshot was supplied for the original topic; closing ticket.

**Closed as not planned by Hekili** 2023-01-23 17:21 UTC
Labels: 🐛 Bug, 🧑‍⚕️ triage
