### ISSUE TITLE
[Assassination Rogue] Reccomendation error + few suggestions/requests

### ISSUE THREAD

**Issue by IIeTpoc** [Hekili/hekili#2062] opened 2022-12-01 22:08 UTC
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

With cooldowns toggled off during fight Rec#3 might cause an auto snapshot. (https://pastebin.com/iqY7ekCK)

Tweaks/Suggestions:

1. Make an opener sequence with multiple Garrotes as it is a decent DPS gain according to theorycrafters.
Right now opener goes as following: **Garrote -> Slice and Dice -> Serrated Bone Spike** (https://pastebin.com/WP9rVDze)

With shrouded suffocation, garrote gives 3 combo points and does quite a lot of damage. By casting extra garrotes in the openers, we get instant ticks of damage from re-applying, as well as extending to max duration pandemic before Exsanguinate using the Vanish. Vanishing before the Deathmark in the openers allows you to sync them together. You can hold the vanish and vanish during Deathmark when the original garrotes drop, which can be slightly better DPS in Patchwerk situations. The timings this causes during fights however can be very undesirable. Because of that, we recommend syncing and taking a simulated 0.5% loss in damage over spreading your cooldowns out and running into difficult situations. In the single target openers, you can Ambush -> Slice -> Garrote. Because of the delay in garrote and the above reasons, there is no discernable  difference in DPS between these two approaches.
![image](https://user-images.githubusercontent.com/64799395/205164135-b1ddf2ea-cf83-4abb-893b-9a9256b69bca.png)
![image](https://user-images.githubusercontent.com/64799395/205164173-38b3540e-e03e-4547-9f50-53a96350066c.png)
![image](https://user-images.githubusercontent.com/64799395/205164276-62579201-2060-4f08-95d7-b05b092b3c7b.png)

This is not yet implemented in the latest simcraft APL changes.

2. Please implement Exsanguinate + Echoing Reprimand sync feature which is also a DPS gain.
It is already implemented in latest simcraft apl. (https://github.com/simulationcraft/simc/blob/dragonflight/engine/class_modules/apl/rogue/assassination_df.simc)
I tried to do the "translation" of the changes to Hekili in #2060 and Exsanguinate+Echoing Reprimand syncing is working good from my tests on target dummy. But Rec#3 issue which i reported above persists still when Toggle cooldowns is turned off. (My initial report is based on your latest addon version) 

### How to Reproduce

1. Start DPSing a target dummy as assassination rogue
2. Turn off cooldowns toggle.
3. In around 30-60 seconds of following rotation an error will occure

### Talent Loadout

BMQAOB/7AZ//CwQOf4fPMswHVLNJSCiElEAAAAAAAJAkkAAAAAAAQQaOQJJkkkkWIikQiEJJB

### Snapshot

https://pastebin.com/iqY7ekCK

### Contact Information

IIeTpoc#3818 discord ID

**Comment by Hekili** [comment] 2022-12-02 00:11
The basis for comparison for the addon are sim behavior vs. addon behavior.  If changes are accounted for in sim priorities, they don't need to be ticketed because I will update from sim priorities.

**Comment by IIeTpoc** [comment] 2022-12-02 00:31
Ok I get it, Number 1 with openes sequence is not something that is implemented into simcraft as far as i understand. But this opened is still considered an upgrade according to theorycrafters in rogue discord community

**Comment by Hekili** [comment] 2022-12-02 00:38
Yeah, the issue is that I really prefer changes to the addon to be tested or testable with sims.  Using Garrote multiple times in the opener doesn't sound particularly complicated; in fact, I think it did that for a while during pre-patch.

> But Rec#3 issue which i reported above persists still when Toggle cooldowns is turned off. (My initial report is based on your latest addon version)

Sorry, what does Rec#3 issue mean?

**Comment by IIeTpoc** [comment] 2022-12-02 01:03
With cooldowns toggled off during fight Reccomendation number 3 sometimes can not be suggested which causes an auto-snapshot. The snapshot link is here (https://pastebin.com/iqY7ekCK).

And I think you are right, It is advantageous to wait till Simcraft updates APL. I am not 100% percent sure how people from rogue discord calculated that opener with multiple Garrotes is better than default Simc. I am asking some theorycrafters in discord right now. 

EDIT: I got the answer. Basicly it is quality of life change. We trade a 0.5% dps loss to a better sychronisation of our cooldowns.
It would be really nice if you could implement it aswell or may be as an option for people who would like an overall easier rotation throughout the fight.
> "By casting extra garrotes in the openers, we get instant ticks of damage from re-applying, as well as extending to max duration pandemic before Exsanguinate using the Vanish. Vanishing before the Deathmark in the openers allows you to sync them together"
> "The openers are set up in a way where you do not need to think about the animacharged combo points. If you do the openers as listed, you should be able to use the same sequence over and over with no variations, always landing on an animacharged combo point when you need it."

**Comment by Hekili** [comment] 2022-12-03 17:03
I'm going to close this due to recent priority updates.  If there are specific issues that carry over, feel free to open a new ticket and with specific details for those issues (what you're actually seeing, what you should be seeing, why you think you should be seeing something different, etc.).

**Closed as completed by Hekili** 2022-12-03 17:03 UTC
Labels: 📈 recommendations, 🧑‍⚕️ triage
