### ISSUE TITLE
Sin Rogue: Primary - Garrote Issues

### ISSUE THREAD

**Issue by DrWren** [Hekili/hekili#3975] opened 2024-10-16 15:28 UTC
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Not sure what happened, auto snap shot took it; was on Court, went blank, took 8 sec for it to recommend Mutalate again, looked at the log, said garrote?  Wanted to show it to you.

### How to Reproduce

Logged in Sin, played on Heroic Court, not sure how to reproduce.

### Player Information (Link)

https://pastebin.com/RVZH5F5C

### Error Messages (Link)

https://pastebin.com/RVZH5F5C

### Contact Information

Wren1740

**Comment by DrWren** [comment] 2024-10-17 17:12
Not sure if this should be under bug or under recommendation??? Sorry, might have put it under the wrong one. Sorry!!!!

**Comment by Hekili** [comment] 2024-10-17 20:32
Thanks.  I reviewed your snapshot; the issue is that the priority is written to spend Envenom at max CP when Darkest Night is up, but is also written not to Mutilate if you're only missing one (or no) Combo Point(s).  I have made a modification that will allow the Mutilate to cap CP when starting Envenom with Darkest Night; it will be in today's release.

**Closed as completed by Hekili** 2024-10-17 20:32 UTC
Labels: 🐛 Bug, 🧑‍⚕️ triage
