### ISSUE TITLE
Request: add option to turn off current/queued spell highlight

### ISSUE THREAD

**Issue by leinstay** [Hekili/hekili#1852] opened 2022-11-02 08:09 UTC
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### WoW Version

Retail (Dragonflight)

### Describe the Issue

The Glow setting does not remove the Blizzard overlay when the first recommended ability key is pressed.

https://imgur.com/a/3HwZKD3

### How to Reproduce

1. Press or hold the first ability button in the queue suggested by Hekili
2. Pay attention to the bluish overlay 

### Player Information (Link)

```Text
build: v10.0.0-06.1
level: 60 (60)
class: PALADIN
spec: retribution

talents: art_of_war
    ashes_to_ashes = 2/2
    ashes_to_dust = 1/1
    aspiration_of_divinity = 2/2
    auras_of_swift_vengeance = 1/1
    avenging_wrath = 1/1
    blade_of_justice = 1/1
    blade_of_wrath = 1/1
    blessing_of_freedom = 1/1
    blessing_of_protection = 1/1
    blessing_of_sacrifice = 1/1
    cavalier = 1/1
    consecrated_blade = 1/1
    crusade = 1/1
    divine_purpose = 1/1
    divine_steed = 1/1
    divine_storm = 1/1
    empyrean_power = 1/1
    final_reckoning = 1/1
    fist_of_justice = 2/2
    greater_judgment = 1/1
    hallowed_ground = 1/1
    hammer_of_wrath = 1/1
    hand_of_hindrance = 1/1
    healing_hands = 1/1
    highlords_judgment = 1/2
    holy_aegis = 2/2
    holy_blade = 1/1
    holy_crusader = 1/1
    improved_crusader_strike = 1/1
    incandescence = 1/1
    judgment_of_light = 1/1
    lay_on_hands = 1/1
    of_dusk_and_dawn = 1/1
    rebuke = 1/1
    recompense = 1/1
    righteous_verdict = 1/1
    sanctification = 1/1
    seal_of_order = 1/1
    seal_of_reprisal = 2/2
    seasoned_warhorse = 1/1
    shield_of_vengeance = 1/1
    tempest_of_the_lightbringer = 1/1
    unbreakable_spirit = 1/1
    virtuous_command = 2/2
    wake_of_ashes = 1/1
    zeal = 1/1

pvptalents: aura_of_reckoning
   law_and_order
   lawbringer

covenant: night_fae

conduits: echoing_blessings = 4
   expurgation = 5
   lights_barding = 4
   shielding_words = 4
   templars_vindication = 5
   virtuous_command = 5

soulbinds: [koreyn]
   face_your_foes = 1
   get_in_formation = 1
   horn_of_the_wild_hunt = 1
   hunts_exhilaration = 1
   wild_hunt_tactics = 1

sets: eternal_aspirants_medallion = 1
    gladiators_medallion = 1

gear: dvuruchnyy_mech_vechnogo_pretendenta = 1
    eternal_aspirants_medallion = 1
    gildeyskaya_gerbovaya_nakidka_slavy = 1
    gladiators_medallion = 1
    latnaya_brigantina_vechnogo_pretendenta = 1
    latnye_boevye_naruchi_vechnogo_pretendenta = 1
    latnye_boevye_rukavitsy_vechnogo_pretendenta = 1
    latnye_boevye_sapogi_vechnogo_pretendenta = 1
    latnye_nabedrenniki_vechnogo_pretendenta = 1
    latnye_naplechnye_shchitki_vechnogo_pretendenta = 1
    latnyy_bolshoy_poyas_vechnogo_pretendenta = 1
    latnyy_shlem_vechnogo_pretendenta = 1
    mayka_okrovavlennogo_boytsa = 1
    medalon_vechnogo_pretendenta = 1
    ozherele_vechnogo_gladiatora = 1
    pechatka_vechnogo_pretendenta = 1
    pelerina_vechnogo_gladiatora = 1
    persten_vechnogo_pretendenta = 1
    znak_rastoropnosti_vechnogo_pretendenta = 1

legendaries: none

itemIDs: 192210, 192216, 192318, 192321, 192324, 192335, 192347, 192365, 192376, 192379, 192385, 192388, 192391, 192401, 192412, 69210, 98543

settings: aoe = 3
    buffPadding = 0
    combatRefresh = 0.1
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = true
    cycle_min = 6
    damage = true
    damageDots = false
    damageExpiration = 8
    damageOnScreen = true
    damagePets = false
    damageRange = 0
    debuffPadding = 0
    enabled = true
    enhancedRecheck = true
    gcdSync = true
    maxTime = 10
    nameplateRange = 8
    nameplates = true
    noFeignedCooldown = false
    package = Retribution
    petbased = false
    potion = spectral_strength
    regularRefresh = 0.5
    throttleRefresh = false
    throttleTime = false
    check_wake_range = true

toggles: cooldowns = false 
    custom1 = false 
    custom2 = false 
    defensives = false 
    essences = true 
    interrupts = true 
    mode = automatic 
    potions = false 

keybinds: 
    blade_of_justice       = 3   [02]
    blessing_of_autumn     = =   [02]
    blessing_of_freedom    = S2  [01]
    blessing_of_protection = S3  [01]
    blessing_of_sacrifice  = S1  [01]
    blessing_of_spring     = =   [02]
    blessing_of_summer     = =   [02]
    blessing_of_winter     = =   [02]
    consecration           = X   [01]
    crusade                = SC  [02]
    crusader_strike        = 2   [02]
    divine_shield          = S2  [02]
    divine_steed           = -   [01]
    divine_storm           = ST  [01]
    final_reckoning        = SC  [01]
    flash_of_light         = =   [01]
    hammer_of_justice      = 2   [01]
    hammer_of_wrath        = X   [02]
    hand_of_hindrance      = 1   [01]
    judgment               = SR  [02]
    lay_on_hands           = S3  [02]
    rebuke                 = 3   [01]
    shield_of_vengeance    = S1  [02]
    templars_verdict       = ST  [02]
    wake_of_ashes          = 1   [02]
    word_of_glory          = SR  [01]

warnings: none
```

### Error Messages (Link)

```Text
There are no ingame errors.
```

### Contact Information

Leinstay#0159

**Comment by Hekili** [comment] 2022-11-02 13:20
This is not a bug.  The "glows" that the addon lets you control are the spell activation overlay glows (i.e., then an action bar button lights up when you get a buff).

The "highlight" you are asking about is showing when an ability is queued (`IsCurrentSpell` or `IsCurrentItem`).  It is a fairly recent addition to the addon, and it makes sense to make it configurable at some point, though it won't be a top priority right now.  I'll change this ticket into a feature request and add this to the backlog.

**Comment by leinstay** [comment] 2022-11-02 15:46
Thanks!

**Comment by Hekili** [comment] 2022-11-03 16:17
This is either in the latest release or will be in the next release.  It is controlled by the "Enable Action Highlight" option on each display's Glows tab.

**Closed as completed by Hekili** 2022-11-03 16:17 UTC
Labels: ✨ Feature
