### ISSUE TITLE
[REC] Assassin Rogue failed to generate recommendation

### ISSUE THREAD

**Issue by DrWren** [Hekili/hekili#3853] opened 2024-09-25 13:13 UTC
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Single Target Dummy Testing, Auto snapshott, garrote fail, addon disappeared

### How to Reproduce

Sign in play rogue hit dummy,

### Player Information (Link)

https://pastebin.com/HPtvp3fd

### Error Messages (Link)

https://pastebin.com/HPtvp3fd

### Contact Information

Wren1740

**Comment by syrifgit** [comment] 2024-09-26 13:34
![image](https://github.com/user-attachments/assets/cc72dde8-8eff-41d6-afea-263d22d30656)

This is a duplicate of https://github.com/Hekili/hekili/issues/3853

**Comment by aaronlilla** [comment] 2024-09-26 15:41
I have several more automatically generated snapshots:
https://pastebin.com/Ns2AxrsA
https://pastebin.com/ahfHKeAQ
https://pastebin.com/n8NHS8fT
https://pastebin.com/kg2u0DqD

**Comment by Hekili** [comment] 2024-09-30 20:58
Working on the other other other open ticket.

**Closed as not planned by Hekili** 2024-09-30 20:58 UTC
Labels: 📈 recommendations, 🧑‍⚕️ triage

**Comment by DrWren** [comment] 2024-09-30 21:01
Roger that. Sorry, I every time I see that the SIN stuff has been updated,
I always think the tickets are closed. I apologize. Will
Do better!
