### ISSUE TITLE
Ret Paladin not spending when Final Reckoning and Seraphim are desynced.

### ISSUE THREAD

**Issue by superrior** [Hekili/hekili#1150] opened 2021-07-08 19:05 UTC
well i have more than enough holy power and it keeps recommending crusader strike etc the and sometimes it doesnt recommend using big cds  like final reckonning when its up. i would expect it to work like it works when u test it on dummies and it works great then but when u do mythic+ or something it starts bugging on bosses.

snapshot:
https://pastebin.com/y7vEHvY6

**Comment by Hekili** [comment] 2021-07-08 19:14
Tell me about the time you took the snapshot.  You have 4 Holy Power and it recommended Crusader Strike.  What did you think should've been recommended at that time?

**Comment by Hekili** [comment] 2021-07-08 19:42
So far, it looks like you'd used Final Reckoning in a very-desynchronized-from-Seraphim sort of way, which the priority isn't really written to recover from.  But it is something that could happen, so I should probably resolve it.  The issue is, it'll be challenging to figure out how long to hold Seraphim for in order to resync them.

**Comment by Hekili** [comment] 2021-07-08 23:02
This may be fixed in 1.0.8a-beta1, please test and let me know.

**Comment by Hekili** [comment] 2021-07-10 16:21
I will close this ticket tomorrow if there are no further updates.  Thanks.

**Closed as completed** 2021-07-13 11:48 UTC
Labels: 📈 recommendations
