### ISSUE TITLE
[REC] Havoc DH, Meta is still barely recommended, Opening is wrong

### ISSUE THREAD

**Issue by sK4r4** [Hekili/hekili#3575] opened 2024-08-28 09:36 UTC
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

When opening the fight, metamorphisis is never recommended after Vengeful retreat. Often you need to fight at least a minute until meta is recommended, sometimes never

### How to Reproduce

Just do the normal opening, nothing special is required 

### Snapshot (Link)

https://pastebin.com/AxuS6jwD

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/n8FJPTcmrcxp9mAVZnxcmW

### Contact Information

Skara#2856

**Comment by syrifgit** [comment] 2024-08-28 16:06
Can you explain what **_exactly_** is wrong about the opener? Your snapshot isn't even at the part where your sim uses Meta yet, as far as I can tell. Need more information.

**Comment by sK4r4** [comment] 2024-08-28 16:16
> Can you explain what **_exactly_** is wrong about the opener? Your snapshot isn't even at the part where your sim uses Meta yet, as far as I can tell. Need more information.

I am not sure what i should explain furthermore.
This is like 10 secs after opening the fight. Meta should be used right after Vengeful retreat or like 1-3 recommendations after that. As you see, the first recommendation is Vengeful Retreat. So you should be able to see Meta in Recomm #2-5 somewhere.
And of course the snapshot is not at the part where it uses Meta, because Meta is not recommended for some reason.

Only if you fight for like 1 minute more, meta is recommended.

**Comment by syrifgit** [comment] 2024-08-28 16:28
Looks like sim uses a hard-coded opener to get that meta off. If you remove the strict opener, it would behave just as the addon does. I will leave it up to @Hekili to decide how to handle that, as it's not necessarily always good to set the addon up that way as it can run into unintended issues with how dynamic the game is in reality.

```
actions.opener=potion
actions.opener+=/vengeful_retreat,use_off_gcd=1,if=prev_gcd.1.death_sweep&buff.initiative.remains<2|buff.initiative.remains<0.5&debuff.initiative_tracker.up
actions.opener+=/fel_rush,if=talent.momentum&buff.momentum.remains<6|talent.inertia&buff.unbound_chaos.up&talent.a_fire_inside&(buff.inertia.down&buff.metamorphosis.up&cooldown.blade_dance.remains<gcd.max|hero_tree.felscarred)&debuff.essence_break.down
actions.opener+=/fel_rush,if=talent.inertia&buff.unbound_chaos.up&!talent.a_fire_inside&buff.metamorphosis.up
actions.opener+=/the_hunt
actions.opener+=/felblade,if=(buff.metamorphosis.down|fury<40)&(!talent.a_fire_inside|hero_tree.aldrachi_reaver)
actions.opener+=/reavers_glaive,if=debuff.reavers_mark.down&debuff.essence_break.down
actions.opener+=/immolation_aura,if=(charges=2-!talent.a_fire_inside&cooldown.blade_dance.remains|hero_tree.felscarred)&(!hero_tree.felscarred&buff.unbound_chaos.down|hero_tree.felscarred&(cooldown.metamorphosis.up|buff.inertia.remains<gcd.max*2))&debuff.essence_break.down&buff.immolation_aura.stack<5
actions.opener+=/blade_dance,if=buff.glaive_flurry.up&!talent.shattered_destiny
actions.opener+=/chaos_strike,if=buff.rending_strike.up&(!talent.shattered_destiny)
actions.opener+=/metamorphosis,if=buff.metamorphosis.up&cooldown.blade_dance.remains&buff.inner_demon.down&(!hero_tree.felscarred|buff.demonsurge.stack=2)&(cooldown.essence_break.remains|talent.shattered_destiny|!talent.essence_break)
actions.opener+=/sigil_of_spite,if=hero_tree.felscarred|debuff.reavers_mark.up&(!talent.cycle_of_hatred|cooldown.eye_beam.remains&cooldown.metamorphosis.remains)
actions.opener+=/sigil_of_doom,if=buff.inner_demon.down&debuff.essence_break.down&cooldown.blade_dance.remains
actions.opener+=/eye_beam,if=buff.metamorphosis.down|debuff.essence_break.down&buff.inner_demon.down
actions.opener+=/abyssal_gaze,if=debuff.essence_break.down&cooldown.blade_dance.remains
actions.opener+=/annihilation,if=hero_tree.felscarred&(talent.essence_break|talent.restless_hunter)&buff.demonsurge_annihilation.up,line_cd=10
actions.opener+=/essence_break,if=cooldown.blade_dance.remains<gcd.max&!talent.shattered_destiny&buff.metamorphosis.up|cooldown.eye_beam.remains&cooldown.metamorphosis.remains
actions.opener+=/death_sweep
actions.opener+=/annihilation
actions.opener+=/demons_bite
```

**Comment by sK4r4** [comment] 2024-08-28 16:30
Oh okay, thats interesting. But on another note, wowhead and icy-veins both recommend meta right after using vengeful retreat. It can't be correct to spare meta for like a minute (I didnt count the seconds but it really takes a lot of time until its first recommended to use)

**Comment by syrifgit** [comment] 2024-08-28 16:35
> Oh okay, thats interesting. But on another note, wowhead and icy-veins both recommend meta right after using vengeful retreat. It can't be correct to spare meta for like a minute (I didnt count the seconds but it really takes a lot of time until its first recommended to use)

It's because of what I just said. The sims use a strict opener to replicate that, without the strict opener the sim would behave like the addon and not the guide. Hekili addon doesn't typically do strict openers.

**Comment by bsdgaming** [comment] 2024-08-28 16:41
I believe that Reaver's Glaive not being recommended correctly is one of the causes for the long Meta recommendations. According to sims Thrill of the Fight (buff from ReaversGlaive) should be up before entering Meta.

**Comment by sK4r4** [comment] 2024-08-28 16:42
> > Oh okay, thats interesting. But on another note, wowhead and icy-veins both recommend meta right after using vengeful retreat. It can't be correct to spare meta for like a minute (I didnt count the seconds but it really takes a lot of time until its first recommended to use)
> 
> It's because of what I just said. The sims use a strict opener to replicate that, without the strict opener the sim would behave like the addon and not the guide. Hekili addon doesn't typically do strict openers.

I understand that. But if we ignore the aspect of a hardcoded opener, Meta should be recommended somewhen in the normal roation when the other big cds have been used (Essence Break, The Hunt, Eye Beam, etc). Can I paste the recommendations of a complete fight to show you what I mean?

**Comment by sK4r4** [comment] 2024-08-28 16:45
> I believe that Reaver's Glaive not being recommended correctly is one of the causes for the long Meta recommendations. According to sims Thrill of the Fight (buff from ReaversGlaive) should be up before entering Meta.

happens with the fel scarred tree as well, so this can't be the only reason

**Comment by syrifgit** [comment] 2024-08-28 16:46
> > > Oh okay, thats interesting. But on another note, wowhead and icy-veins both recommend meta right after using vengeful retreat. It can't be correct to spare meta for like a minute (I didnt count the seconds but it really takes a lot of time until its first recommended to use)
> > 
> > 
> > It's because of what I just said. The sims use a strict opener to replicate that, without the strict opener the sim would behave like the addon and not the guide. Hekili addon doesn't typically do strict openers.
> 
> I understand that. But if we ignore the aspect of a hardcoded opener, Meta should be recommended somewhen in the normal roation when the other big cds have been used (Essence Break, The Hunt, Eye Beam, etc). Can I paste the recommendations of a complete fight to show you what I mean?

As I said, I will leave it up to Hekili to decide what to do.

**Comment by Hekili** [comment] 2024-08-29 01:58
This is probably more related to the Demonsurge effects not being accurately modeled just yet.  I believe the Metamorphosis is intended to be cancelled after those are expended, but they're not detected up front.  I'm hoping to resolve that soon.

**Comment by Lithium69280** [comment] 2024-09-06 19:20
Thank you Hekili for helping us!! I'm relieved to have found this post, because I'm lost on the demon hunter, we have a week left before the release of the raids and I'm worried, thank you from my heart for worrying about our cycle problem on the demon hunter both on the tank and on the dps.

**Comment by syrifgit** [comment] 2024-09-10 01:59
Closing as this issue is many, many addon versions ago. If the issue still exists, please open a new ticket with new snapshots and sims.

**Closed as completed by syrifgit** 2024-09-10 01:59 UTC
Labels: 📈 recommendations, 🧑‍⚕️ triage
