### ISSUE TITLE
MM Hunter CD window issue with Arcane Shot

### ISSUE THREAD

**Issue by Lipstopica** [Hekili/hekili#840] opened 2021-01-16 16:47 UTC
Currently using the most updated version of the addon.

Basically during the opener of MM Hunter without Lust and other options ticked, my sim never shows double Arcane Shot. Hekili is suggesting to use two Arcane Shots, when sim is only ever using 1 Arcane Shot (without lust) during cooldowns. This is causing me not to get a 5th aimed shot out within the wild spirits window. (Will explain more in the expect behavior).

To reproduce, just hit a target dummy and follow the rotation with everything enabled.

Basically during the opener of MM Hunter without Lust and other options ticked, my sim never shows double Arcane Shot. Hekili is suggesting to use two Arcane Shots, when sim is only ever using 1 Arcane Shot (without lust) during cooldowns. As you can see in the picture below It's going into a steady shot after the first Arcane Shot then into Aimed Shot for the 5th during Wild Spirits. In the log I provided it shows it suggesting double Arcane Shot instead of Steady Shot which ended up leaving me never getting that 5th Aimed Shot.  I believe the sim is not really reacting to the Precise Shots during Wild Spirits as its better to get as many Aimed Shots out as possible.

![Untitled](https://user-images.githubusercontent.com/48372691/104817588-22224f80-581a-11eb-9879-ce5ee7e5a0f7.png)

https://pastebin.com/JbMn4nzQ
https://pastebin.com/X2ghxtz9

Please tell me if I need to get another snapshot. I took this snapshot after I followed the first Arcane Shot and when it was suggesting to use the second Arcane Shot. Where I believe the Steady Shot should've been instead of Arcane Shot to be able to go into another Aimed Shot.

**Comment by Lipstopica** [comment] 2021-01-16 17:12
I would also like to add that the sim does show double aimed shots, but thats out of the CD range such as Wild Spirits etc, just never during unless Lust is up which I guess is because of the extra haste and focus regen?

**Comment by Lipstopica** [comment] 2021-01-16 20:28
Also suggests using two aimed shots back to back when simc list is one aimed shot into two aimed shots after rapid fire. Not sure whats actually happening

**Comment by Hekili** [comment] 2021-01-16 20:29
If you want this to go anywhere, you have to follow the ticket instructions.

**Comment by Lipstopica** [comment] 2021-01-16 20:29
What am I missing? I've posted everything it asked for

**Comment by Lipstopica** [comment] 2021-01-16 20:30
snapshots, whats expected, whats happening

**Comment by Lipstopica** [comment] 2021-01-16 20:33
https://pastebin.com/cnmg1kqm

Issue report, which is the only thing I missed? really. What else? Cant post error message as there is none

**Comment by Lipstopica** [comment] 2021-01-16 20:35
Literally, # 841 got more feedback on what else to send without proper format than what I've gotten while using a good format I think

**Comment by Hekili** [comment] 2021-01-16 20:41
It's really helpful to keep it in the format.  841 is a poorly constructed ticket, too, but was simply an easier issue to look at.  We are not going to do the "fighting for attention" in these tickets.  Seriously.

Okay, the best thing you can do, to have a demonstrative snapshot, is to turn the Primary display up to showing 10 recommendations and grab a snapshot that directly matches the portion of the sim.  And also, to link the actual sim.  That way, a side-by-side comparison is more viable.

**Comment by Lipstopica** [comment] 2021-01-16 20:42
Thank you for the feedback. I will go ahead and do that when I can

**Comment by Hekili** [comment] 2021-01-16 20:47
Thanks for being willing to gather info.  It'll help to diagnose and resolve any issue here.  One area to clear up will be whether the predictive portion (i.e., the queued recommendations) match expectations but the first recommendation does not.  That'd imply some minor difference between the model and what actually occurred in-game.

**Comment by Lipstopica** [comment] 2021-01-16 21:14
Sent you the sim in Discord DM
 
 Double Arcane - https://pastebin.com/yfAQyeHA (snapped on the second Arcane Shot that was being suggested)
 Double Aimshot open - https://pastebin.com/7hWC0sFB (Snapped on the second Aimed Shot, Technically 3rd if you count the actual start combat aimed shot instead of it being Rapid Fire comapred to sims)
 
 Hope those are the right snapshots that you're looking for with 10 icons being shown.

**Comment by Lipstopica** [comment] 2021-01-17 15:56
Just checking are those snapshots fine or do you need them snapshotted before the actual recommended ability? Also not sure if you wanted/needed me to answer or the logs would answer "One area to clear up will be whether the predictive portion (i.e., the queued recommendations) match expectations but the first recommendation does not.". 

I do feel like they're different from each other. Like when I am casting the aimed shot, that suggests going into rapid fire it changes to the second aimed shot just before the end of the cast/gcd if that makes sense. The Arcane shot only shows one in the recommendation until it moves into the first icon then the second one appears in the recommended

**Comment by Hekili** [comment] 2021-01-17 16:09
I will let you know if/when I need anything else; thanks.

**Comment by Lipstopica** [comment] 2021-01-17 16:16
Sorry and thank you. Would like to add just one more thing though. From the first Aimed Shot after Blood Fury, it suggests going into Rapid Fire until the near the end of gcd/cast of the Aimed Shot then switches to Aimed Shot for the second Aimed Shot when it should still have suggested Rapid Fire. If I just ignore the Aimed Shot and use Rapid Fire anyway, the rotation goes perfectly to sims from the last few attemps of testing that I did. So not sure if that might be something

**Comment by Hekili** [comment] 2021-01-17 16:20
If you have additional information to add, it's a good idea to link the snapshot + screenshot + highlight the actual point in sims you're reference.  We're kind of at a point where reconstructing what you're saying from additional context is time-consuming and I'm not totally certain which pieces of information are relevant and which aren't.

**Comment by Lipstopica** [comment] 2021-01-17 16:28
Understood

**Comment by Hekili** [comment] 2021-01-18 16:30
This has required a fair amount of research, so sorry for taking time.

So far, it seems there are a combination of things happening:

1.  I hadn't proactively modeled the CDR effect on Aimed/Rapid when you pop Trueshot.  The addon would instead react to this after you hit Trueshot, resulting in new recommendations that differ slightly depending on haste/focus regen, etc.

2.  It *seems* that the Rapid Fire channel time in SimC isn't reducing accurately from haste.  I've asked Putro to look at it, he disagrees but we'll see how that pans out.  If my modeling is inaccurate, what you'd see if a rapid change from one set of predictions to a different set of predictions.  Once I fix the first point above, that shouldn't really be the case (barring procs, etc.).

So yeah, I'll fix point 1 and we'll see how things go with point 2.

**Comment by Lipstopica** [comment] 2021-01-18 16:43
Thank you for looking into it without me providing the best information for you to go off. Very much appricated.

**Comment by Hekili** [comment] 2021-01-18 16:44
You provided a lot.  It was a lot to sort through.  It's just really complicated.  I appreciate what you provided.

**Comment by Hekili** [comment] 2021-01-18 19:26
Re: the second point, Putro and some simc buddies investigated and found that the delays after a channeled spell in the sim is by design and pretty consistent throughout (i.e., there's a delay between the end of Void Torrent and the start of the next cast for Shadow Priests).  My own judgment is that a delay of as much as 0.3 seconds is *a bit much* but it does account for most of the remaining discrepancy between addon behavior and your sim.

In short, your sim is cautious and avoids clipping the end of a channel, and this ultimately results in a delay, and can be followed by another 0.1s delay, and this can compound a fair bit.

I don't like differing from SimC significantly, but the short answer is that your character, following the sim priority, absolutely would've cast an Arcane Shot after the first Rapid Fire, in the short window afterward, before Aimed Shot was available.  By contrast, your sim will hesitate at the end of the channel, providing enough time for Aimed Shot to be ready instead of using the Arcane Shot.

I'm not sure there's a measurable performance difference, and both are executing the priority list correctly.  It's just a matter of delaying vs. not.  For my addon, I've generally chosen not to build in delays because I don't have to model your player behavior -- I just use your actual player behavior.  If you react slowly, recommendations change, and you get the new recommendations.

So, part 2 probably doesn't have an easy/clean solution that's worth pursuing.  But I'll put in the CDR from Trueshot, which will prevent some flicker.

**Comment by Lipstopica** [comment] 2021-01-18 19:43
Took me a few attemps to understand properly, but I believe I know what you're meaning now. I see what you mean by it being really complicated. But thanks for taking your time to also explain how things are actually working, really helps me understand the explanation behind it.

**Comment by Hekili** [comment] 2021-01-18 21:25
All available fixes will be in next beta build.

**Closed as completed by Hekili** 2021-01-18 21:25 UTC
Labels: 🐛 Bug
