### ISSUE TITLE
[REC] Moonkin venthyr sinful hysteria issue

### ISSUE THREAD

**Issue by Olanid57** [Hekili/hekili#1169] opened 2021-07-16 17:08 UTC
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

I expect the addon to be around 60/90 AsP during my cd and spend it all during the 5s extension buff (legendary)
Actually it spends all before

### How to Reproduce

1. Target dummy 
2. Talents for mythicplus : trees, soul of the forest, FoE
2. Follow the addons until the last second of my venthyr buffs

### Snapshot (Link)

https://pastebin.com/BagEwtNf

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/8pSjXT7XyoBFk1Re2Hoy21

### Additional Information

Already discussed on Discord #general

**Comment by Hekili** [comment] 2021-07-16 17:33
So far, it looks to be working as intended.  The entry for Starsurge that is firing is firing because Celestial Alignment is falling off.  The sim has Celestial Alignment up through all of Ravenous Frenzy.

![image](https://user-images.githubusercontent.com/9438134/125985550-49aa4fac-a38a-44d4-a2e0-249cc9708553.png)

The next Starsurges are recommended because Sinful Hysteria is up and it's happily dumping AsP.

The difference may be related to the sim having Bloodlust on pull, but you don't have Bloodlust active.  I'm not quite sure.  It seems more like your alignment of Celestial Alignment and Ravenous Frenzy aren't great -- which could be based on addon recommendations, not sure yet, tbh.

In the screenshot, you can see that the sim uses Celestial Alignment once it is about 5 seconds into Ravenous Frenzy.  In your usage, they would've been popped almost simultaneously.  Was that based on the addon's recommendations?  Can you go to /hekili > Primary > Displays and set your queue to 4 or 5 icons, and take a snapshot when both Ravenous Frenzy and Celestial Alignment are recommended, before this point?

Thanks!

**Comment by Olanid57** [comment] 2021-07-16 20:25
Im in raid right now, im gonna do that after. In raid my CA lasts more than 10s more than RF but i have the same problem.
And hekili recommends CA & RF at the same time

**Comment by Hekili** [comment] 2021-07-16 20:26
Provide the snapshots and I'll investigate.  Thanks!

**Comment by Olanid57** [comment] 2021-07-16 22:23
Snapshots 1 : https://pastebin.com/QgDRkwp0
Snapshots 2 : https://pastebin.com/nL4vVDUj
Snapshots 3 : https://pastebin.com/tgNRSvmV

I took 1 snapshot 2 recommandations before CDs and 1 just before the last 3 starsurges at the end of CDs, idk why I had 3 in snapshots settings ! ^^

If you need more help or things to investigate, let me know.

Hafe fun

**Comment by Olanid57** [comment] 2021-07-16 22:25
If it can help : i have the same issue with incarnation : chosen of elune talents which lasts 10 more seconds than RF

**Comment by Hekili** [comment] 2021-07-16 22:27
It can only help if you submit snapshots for that scenario, too.

**Comment by Olanid57** [comment] 2021-07-17 11:38
Incarnation : https://pastebin.com/B5YaGHfH

**Comment by Hekili** [comment] 2021-07-25 13:50
Priority has changed a bit since then (and may have a bug, waiting on a report).  Gonna close this so there'll be one thread related to Venthyr and CDs.

**Closed as completed by Hekili** 2021-07-25 13:50 UTC
Labels: 📈 recommendations, 🧑‍⚕️ triage
