### ISSUE TITLE
Frost Mage:  Recommendations flicker when casting Flurry with Brain Freeze but no Fingers of Frost

### ISSUE THREAD

**Issue by LucianDK** [Hekili/hekili#952] opened 2021-03-08 01:37 UTC
**Describe the Bug/Issue**
Ive frequently noticed that with frost mage since I started on the spec yesterday. That the spells in the queue will  quite often very rapidly flicker between the choices when casting flurry with the brain freeze proc, and ice lance is showing as recommended.
Its not pleasant for my eyes to look at for long. I wanted to hear if that is intended behavior.
But should I hazard a guess, its because flurry is a multihit spell, combined with it adding winters chill that will empower ice lance that causes the issue.. Though there seem to be a spell interaction that I cant precisely pin down since it doesnt happen all the time.

build: v9.0.2-1.0.40a
level: 60 (60)
class: MAGE
spec: frost

talents: chain_reaction
    ice_ward
    incanters_flow
    lonely_winter
    shimmer
    splitting_ice
    thermal_void

pvptalents: none

covenant: venthyr

conduits: flow_of_time = 3
   icy_propulsion = 2

soulbinds: [nadjia_the_mistblade]
   agent_of_chaos = 1
   friends_in_low_places = 1
   thrill_seeker = 1

sets: none

gear: acolytes_velvet_bindings = 1
    cinch_of_infinite_tightness = 1
    darkmoon_deck_putrescence = 1
    doubtweavers_handwraps = 1
    faewoven_cowl = 1
    faewoven_drape = 1
    glyph_of_assimilation = 1
    grimveiled_pants = 1
    harp_of_the_sanguine_court = 1
    hishtars_severe_stiletto = 1
    hyperlight_band = 1
    most_regal_signet_of_sire_denathrius = 1
    renowned_guild_tabard = 1
    shadowlace_mantle = 1
    shadowlace_tunic = 1
    sin_stained_pendant = 1
    sparkling_glass_slippers = 1

legendaries: slick_ice = 1

itemIDs: 173069, 173214, 173220, 173246, 175588, 178827, 179570, 179623, 183017, 183023, 183028, 183036, 183038, 184021, 184170, 184798, 69210

settings: aoe = 3
    buffPadding = 0
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = false
    cycle_min = 6
    damage = true
    damageDots = false
    damageExpiration = 6
    damagePets = false
    damageRange = 0
    debuffPadding = 0
    enabled = true
    gcdSync = true
    maxRefresh = 10
    maxTime = 33
    nameplateRange = 8
    nameplates = false
    package = Frost Mage
    petbased = false
    potion = potion_of_spectral_intellect
    potionsReset = 20180919.1
    throttleRefresh = false
    throttleTime = false
    ignore_freezing_rain_st = true

toggles: cooldowns = true
    custom1 = false
    custom2 = false
    defensives = false
    essences = true
    interrupts = false
    mode = automatic
    potions = false

**Comment by Hekili** [comment] 2021-03-08 03:04
**BEFORE SUBMITTING AN ISSUE:**

1.  Check to see if you are using the latest version of the addon.  If there is a newer alpha/beta/release version, see if your problem exists with the new version.

2.  Check to see if someone else has already opened an issue report here.  Please don't submit repeat reports.

**Describe the Bug/Issue**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
- Go to '...'
- Click on '....'
- Scroll down to '....'
- See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**WHEN SUBMITTING AN ISSUE:**

Please provide the following information.  Leaving it out may result in your ticket being ignored (because I won't have the information needed to explore your report).

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here.

**PUT ISSUE REPORT LINK HERE:**

2.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot.  This is not a screenshot.  A snapshot can be generated by binding the Pause feature on the Toggles tab.  When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab.  Copy and paste this to pastebin.com and provide the link here.
 
**PUT SNAPSHOT LINK HERE:**

3.  If reporting an error (i.e., the addon freezes and/or disables itself), please install the BugSack and BugGrabber addons as they will enable you to paste the exact error message, with detail that will help me identify where the code error is located.  You can paste the error information here or use pastebin.com for that as well.

**PUT ERROR MESSAGE(S) HERE:**

**Comment by LucianDK** [comment] 2021-03-08 04:49
Managed to reproduce the issue :)

BEFORE SUBMITTING AN ISSUE:
build: v9.0.2-1.0.40a

Describe the Bug/Issue
Rapid flickering of Ice Lance icons in queue list after casting Flurry when Fingers of Frost is NOT present and Icicles is at 5, and then casting Flurry once Brain Freeze have procced
If Fingers of Frost is present, the issue does not happen. 

To Reproduce
Cast Frostbolt till till Icicles is at 5 stack, which will trigger Ice Lance recommendation. Continue casting Frostbolt till Brain Freeze have procced and giving you an instant cast Flurry that will apply Winter's Chill.  If Fingers of Frost have procced as well, click away the buff to just have Ice Lance recommended from 5 stack Icicles alone - you may have to cast Frozen Orb/Icy Veins to ensure both are on cooldown to not intrude on the queue, then cast Flurry and the flickering will happen. I speculate its related to each impact of Flurry.

Expected behavior
No icon flickering.


Snapshot
https://pastebin.com/wSqRmCnY

**Comment by LucianDK** [comment] 2021-03-08 14:56
Its casting Flurry with Brain Freeze, while Fingers of Frost is NOT present. And that Icicles is at 5 stacks.

**Comment by LucianDK** [comment] 2021-03-18 14:13
I am not certain whats missing from here.

**Comment by Hekili** [comment] 2021-03-19 16:40
Frost mage snapshot:

Frost mage here as well, using v9.0.5-1.0.1a and glacial fragments legendary (now named Icebringer, if that matters at all).
I was getting spam errors before the bandaid but still getting them after updating.

Weird thing is the snapshot spam stops and everything goes back to normal if I unequip the Icebringer legendary (I picked pants slot) and starts again if I put them on.

pastebin of snapshot: (sorry if this isn't proper, never done this before)

pastebin.com/VBWfwTmG

**Comment by Hekili** [comment] 2021-03-20 13:41
I could use more information about what it flickers between -- i.e., if it's flickering, I really need a snapshot of the two scenarios it flickers between.  Then I can investigate whether there's an aura detection issue, a spell impact timing issue, or if it really is just a really narrow window between the two recommendations.

**Comment by LucianDK** [comment] 2021-03-20 18:48
[After2.txt](https://github.com/Hekili/hekili/files/6176205/After2.txt)
[Before.txt](https://github.com/Hekili/hekili/files/6176186/Before.txt)
[After.txt](https://github.com/Hekili/hekili/files/6176187/After.txt)
I think After2 may be the better one, as that is right after the flickering stopped on a new round. After was mid-flickering.

Ok, as far as reproducing it reliably, its under these conditions:
Both Icy Veins and Frozen Orb is on cooldown, so the bar recommendation looks like 2x Ice Lance and 1x Flurry.
The issue does not happen if Frozen Orb and Icy Veins is present on the recommendation bar.
Buffwise, Fingers of Frost is NOT present, but Brain Freeze is present.
Then an Ice Lance icon will rapidly flicker between Frostbolt and Ice Lance, x3 times, upon casting Flurry. And Flurry makes x3 impacts.

**Comment by Hekili** [comment] 2021-04-03 14:31
The piece you seem concerned about is likely a function of travel times for spells.  I don't have a solution for this, and it's been hard for me to track your explanation.  I'm going to close this ticket.

**Closed as completed by Hekili** 2021-04-03 14:31 UTC
Labels: 🐛 Bug
