### ISSUE TITLE
[11.0.2] Spells Replaced by Hero Talents

### ISSUE THREAD

**Issue by MatteoLombardi** [Hekili/hekili#3450] opened 2024-08-07 17:21 UTC
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

In beta everything seems to work just fine for aug evoker, the main issue I found seems to be Breath of the Eons not stopping being recommended when overwritten by the talent enabling steering. Should be a pretty straight forward fix, can't provide a snapshot right now, but I will once I get home. Just wanted to address it in time for early access (same happens for summon demon for warlock and shadowfiend for voidweaver, but not gonna open 3 issues without snapshots)

### How to Reproduce

Enter the game as max level aug evoker with Scalecommander and just play around

### Snapshot (Link)

Will provide! (Sorry, terrible reporter)

**Comment by MatteoLombardi** [comment] 2024-08-08 09:55
The new commit fixed aug, so I'm updating the issue with the other cases to help keeping track!

SPriest error with Shadowfiend: https://pastebin.com/9VV59xsu (there's a lot of LUA errors regarding entropic rift, had to cut the logs to fit pastebin's limit)

**Comment by Hekili** [comment] 2024-08-08 14:35
I'll fix the typo causing those errors you noted.  In terms of catching spell replacements for new (hero) talents, the details I'll need to fix them up would be:

* Class / Spec
* (Hero) Talent
* Spell `x` should change to spell `y` when ( `z` is talented *or* `z` buff is active, etc.)

Ideally, `x` and `y` are the spell IDs on your action bar.  You can set up ElvUI to show the spell ID in the tooltip or get another addon that includes spell IDs in tooltips.

**Comment by MatteoLombardi** [comment] 2024-08-08 14:41
I'll fetch them soon :) I'd do the changes myself and open a PR given the time, but giving you the data is prolly faster

**Comment by MatteoLombardi** [comment] 2024-08-08 14:47
Priest/Shadow
Voidweaver
Shadowfiend (34433) should change to Voidwraith (451235) when talented in Voidwraith

**Comment by MatteoLombardi** [comment] 2024-08-09 15:19
@Hekili I understood what the problem with warlock might be, dunno if you need a snapshot or not. The addon gets stuck on the "generic" summon demon spell with affliction, since it's missing the preferred demon option that Destro has. So the primary icon is an empty square with no icon, pause shows it being "Summon demon"

**Comment by MatteoLombardi** [comment] 2024-08-09 15:24
Also:

- Warlock / Affliction
- Hellcaller
- Corruption (172) should change to Wither (445468) when talented in Wither

**Comment by MatteoLombardi** [comment] 2024-08-21 22:05
Are some fixes coming for early access?

**Comment by DumbRogue** [comment] 2024-08-23 08:18
Just wanted to piggy back off this since Devastation Evoker has the same issue with Deep Breath on Live now, it keeps recommending Deep Breath even after using it when you have Maneuverability. 

Class/Spec: Evoker (Devastation)
Hero Talents: Scalecommander
Talent Name: Maneuverability
Deep Breath ID needs to change from 357210 to 433874 when you're playing Scalecommander with Maneuverability.

**Comment by MatteoLombardi** [comment] 2024-08-23 12:11
- Demon Hunter / Both
- Aldrachi-Reaver
- Throw Glaive (185123) should Change to Reaver's Glaive (442294) when talented in Art of the Glaive (every 6 Soul Fragments or after The Hunt is cast)

**Comment by ziggykoala** [comment] 2024-08-23 12:50
Class/Spec: Evoker (Augmentation)
Hero Talents: Chronowarden
Talent Name: Chrono Flame
Living Flame (361469) should change to Chrono Flames (431443) when talented into Chrono Flame

**Comment by Xephus1** [comment] 2024-08-23 12:56
Confirmed last night for Warlock. 
Affliction when talented into Hellcaller/Wither does not replace corruption neither spell is ever recommended. Didn’t test destruction. But Wither should replace immolate.

**Comment by superzuk02** [comment] 2024-08-23 14:56
Class Spec: Ret Paladin
Hero Talents: Templar
Talent Name: Hammer of Light
Description: Hammer of Light hero ability is not recommended once available after using Wakes of Ashes ability and requiring 5 Holy Power.

**Comment by MatteoLombardi** [comment] 2024-08-23 18:08
Another Ret paladin (@xilostcause) in #3520 notifies the error [in this snapshot](https://pastebin.com/feUHMian)

**Comment by ziggykoala** [comment] 2024-08-23 21:23
Class/Spec: Evoker (Augmentation)
Hero Talents: Scalecommander
Talent Name: Maneuverability
Breath of Eons ID (403631) should change to (unconfirmed) 442204 when you're playing Scalecommander with Maneuverability.

**Comment by TerrySmith22** [comment] 2024-08-24 17:09
I too was about to report the matter with  Hammer of light, but decided to look if it had reports already. seem like its just a matter of patience to fix.

**Comment by himea-saito** [comment] 2024-08-24 17:23
Adding on to this, when picking the talent Voidwraith for Voidweaver priest the recommendations completely break.

Mindbender (123040) if specced into it, or Shadowfiend (34433) is being replaced with Voidwraith (451235). Hekili recommends to cast Mindbender, and when it is cast stops recommending most abilities until is off cooldown again.

**Comment by Hekili** [comment] 2024-08-25 02:29
> Mindbender (123040) if specced into it, or Shadowfiend (34433) is being replaced with Voidwraith (451235). Hekili recommends to cast Mindbender, and when it is cast stops recommending most abilities until is off cooldown again.

It would be helpful to provide a snapshot when the recommendations fail.

**Comment by MatteoLombardi** [comment] 2024-08-25 02:38
Pretty much the same snapshot I shared for shadowfiend, just with mindbender. Since Mindbender replaces Shadowfiend, and Voidwraith replaces both, no matter which variant of the pet you have talented, it should become Voidwraith. Since the addon is not recommending Voidwraith but the talented pet, it gets stuck as it used to with Maneuverability and Breath of the Eons for Aug

**Comment by himea-saito** [comment] 2024-08-25 02:49
> > Mindbender (123040) if specced into it, or Shadowfiend (34433) is being replaced with Voidwraith (451235). Hekili recommends to cast Mindbender, and when it is cast stops recommending most abilities until is off cooldown again.
> 
> It would be helpful to provide a snapshot when the recommendations fail.

It's pretty reproducible, here's the snapshot I just got. Simply pulled the mob and cast Voidwraith and it failed over to the scov_prep action list. It also doesn't recognize that Voidwraith is on cooldown so it goes back to recommending Mindbender as soon as the Voidwraith pet has expired, even though it can't be cast yet.

https://pastebin.com/L9bkwLQn

**Comment by Hekili** [comment] 2024-08-25 02:56
No, I need the snapshot when the recommendations have stopped.  The snapshot you provided is recommending Shadowfiend, no?

**Comment by himea-saito** [comment] 2024-08-25 05:07
> No, I need the snapshot when the recommendations have stopped. The snapshot you provided is recommending Shadowfiend, no?

Nope! 😅

I pressed Voidwraith and then the snapshot key. I'll try again with some screenshots.

Before entering combat:
![image](https://github.com/user-attachments/assets/fe23b2f0-5360-42a7-a1cd-089d6526434f)

After pressing Voidwraith:
![image](https://github.com/user-attachments/assets/351eeac9-e3e4-4080-b9fa-ddaf4e266a36)

It looks like it generated two snapshots automatically so maybe I copied a wrong one? Here is both:

https://pastebin.com/0cFP8XLT
https://pastebin.com/jVDHEKKp

**Comment by PinkLionArt** [comment] 2024-08-25 11:46
Deep Breath is being recommended when it's on CD

Evoker / Devastation
Scalecommander, Talent 433871 (Maneuverability)
Deep Breath 357210 should change to Deep Breath 433874 when Maneuverability 433871 is talented

https://pastebin.com/dj3CBkAs
![Dev Deep Breath](https://github.com/user-attachments/assets/4b1337f9-e8bf-4849-9306-ad8011617054)

**Comment by syrifgit** [comment] 2024-08-26 03:20
Is this fixed for Aug with the newest update? @MatteoLombardi

**Comment by Sarge95k** [comment] 2024-08-26 14:52
Can coroborate Devestation Evoker Scalecommander recomending Deep Breath after it has been used and is on CD.
As Above believe:
 
Talent 433871 (Maneuverability)
Deep Breath 357210 should change to Deep Breath 433874 when Maneuverability 433871 is talented

will fix issue

**Comment by darren-henderson** [comment] 2024-09-04 18:15
I see that it was noted a few months ago and again a couple of weeks ago so just giving it a bump... wither is not replacing corruption as it should. This is as of version 11.0.2-1.0.7

Warlock/Affliction
Hellcaller
corruption->wither

**Comment by Zanetsuken** [comment] 2024-09-04 19:40
> I see that it was noted a few months ago and again a couple of weeks ago so just giving it a bump... wither is not replacing corruption as it should. This is as of version 11.0.2-1.0.7
> 
> Warlock/Affliction Hellcaller corruption->wither

Have you made any edits to your APL? Because i have never had this issue.

**Comment by Hekili** [comment] 2024-09-05 02:50
I'm not able to replicate this issue with Affliction/Hellcaller/Wither.

**Comment by darren-henderson** [comment] 2024-09-05 17:57
> > I see that it was noted a few months ago and again a couple of weeks ago so just giving it a bump... wither is not replacing corruption as it should. This is as of version 11.0.2-1.0.7
> > Warlock/Affliction Hellcaller corruption->wither
> 
> Have you made any edits to your APL? Because i have never had this issue.

Not quite clear on what you are asking - I've not changed any of the hekili code.

When the servers come back up I'll disable everything else and dig a bit more.


EDIT:   This was user error - sorry folks.

**Comment by syrifgit** [comment] 2024-09-10 02:23
Closing this ticket. If you find an issue for an individual spec or hero tree, please open a new ticket for that specific issue.

**Closed as completed by syrifgit** 2024-09-10 02:23 UTC
Labels: 📈 recommendations, 🧑‍⚕️ triage
