### ISSUE TITLE
Hunter MM

### ISSUE THREAD

**Issue by Sisrat** [Hekili/hekili#1589] opened 2022-08-19 23:01 UTC
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

When i equip the trinket "Enforcer's Stun Grenade", the other trinkets get's delidet from the rotation. And the trinket "Enforcer's Stun Grenade" is not in the rotation to see as icon.

### How to Reproduce

MM Hunter

### Snapshot (Link)

Marksmanship; Primary - Gezielter Schuss(0.00), Doppelpack(2.07), Todeschakram(3.31)

### Contact Information

Hekili

**Comment by Hekili** [comment] 2022-08-20 03:29
Duplicate of #1586.

**Closed as completed by Hekili** 2022-08-20 03:29 UTC
Labels: 📈 recommendations, 🧑‍⚕️ triage
