### ISSUE TITLE
Reccomendation doesn't change after action selected

### ISSUE THREAD

**Issue by gyllygan** [Hekili/hekili#2646] opened 2023-05-23 01:54 UTC
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

While play Sub Rogue after the most recent update, [v10.1.0-1.0.1h](2023-05-22), I noticed the recommended action doesn't change and will just get hung up despite selecting that action. It seems to be getting hung up during anything, even selecting poison.~~Shuriken Storm + Black Powder~~. Also noticing that it is recommending Single Target actions despite being in AOE.

### How to Reproduce

1. Enter game as Sub Rogue
2. Follow the addons recommendation
3. Recommendation doesn't update.
4. Appears to get hung up and non responsive.

### Snapshot (Link)

Snapshot wasn't working

### Contact Information

Discord- Gyll#0179

**Comment by Hekili** [comment] 2023-05-23 02:06
Duplicate of #2645

**Closed as completed by Hekili** 2023-05-23 02:06 UTC
Labels: 📈 recommendations, 🧑‍⚕️ triage
