### ISSUE TITLE
[REC] Enhancement Shaman Flame Shock reapply.

### ISSUE THREAD

**Issue by dhaos21** [Hekili/hekili#2605] opened 2023-05-14 15:19 UTC
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

After going through the ST rotation it will get to a point where it will start wanting you to reapply flame shock every 3 or 4 GCD's

### How to Reproduce

1. Enter game as Enhancement Shaman
2. Attack Single target Dummy
3. Go through rotation that hekili suggests

### Snapshot (Link)

https://pastebin.com/7Bm1wjND

**Comment by Hekili** [comment] 2023-05-14 18:00
Duplicate of #2600; this is largely resolved with `1.0.0l` and has an additional fix coming in `1.0.1`.

**Closed as completed by Hekili** 2023-05-14 18:00 UTC
Labels: 📈 recommendations, 🧑‍⚕️ triage
