### ISSUE TITLE
Multitude of LUA errors on recent update

### ISSUE THREAD

**Issue by raghalis** [Hekili/hekili#3828] opened 2024-09-22 17:11 UTC
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Attempting to call various fields resulting in lua errors

- Events.lua:1663: attempt to call field callHook (a nil value)
- Events.lua:117: attempt to call method SpecializationChanged (a nil value)
- Events.lua:326: attempt to call method SpecializationChanged (a nil value)
- Options.lua:10251: attempt to call upvalue callHook (a nil value)
- UI.lua:2408: attempt to call method GetActiveSpecOption (a nil value)

### How to Reproduce

Install newest update.
Load into game
Get blasted with lua errors

### Player Information (Link)

unable. see below

### Error Messages (Link)

https://pastebin.com/afBMdK4v

### Additional Information

Cant open the hekili addon due to the lua errors

### Contact Information

raghalis (discord)

**Comment by syrifgit** [comment] 2024-09-22 17:12
Duplicate of https://github.com/Hekili/hekili/issues/3827

**Closed as not planned by syrifgit** 2024-09-22 17:12 UTC
Labels: 🐛 Bug, 🧑‍⚕️ triage
