### ISSUE TITLE
Does not respond to the lava surge buff

### ISSUE THREAD

**Issue by istari0n** [Hekili/hekili#847] opened 2021-01-18 20:16 UTC
With Windspeaker's Lava Resurgence legendary effect, I should spend lava surge procs before using earth shock. But the line "buff.lava_surge.up" doesn't seem to work at all. It is always in a "false" state.

**Comment by Hekili** [comment] 2021-01-18 20:21
Please fill out the complete ticket with all the required information.

**BEFORE SUBMITTING AN ISSUE:**

1.  Check to see if you are using the latest version of the addon.  If there is a newer alpha/beta/release version, see if your problem exists with the new version.

2.  Check to see if someone else has already opened an issue report here.  Please don't submit repeat reports.

**Describe the Bug/Issue**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
- Go to '...'
- Click on '....'
- Scroll down to '....'
- See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**WHEN SUBMITTING AN ISSUE:**

Please provide the following information.  Leaving it out may result in your ticket being ignored (because I won't have the information needed to explore your report).

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here.

**PUT ISSUE REPORT LINK HERE:**

2.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot.  This is not a screenshot.  A snapshot can be generated by binding the Pause feature on the Toggles tab.  When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab.  Copy and paste this to pastebin.com and provide the link here.
 
**PUT SNAPSHOT LINK HERE:**

3.  If reporting an error (i.e., the addon freezes and/or disables itself), please install the BugSack and BugGrabber addons as they will enable you to paste the exact error message, with detail that will help me identify where the code error is located.  You can paste the error information here or use pastebin.com for that as well.

**PUT ERROR MESSAGE(S) HERE:**

**Comment by istari0n** [comment] 2021-01-18 21:00
**Describe the Bug/Issue:**
Addon does not track a buff "lava surge" (Elemental shaman). The current priority list contains the line "buff.lava_surge.up", but the presence of this buff does not affect the state in any way. it is always "false". So using this line does not lead to any positive result and i cant prioritise lava burst procs (lava surge) higher then earth shock.

**To Reproduce
Steps to reproduce the behavior:**

Go to 'Priorities'
Click on 'Elemental > Action lists > Entry'
Scroll down to 'Actually, it is a first string (Flame shock)'
See this line: "( ! ticking | dot.flame_shock.remains <= gcd | talent.ascendance.enabled & dot.flame_shock.remains < ( cooldown.ascendance.remains + buff.ascendance.duration ) & cooldown.ascendance.remains < 4 ) & ( buff.lava_surge.up | ! buff.bloodlust.up )"
Expected behavior: Addon does not changes state of "buff.lava_surge.up" line when it does procs

**A clear and concise description of what you expected to happen.**
Well, I need the ability to change the priority of the "lava burst" according to the availability of the "lava surge" proc.
![lava surge](https://user-images.githubusercontent.com/77640898/104962270-218be380-59e9-11eb-841b-12a9101fc33d.png)

P.S. I did my best with english ^^

**Comment by Hekili** [comment] 2021-01-18 21:02
Thanks.  Still need you to provide the *snapshot* that's described in the ticket.

Does your UI show spell IDs if you mouseover a spell icon?  I'm guessing your Lava Surge spell ID changed when you equipped your legendary.

**Comment by istari0n** [comment] 2021-01-18 21:10
My UI does not show spell IDs but i disequipped legendary item and nothing happend to the state of lava surge buff.

**Comment by istari0n** [comment] 2021-01-18 21:17
[lava surge snsh.txt](https://github.com/Hekili/hekili/files/5832429/lava.surge.snsh.txt)

**Comment by Hekili** [comment] 2021-01-18 21:19
Thanks for the snapshot.  I have a fix for this.

**Closed as completed** 2021-01-18 21:24 UTC
Labels: 🐛 Bug
