### ISSUE TITLE
[REC] Bladestorm Keybind Not Displaying After 8/25 Update

### ISSUE THREAD

**Issue by Mosborne90** [Hekili/hekili#3534] opened 2024-08-25 06:49 UTC
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

After the update on 8/25, Hekili is no longer showing the keybind for bladestorm. I use the consoleport addon to play wow alongside hekili, but I tested this with consoleport disabled and the issue persists.

Note: There is no issue with the priority, this is only the keybind not displaying for Bladestorm.

Things I have tried: 
1. Disabled the consoleport addon completely. The keybind for bladestorm does not show this way either.
2. Ran a macro to remove abilities from every action bar to ensure this was not a repeat of last time.
3. Assigning bladestorm to a different keybind did not fix the issue
4. Reset all keybinds through the consoleport addon

This screenshot shows bladestorm recommended with no keybind
![image](https://github.com/user-attachments/assets/ebe11271-9303-4371-ae6c-6d3b4e42d691)

This screenshot shows bladestorm is assigned to LB within the consoleport addon
![image](https://github.com/user-attachments/assets/ad166e17-b9a4-4a09-8aea-d010384f095f)

This screenshot shows that LB is an assigned keybind
![image](https://github.com/user-attachments/assets/a1fff2e5-5d89-427c-b869-5d7b31424d07)

This screenshot shows that bladestorm is on my bar as LB
![image](https://github.com/user-attachments/assets/4a5114bd-4670-4d35-b746-3709e82014a3)

The snapshot does not have bladestorm listed as a keybind
![image](https://github.com/user-attachments/assets/5316600d-c0d2-4c20-85c3-a751341c31e4)

### How to Reproduce

Not sure if the problem is on my end or I did something to break it. If this was an issue with the addon after the update, the user would need to test hekili using a controller, specifically looking at the bladestorm keybind.

### Snapshot (Link)

https://pastebin.com/phj1zmZY

**Comment by mkaliaha** [comment] 2024-08-25 09:28
![image](https://github.com/user-attachments/assets/3af7ebb4-9206-411d-aef2-4a8191e4ea2e)
![image](https://github.com/user-attachments/assets/b8e9ccaa-75bc-4454-a85b-887115fb3977)
It does reproduce even without consoleport, without controller. At first I had a copy of bladestorm on my panels without keybind, but removing it did nothing.

**Comment by mkaliaha** [comment] 2024-08-25 11:06
Update: also breaks for Arms.
The reason seems to be the [Unrelenting Onslaught](https://www.wowhead.com/spell=444780/unrelenting-onslaught) talent in the Slayer hero talents.
It changes ID for the Bladestorm from 227847 (https://www.wowhead.com/spell=227847/bladestorm) to 446035 (https://www.wowhead.com/spell=446035/bladestorm) for both specs.

**Comment by mkaliaha** [comment] 2024-08-25 12:14
Created PR https://github.com/Hekili/hekili/pull/3539 for this issue.

**Comment by Hekili** [comment] 2024-08-25 22:30
This should be resolved in v11.0.2-1.0.4.

**Closed as completed by Hekili** 2024-08-25 22:30 UTC
Labels: 📈 recommendations, 🧑‍⚕️ triage
