### ISSUE TITLE
Keybindings for action bars 6-8 not being detected

### ISSUE THREAD

**Issue by jgwallace3** [Hekili/hekili#1946] opened 2022-11-14 16:34 UTC
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### WoW Version

Retail (Dragonflight)

### Feature Request

Using stock keybindings I cannot get hekili to recognize any actions on the subject bars. Bars 1-5 work as expected.

### Contact Information

greywun#5079

**Comment by Hekili** [comment] 2022-11-15 18:58
Duplicate of #1764

**Closed as completed by Hekili** 2022-11-15 18:58 UTC
Labels: ✨ Feature, 🧑‍⚕️ triage
