### ISSUE TITLE
Fists of Fury channel not broken when expected (Weapons of Order) + other stuff.

### ISSUE THREAD

**Issue by Smudgiee** [Hekili/hekili#686] opened 2020-12-13 19:41 UTC
When having this option ticked and with the new changes to WW Monk to interrupt FoF with SeF and WoO up, it's not suggesting to interrupt at all. It stays greyed out until the end of the channel, this also applies for SeF it's greyed out until 1gcd has ended then lights back up when its useable and should be used right away. I will include two snapshots, one with FoF not suggesting to cancel with this Fade ticked. And the SeF just in case that is also an issue or intended. 

Now I believe this works completely fine on Spriest, with the exact same settings when I tested Spriest it would be greyed out but then would light up in the middle of a channel to interrupt to cast the next suggested ability. So this may only be an issue for WW Monk somehow.

https://pastebin.com/W5Etmbkp -- FoF not being suggested to interrupt (Fade as Unusable ticked)
https://pastebin.com/4srF0PNS   -- SeF greyed out until end of GCD (Fade as Unusable ticked)

**Comment by Hekili** [comment] 2020-12-13 19:58
1.  You have interrupts disabled.
2.  Fists of Fury doesn't (yet) have tick times in place for the FoF channel to be interrupted.
3.  When I resolve part 2, it will still not recommend to break Fists of Fury to interrupt a spell, as the conditions for breaking Fists of Fury are related to Weapons of Order being up, not interrupting.
4.  You could resolve 3 with a custom priority or by showing interrupts separately from your Primary display.
5.  SEF being greyed out until it's time to use it is literally what "Fade as Unusable" does.

Please include/follow the ticket instructions when submitting a ticket.  The second point will be addressed in the near future.  The rest is working as intended.

**Comment by Smudgiee** [comment] 2020-12-13 20:02
Interrupts have nothing to do with interrupting a channel? Isn't that for an actual interrupt/kick ability? Maybe I didnt word it correctly but I meant interrupted the channel not interrupt kick. Should've used "breaking".

**Comment by Hekili** [comment] 2020-12-13 20:06
Well, you said interrupts, so...

Since you have two tickets for the same issue, I'll close this one.

**Closed as completed by Hekili** 2020-12-13 20:06 UTC
Labels: 🐛 Bug
