### ISSUE TITLE
[FEATURE] REPLACE THIS TEXT WITH A BRIEF DESCRIPTION OF YOUR NEW FEATURE

### ISSUE THREAD

**Issue by Isucceeded** [Hekili/hekili#2753] opened 2023-07-30 11:10 UTC
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/enhancement) for this request and was not able to find one.
- [X] I edited the title of this feature request (above) so that it describes the issue I am reporting.

### Feature Request

Hey is it real to get mage profiles for hekili in wrath?

### Additional Information

And maybe anytime soon?

**Comment by Hekili** [comment] 2023-08-01 02:06
Duplicate of an open ticket.  Mage will be available when it's available.

**Closed as not planned by Hekili** 2023-08-01 02:06 UTC
Labels: ✨ Feature, 🧑‍⚕️ triage
