### ISSUE TITLE
[REC] Ret recommendations show cooldown/wait time although abilities are available

### ISSUE THREAD

**Issue by cremor** [Hekili/hekili#2454] opened 2023-03-02 16:51 UTC
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

It seems like there can be situations where Hekili recommends a Ret Paladin to wait quite a long time (multiple seconds) before using an ability, altough many abilities are available. Not only that, but it also recommended to use a Holy Power builder although I already was at 5 Holy Power (similar to #2170).

### How to Reproduce

I'm not sure how to reproduce this, but I assume this is what happened:

1. Have Crusade available.
2. Get Retribution Aura to proc Crusade.
3. Get to a state where Hekili would recommend Crusade.
4. Check recommendations.

### Snapshot (Link)

https://pastebin.com/JHTewW5D

### Additional Information

The snapshot only shows a wait time less than one second because I didn't take it immediately. Before that the shown wait time was longer.

Most likely Crusade could be replaced with Avenging Wrath when the Crusade talent is not taken.

**Comment by Hekili** [comment] 2023-03-13 21:53
I've been looking into this; it appears to be caused by Crusade proccing from Retribution Aura (since your Crusade does not appear to be on CD despite having the buff active).  In your case, it seems like you may have had a chain of procs, since you have 10 stacks of Crusade with ~6 seconds remaining, but Crusade is not on cooldown.

Could you provide a Raidbots sim of your character with 3+ targets?

**Comment by Hekili** [comment] 2023-03-13 22:08
I'm realizing that doesn't make sense, as Ret Aura procs Seraphim.  Somehow, the cooldown of Crusade is showing as zero despite you having the buff up and 10 stacks.  Continuing to investigate.  (Edit:  Wait, it does both.  This is why I shouldn't code with covid brain.)

**Comment by Hekili** [comment] 2023-03-13 22:32
Testfix in 1.0.23b.

**Comment by cremor** [comment] 2023-03-14 09:45
Thanks, but I won't be able to test this because I'm taking a break from WoW until season 2.
Do you still need a Raidbots sim?

**Comment by Hekili** [comment] 2023-03-14 12:17
It would still be helpful, yes.

**Comment by cremor** [comment] 2023-03-14 17:06
3 target sim: https://www.raidbots.com/simbot/report/qMuz8Fhr8v3QYHxemg7zAM

**Comment by Hekili** [comment] 2023-03-20 12:30
I believe this has been addressed in 10.0.5 (no other reports).  Additionally, the logic and workarounds don't apply in 10.0.7, so I'm going to treat as resolved and close this issue.  Thanks for the additional sim despite not actively playing.  :)

**Closed as completed by Hekili** 2023-03-20 12:30 UTC
Labels: 📈 recommendations, retail
