### ISSUE TITLE
Epidemic being suggested while using Deadliest Coil at 3 or less targets. (Unholy DK)

### ISSUE THREAD

**Issue by Siestasam** [Hekili/hekili#837] opened 2021-01-15 00:09 UTC
**Expected behavior**
According to sims and testing, while the Deadliest Coil legendary is equipped it is best to use Death Coil at 3 or less targets even outside of Dark Transformation because of the CDR it provides. However, the addon is suggesting Epidemic inside and outside of the Dark Transformation duration.

 
**PUT SNAPSHOT LINK HERE:**

[Epidemic Issue Hekili.txt](https://github.com/Hekili/hekili/files/5817585/Epidemic.Issue.Hekili.txt)

**Comment by Hekili** [comment] 2021-01-15 00:48
This is the Epidemic entry whose criteria passed.

```
62.  epidemic ( aoe_burst - 4 )
The action (epidemic) is usable at (1.25 + 1.25).
 - the action is ready before the current recommendation (at +1.25 vs. +60.00).
List ( aoe_burst ) called from ( Unholy:default:18 ) would PASS at 1.25.
active_enemies[3.00] >= 2 & death_and_decay.ticking[true]
 - this entry's criteria PASSES: ! death_knight.fwounded_targets[0.00] & ! variable.pooling_for_gargoyle[false] | fight_remains[12225.50] < 5 | raid_event.adds.exists[true] & raid_event.adds.remains[12225.50] < 5
Action chosen:  epidemic at 1.25!
```

You have no Festering Wounds up and you're not pooling for gargoyle, so those criteria are met.

The Death Coil entry that didn't pass (checked before the Epidemic entry):

```
59.  death_coil ( aoe_burst - 1 )
The action (death_coil) is usable at (1.25 + 1.25).
 - the action is ready before the current recommendation (at +1.25 vs. +60.00).
List ( aoe_burst ) called from ( Unholy:default:18 ) would PASS at 1.25.
active_enemies[3.00] >= 2 & death_and_decay.ticking[true]
- this entry's criteria FAILS: buff.dark_transformation.up[false] & runeforge.deadliest_coil.enabled[true] & active_enemies[3.00] <= 3
```

You're not in Dark Transformation, so even though you have Deadliest Coil and there are 3 or fewer enemies, the criteria for Death Coil wasn't met.

That appears to be working as intended.

If you want further research, you'll need to provide a snapshot when Epidemic is recommended in the first slot but you think Death Coil should've been recommended (confirm Dark Transformation is up and there are 3 or fewer targets).

**Comment by Siestasam** [comment] 2021-01-15 01:44
![image](https://user-images.githubusercontent.com/77469380/104669744-aead0080-56a8-11eb-81ed-e322cd5d096d.png)

Hello thank you for the quick response, above is a screenshot of epidemic being recommended over DC while DT is up and wounds are on the target.

and here is a snapshot of the same thing:
[Epidemic Issue 2.txt](https://github.com/Hekili/hekili/files/5817893/Epidemic.Issue.2.txt)

**Comment by Hekili** [comment] 2021-01-15 02:16
Are you able to see spell IDs in your UI?

I'd like to check the spell ID for Dark Transformation (the ability) in your spellbook and the spell ID for Dark Transformation (the aura) applied to your ghoul.

Are you using any glyphs that impact your Ghoul?

**Comment by Hekili** [comment] 2021-01-15 02:36
I went ahead and tested the ghoul glyphs and they didn't seem to matter.  My Dark Transformation detection was based on when you cast Dark Transformation, which wouldn't pair well with effects that extend Dark Transformation.  Please try v9.0.2-1.0.36-beta2 (see Releases section) and see if you still have an issue.

**Comment by Siestasam** [comment] 2021-01-15 03:23
Thanks! I will check that version out. However, the issue does not seem limited to just the DT window. According to the DK class discord current consensus, even outside of DT being active, it is better to use DC on 3 or less targets simply because the cooldown reduction DC provides is better than the damage Epidemic does **if you have the Deadliest Coil legendary.** I don't believe the mod is accounting for that either at the moment.

**Comment by Hekili** [comment] 2021-01-15 03:31
If they feel strongly about it, they'll update the sim profile to demonstrate that behavior.

Edit:  They do have some APL revisions that I'll deal with this weekend.  I see they've changed added `| active_enemies = 2` to the end of the conditions for Death Coil in all the aoe lists (`generic_aoe`, `aoe_setup`, and `aoe_burst`).  You could do the same if you don't want to wait.

**Comment by Hekili** [comment] 2021-01-15 14:06
I'm going to close this ticket (let me know if you find a related problem).  The remaining portion of the "fix" will come with priority updates this weekend, which is maintenance (not bugfix).

**Closed as completed by Hekili** 2021-01-15 14:06 UTC
Labels: 🐛 Bug
