### ISSUE TITLE
[REC] Paladin Retribution, Hammer of Wrath recommended but not usable.

### ISSUE THREAD

**Issue by Xeltor** [Hekili/hekili#2603] opened 2023-05-14 12:50 UTC
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

When Avenging Wrath is on cooldown and not up and the target is still above 20% health Hammer of Wrath will sometimes show up as the recommendation even though it is not usable.

### How to Reproduce

1. Enter the game as a Retribution Paladin.
2. Make sure Avenging Wrath is on cooldown and not up.
3. Target is above 20% health.
4. Seems to happen somewhat randomly when above is met.

### Snapshot (Link)

https://pastebin.com/Azsg4bE2

### Contact Information

Xeltor#0001

**Comment by noahfuenfvier** [comment] 2023-05-14 14:49
Can confirm, it starts with the Final Verdict Proc, Hekili doesnt recognize for a few sec that the proc is no longer usable (buff up).

Only in latest Version, on v10.1.0-1.0.0j it is still working as supposed, so u can roll back on an earlier Version for now @Xeltor

**Comment by Dirty23** [comment] 2023-05-14 15:36
Same issue with outlaw rogue, suggesting ambush when not available.

**Comment by Hekili** [comment] 2023-05-14 18:00
Duplicate of #2600; this is largely resolved with `1.0.0l` and has an additional fix coming in `1.0.1`.

**Closed as completed by Hekili** 2023-05-14 18:00 UTC
Labels: 📈 recommendations, 🧑‍⚕️ triage
