### ISSUE TITLE
[REC] UnholyDK/Festermight prio over using RP to buff Gargoyle

### ISSUE THREAD

**Issue by Samejw** [Hekili/hekili#2453] opened 2023-03-02 15:08 UTC
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

For UNHOLY DK add-on suggests using scourge strike/clawing shadows  when at full runic power when gargoyle is up instead of using up runic power to buff gargoyle, it also suggests to start the Festermight window to early so the buff drops off before then end of Gargoyle. There are a few other bad recommendations such as when to use Racial (Berserking, etc..) and when to use Apocalypse

### How to Reproduce

1. Enter game as Unholy Death Knight 
2. Select Talents Festermight, Summon Gargoyle, Plaguebringer/Clawing Shadows 
3. Opener for Unholy DK 

### Snapshot (Link)

https://pastebin.com/ggc2exYg

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/sS3MGwAatYdEDhf3dUAjFs

**Comment by slizersteam** [comment] 2023-03-11 09:46
isnt heikili allready using import from simc to generate the rotation? maybe try to import again in the addon under the unholy tab

**Comment by Hekili** [comment] 2023-03-11 15:27
I don't see Gargoyle as active during your snapshot.  Do you have Gargoyle glyphed by any chance?

**Comment by slizersteam** [comment] 2023-03-11 18:08
doesnt work at all if you have it changed it to dark arbiter

**Comment by Breadwinka** [comment] 2023-03-12 22:52
I notice this happen in raid, next time im in raid ill try and get a snapshot as well. But if I use a training dummy the priority seems fine. And I see this happening with a Glyph gargoyle and unglyphed.

**Comment by Hekili** [comment] 2023-03-13 21:11
This should be addressed in 1.0.23, to the extent that it was caused by detecting that your Gargoyle was active.  Both regular Gargoyle and Dark Arbiters should be counted for their full durations.

**Closed as completed** 2023-03-13 21:11 UTC
Labels: 📈 recommendations, retail
