### ISSUE TITLE
Cache of Acquired Trinkets causing addon to fail to make recommendations

### ISSUE THREAD

**Issue by Justeroo** [Hekili/hekili#1402] opened 2022-03-08 03:08 UTC
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

After updating my Hekili addon (9.2.0-1.0.8) my priority display will not show on my rogue whatsoever. I've swapped characters and it seems to be working on at least one other one (warlock)

I've tried:

- Uninstall/reinstall
- New profile
- bugsack etc. to try and find lua errors
- Finding and adjusting all visibility settings
- Creating a known good profile on my lock then swapping to it on my rogue

Nothing works and the primary display will not show at all. Notification area seems to work as I change settings.

### How to Reproduce

1. Log into game on my rogue
2. Notice no Hekili display

### Player Information (Link)

https://pastebin.com/HNgw4FGt

### Error Messages (Link)

No Errors

### Additional Information

No recurring issues showing up in bugsack. I'm at a loss - it worked just fine last night, my assumption is something with the latest update is causing the issue.

If I've forgotten to include something please let me know.

### Contact Information

Justeroo#0563 - Discord

**Comment by Justeroo** [comment] 2022-03-08 03:13
As a note. I uninstalled and downgraded to the release before this one about 30 seconds ago and it resolves the issue. It's definitely related to the new update.

**Comment by thegameguru** [comment] 2022-03-08 03:36
can confirm the exact same issue.

**Comment by Hekili** [comment] 2022-03-08 03:38
Ok, I can't troubleshoot with a downgraded version.  I'll see if I have issues on Rogue.

**Comment by Hekili** [comment] 2022-03-08 03:40
> can confirm the exact same issue.

By exact same, you mean Rogue?  Can you check /hekili and see if there's a Warnings section?

**Comment by Hekili** [comment] 2022-03-08 03:53
For anyone having this issue, I need:
1. Issue Reporting information.
2. Screenshot of the spec options for your spec(s) that aren't being displayed; especially8 first tab.
3. Any information in the "Warnings" section that can appear at left (if there is no Warnings section, just confirm that).
4. Any error messages (you may need to install BugSack and BugGrabber for this).
5. Possibly a copy of the Hekili.lua file from your SavedVariables/profile.

**Comment by Justeroo** [comment] 2022-03-08 04:19
I'll log in right now and get you everything you need.

**Comment by Justeroo** [comment] 2022-03-08 04:26
1. Player info/character data: https://pastebin.com/HNgw4FGt
2. literally no primary or AoE bar showing.
3. Warnings: https://pastebin.com/RmfGmG7X
4. The above one is the only one I've been able to get into BugSack
5. I don't have a Hekili.lua file in _retail_\WTF\SavedVariables

Observation:
Was working on downgraded version. Updated and problem immediately returned.

**Comment by Hekili** [comment] 2022-03-08 04:37
Try `/run Hekili.Update()` -- this might trigger a more detailed error message in BugSack/Warnings. 

You do have a Hekili.lua file in your account's SavedVariables.

**Comment by Hekili** [comment] 2022-03-08 04:37
> Screenshot of the spec options for your spec(s) that aren't being displayed; especially first tab.

**Comment by Justeroo** [comment] 2022-03-08 04:53
https://pastebin.com/TZ4wH8EX - Hekili.Update error from bugsack
A short video instead of screenshots for the spec options (I think these are the ones you wanted) https://streamable.com/z0j0hg

**Comment by Justeroo** [comment] 2022-03-08 04:56
[Hekili.lua.txt](https://github.com/Hekili/hekili/files/8202888/Hekili.lua.txt)

It's been a while since I've done addon/folder structure work and forgot how it worked. Found it here but github doesn't allow .lua uploads so I changed it to a txt file

**Comment by justindriggers** [comment] 2022-03-08 06:45
Our demon hunter had this issue occur when he equipped the Cache of Acquired Treasures trinket, and the issue is resolved when he unequips the trinket. Let me know if you guys need any information from him.

**Comment by KajiAU** [comment] 2022-03-08 08:51
I have the same exact issue with the Cache of Aquired Treasures trinket

**Comment by Hekili** [comment] 2022-03-08 13:22
Assuming this is an issue for everyone with Cache of Acquired Trinkets, this is fixed in 1.0.8a -- please update and let me know.  Thanks for the bug report info.

**Comment by Justeroo** [comment] 2022-03-08 13:55
> Assuming this is an issue for everyone with Cache of Acquired Trinkets, this is fixed in 1.0.8a -- please update and let me know. Thanks for the bug report info.

Logged in with 4 minutes before reset to verify. Was indeed the issue. Thank you so much for hopping on this and thanks to everyone else who contributed to finding the source!

**Closed as completed** 2022-03-08 13:56 UTC
Labels: 🐛 Bug, 🧑‍⚕️ triage
