### ISSUE TITLE
unholy dk rotation 

### ISSUE THREAD

**Issue by icemanxs1** [Hekili/hekili#1631] opened 2022-09-29 19:08 UTC
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

So pretty much its just its skipping scourge strike. only really using blood strike, plague strike, icy touch, death coil, blood tap. and its same rotation pretty much goes like icy touch. plague strike . blood strike. blood strike . blood strike. death coil and more icy touch spam. tried switching from blood presence to unholy presence and nothing happens 

### How to Reproduce

uhh not sure. i just notice it was skipping some actions 

### Snapshot (Link)

https://pastebin.com/dDmbfs6c

**Comment by Hekili** [comment] 2022-09-29 19:14
Do you have Scourge Strike?

**Comment by icemanxs1** [comment] 2022-09-29 19:36
ya

**Comment by TulukSC2** [comment] 2022-09-29 20:09
Hey! I have the same issue and after checking my snapshot, I realized Scourge Strike isn't registered as a picked talent even if I have the talent chosen.

**Comment by icemanxs1** [comment] 2022-09-29 20:22
Ya i checked pastenbin and i dont even see it in the list.

**Comment by willz501** [comment] 2022-09-29 20:45
probably the same issue with frost and frost strke

**Comment by dmcdaniels** [comment] 2022-10-02 02:20
The problem is in the DeathKnight.lua file. The talent has it selected as looking for 55090 which is the id of the rank 1 spell. As soon as you hit rank 2 the id changes and it thinks you no longer have the spell.  I modified mine for all four ranks and it shows up again.

**Comment by Hekili** [comment] 2022-10-02 04:27
Yeah, it should already be fixed in -beta4 on CurseForge.

**Closed as completed by Hekili** 2022-10-02 04:27 UTC
Labels: 📈 recommendations, 🧑‍⚕️ triage
