### ISSUE TITLE
cooldowns off/on inverted

### ISSUE THREAD

**Issue by odellcubed** [Hekili/hekili#577] opened 2020-11-26 00:39 UTC
cooldowns are turned on when selected off and vice versa. and for demo lock tyrant doesnt seem enabled either way.

build: v9.0.2-1.0.6
level: 58 (58)
class: WARLOCK
spec: demonology

talents: burning_rush
    demonic_calling
    demonic_consumption
    demonic_strength
    mortal_coil
    soul_conduit
    soul_strike

pvptalents: none

covenant: none

azerite: none

essences: [none], none

sets/legendaries/artifacts: none

gear: ashjrakamas_shroud_of_resolve = 1
    deranged_alchemists_slippers = 1
    drustthatched_wristwraps = 1
    emberscale_gloves = 1
    exquisitely_aerodynamic_shoulderpads = 1
    heart_of_azeroth = 1
    manifesto_of_madness = 1
    night_courtiers_ring = 1
    overcharged_pantaloons = 1
    rattling_jar_of_eyes = 1
    redhooks_cummerbund = 1
    robes_of_unreality = 1
    seal_of_fordragon = 1
    shglayos_astral_malignity = 1
    spirit_tenders_hood = 1
    vitacharged_titanshard = 1

legendaries: none

itemIDs: 158075, 159232, 159235, 159282, 159668, 159965, 169071, 169223, 174103, 174108, 174119, 174125, 174500, 175660, 175710, 184165

settings: aoe = 3
    buffPadding = 0
    custom1Name = Custom 1
    custom2Name = Custom 2
    cycle = true
    cycle_min = 6
    damage = true
    damageDots = false
    damageExpiration = 6
    damagePets = false
    damageRange = 0
    debuffPadding = 0
    enabled = true
    gcdSync = true
    maxRefresh = 10
    maxTime = 33
    nameplateRange = 8
    nameplates = false
    package = Demonology
    petbased = false
    potion = unbridled_fury
    potionsReset = 20180919.1
    throttleRefresh = false
    throttleTime = false

toggles: cooldowns = false
    custom1 = false
    custom2 = false
    defensives = false
    essences = true
    interrupts = false
    mode = automatic
    potions = false

**Comment by Hekili** [comment] 2020-11-26 01:12
Fill out a proper ticket with a snapshot when you think this is happening.

**Comment by odellcubed** [comment] 2020-11-26 02:17
![WoWScrnShot_112520_211203](https://user-images.githubusercontent.com/75050716/100300174-6eac8580-2f63-11eb-9dc7-9b8ec0bfd415.jpg)
![WoWScrnShot_112520_211202](https://user-images.githubusercontent.com/75050716/100300183-766c2a00-2f63-11eb-8e30-7537129ab315.jpg)

**Comment by Hekili** [comment] 2020-11-26 02:23
Please follow the instructions and provide the requested information:

**BEFORE SUBMITTING AN ISSUE:**

1.  Check to see if you are using the latest version of the addon.  If there is a newer alpha/beta/release version, see if your problem exists with the new version.

2.  Check to see if someone else has already opened an issue report here.  Please don't submit repeat reports.

**Describe the Bug/Issue**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
- Go to '...'
- Click on '....'
- Scroll down to '....'
- See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**WHEN SUBMITTING AN ISSUE:**

Please provide the following information.  Leaving it out may result in your ticket being ignored (because I won't have the information needed to explore your report).

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here.

**PUT ISSUE REPORT LINK HERE:**

2.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot.  This is not a screenshot.  A snapshot can be generated by binding the Pause feature on the Toggles tab.  When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab.  Copy and paste this to pastebin.com and provide the link here.
 
**PUT SNAPSHOT LINK HERE:**

3.  If reporting an error (i.e., the addon freezes and/or disables itself), please install the BugSack and BugGrabber addons as they will enable you to paste the exact error message, with detail that will help me identify where the code error is located.  You can paste the error information here or use pastebin.com for that as well.

**PUT ERROR MESSAGE(S) HERE:**

**Comment by djsisson** [comment] 2020-11-26 09:46
incorrect spellid for tyrant

should be 265187 NOT 265817, made pull request

**Comment by Hekili** [comment] 2020-11-26 12:34
Thanks for the PR, merged.  I'm closing this ticket because either (1) this will resolve it or (2) I'll need a new ticket that has the required ticket information to pursue further.

**Closed as completed by Hekili** 2020-11-26 12:34 UTC
Labels: 🐛 Bug
