### ISSUE TITLE
[REC] Fury Warrior Multi Target- Only Recommending Whirlwind

### ISSUE THREAD

**Issue by Mosborne90** [Hekili/hekili#3519] opened 2024-08-23 16:01 UTC
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

I'm not certain what is triggering this issue. I've noticed over 5 times now that Hekili is sometimes only recommended Whirlwind for the multi target rotation for Fury Warrior at level 80. Reloading the addon a couple of times seems to fix the issue. Once the issue happens, the multi target rotation will only recommend whirlwind outside of major cooldowns.

### How to Reproduce

I am uncertain how to re-produce the issue. It has happened randomly in a dungeon, and twice in the open world. The log I've uploaded was captured when the issue was present.

### Snapshot (Link)

https://pastebin.com/5LD2iS0z

**Comment by MatteoLombardi** [comment] 2024-08-23 16:23
Duplicate of #3510

**Comment by syrifgit** [comment] 2024-08-23 16:48
Will copy your snapshot over to the other ticket

**Closed as not planned by syrifgit** 2024-08-23 16:48 UTC
Labels: 📈 recommendations, 🧑‍⚕️ triage
