### ISSUE TITLE
[REC] Balance druid opener/cooldown usage with Instructors Divine Bell & IQD incorrect

### ISSUE THREAD

**Issue by yenbounger** [Hekili/hekili#1205] opened 2021-08-11 19:15 UTC
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

Bell is being recommended too early - usage (outside of BL) should be IQD with Ravenous, the bell on last 8 seconds.
Bell is being recommended before ravenous is used.

After a reload, I could not replicate the issue - however this was happening to me in a dungeon, and continued after a log out and a test on a training dummy.

### How to Reproduce

1. Enter game as balance druid
2. Have both IQD & Instructors Divine Bell Equipped (may happen with other on-use, did not have any others to test)
3. Follow rotation reccomended
4. Bell is recommended earlier than expected

Possibly some other steps, have not been able to recreate since a /rl

### Snapshot (Link)

https://pastebin.com/FczUypaY

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/CbdNaciMuPsVe5hoLsJYY

**Comment by Hekili** [comment] 2021-08-12 18:13
This should be fixed with the latest beta; the issue is that your trinkets are being used by the generic "Use Items" action when they're not supposed to be.  That should be fixed.

**Comment by Hekili** [comment] 2021-08-12 23:54
I'm closing this ticket because it overlaps with the other one that's open and active.

**Closed as completed by Hekili** 2021-08-12 23:54 UTC
Labels: 📈 recommendations, 🧑‍⚕️ triage
