### ISSUE TITLE
Microstuttering on fire mage - Memory usage scales up fast

### ISSUE THREAD

**Issue by ZoidieKI** [Hekili/hekili#239] opened 2019-12-05 20:35 UTC
**Describe the Bug/Issue**
When playing fire mage, you can see the screen stuttering.  It looks like a frozen frame in amongst the other frames, but is quite noticeable.  Switching to Frost or Arcane, or playing as any other class does not show the issue.  The program also seems to use memory up a lot faster than the other specs/classes, e.g. Fire always goes up by around 0.10MB per second, other specs are around 0.01-0.02 every 3-4 seconds.

**To Reproduce**
It starts at login and doesn't seem to disappear if you re-zone.

**Expected behavior**
Should be no stuttering and I would probably imagine memory usage should not be so much.

**Screenshots**
Unable to capture with a screenshot.

Issue reporting:

build: v8.2.5-04.04
level: 120 (120)
class: MAGE
spec: fire

talents: conflagration
    flame_on
    frenetic_speed
    incanters_flow
    meteor
    searing_touch
    shimmer

azerite: azerite_empowered=2
    duplicative_incineration=1
    flames_of_alacrity=1
    longstrider=1
    resounding_protection=1
    wildfire=1

essences: none*, none

sets/legendaries/artifacts: none

gear:     7th_legionnaires_mantle=1
    bartered_vrykul_hood=1
    blistering_seawater_seal=1
    fathomstalker_cloak=1
    fort_daelin_lantern=1
    heart_of_azeroth=1
    lord_kennings_signet=1
    maokkas_carving=1
    navigators_bands=1
    navigators_leggings=1
    rikals_ritual_beads=1
    shirakess_cinch=1
    shirakess_wraps=1
    storms_wake_baton=1
    tidespeaker_mittens=1
    tidespeaker_soles=1

itemIDs: 155036, 155089, 155226, 158075, 158272, 158679, 158680, 160335, 160349, 160885, 161446, 163653, 163862, 167757, 167779, 169487

**Comment by Hekili** [comment] 2020-01-13 15:50
Fire Mage requires a great deal more computing because of the crit-anticipation and casting-while-casting.  I'll roll this into the Overhaul ticket.

Duplicate of #246.

**Closed as completed** 2020-01-13 15:50 UTC
Labels: duplicate

**Comment by wow1989** [comment] 2020-03-01 04:19
Any update on this?

Rotation still not optimized during combustion and scorch-execute phase.

Using fire blasts during scorch casts with a heating up proc already active. Not anticipating pyroblast crits during combustion.

**Comment by Hekili** [comment] 2020-03-01 04:25
There have been updates since then, yes.  If you want to help, the best thing you can do is grab snapshots when you see something problematic, and pastebin them so I can look at what was happening.

There are some more updates coming, but I will probably have to write a separate priority for Fire because the SimC one requires more CPU time than I like.
