### ISSUE TITLE
shadow priest void eruption rotation is wrong.

### ISSUE THREAD

**Issue by comproh** [Hekili/hekili#3663] opened 2024-09-05 09:01 UTC
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

shadow rotation with void eruption is wrong. its supposed to be https://i.imgur.com/JNpNdIt.jpeg but hekili is different. 

### How to Reproduce

do the normal rotation from guides. 

### Snapshot (Link)

https://pastebin.com/YaAcSgUs 

### Raidbots Sim Report (Link)

[_No response_
](https://www.raidbots.com/simbot/report/hvmoYP3Um4EGnxbK9sthuu)

### Contact Information

pie.are.squared

**Comment by comproh** [comment] 2024-09-06 09:28
Correction, with that hero talent and the talent  Mindbender, void erruption is removed from your queue list.

**Comment by Hekili** [comment] 2024-09-06 19:47
1. Power Infusion is on CD; Void Bolt therefore is the next ability ready with its criteria met.
2. After Void Bolt, you have 18 Insanity, therefore Devouring Plague isn't going to be usable.
3. Mind Blast on CD is higher in priority...

I think the issue is that the circumstances of entering Voidform are different in your snapshot vs. your sim.  It might be useful to look at a snapshot where Void Eruption is the first recommendation and then see what follows.

**Comment by comproh** [comment] 2024-09-06 20:00
idk how to do that but 
https://pastebin.com/0qZV19Lp this is a longer ST on a dummy now

yeah for some reason it recommends mindblast  first then void bolt.

**Comment by comproh** [comment] 2024-09-06 20:08
> 1. Power Infusion is on CD; Void Bolt therefore is the next ability ready with its criteria met.
> 2. After Void Bolt, you have 18 Insanity, therefore Devouring Plague isn't going to be usable.
> 3. Mind Blast on CD is higher in priority...
> 
> I think the issue is that the circumstances of entering Voidform are different in your snapshot vs. your sim. It might be useful to look at a snapshot where Void Eruption is the first recommendation and then see what follows.

Im following the reommendations Im not doing anything more than that on the snapshots

**Comment by Hekili** [comment] 2024-09-06 20:16
> idk how to do that

Take the snapshot when Void Eruption is being recommended first.

**Comment by comproh** [comment] 2024-09-06 20:22
how do i get it to recommend void eruption first?  i mean im literally just following the recommendations that pops up but  this is the snapshot when void erruption is recommended and after pressing it https://pastebin.com/rtp9q5uc

**Comment by GitBearded** [comment] 2024-09-06 20:28
> how do i get it to recommend void eruption first? i mean im literally just following the recommendations that pops up but this is the snapshot when void erruption is recommended and after pressing it https://pastebin.com/rtp9q5uc

He’s literally telling you to take the snapshot AS SOON AS VOID ERUPTION IS RECOMMENDED, DONT press void eruption then take the snapshot. Do your rotation and the moment void eruption is recommended NEXT on your list, take the snapshot

**Comment by comproh** [comment] 2024-09-06 20:30
https://pastebin.com/KZwMTg53 

AH okay

**Comment by comproh** [comment] 2024-09-06 20:39
it recommends mindblast over void bolt, and its supposed to be void bolt then mind blast right?

**Comment by Hekili** [comment] 2024-09-06 20:47
It's treating Mind Blast and Void Blast as interchangeable, which results in Mind Blast being recommended in the higher priority slot for Void Blast.  I'll address it.

**Comment by comproh** [comment] 2024-09-06 21:19
im not trying to be difficult btw, I just like this addon andits alot easier to use than me making a weakaura for something like this.  lol <3

**Comment by syrifgit** [comment] 2024-09-08 06:07
Confirming this is fixed in the current release version, just tested.

**Closed as completed by syrifgit** 2024-09-08 06:07 UTC
Labels: 📈 recommendations, retail
