### ISSUE TITLE
Evoker Pyre Priority bug/issue maybe?

### ISSUE THREAD

**Issue by mightymist3ry** [Hekili/hekili#1988] opened 2022-11-18 15:38 UTC
![evoker1](https://user-images.githubusercontent.com/46112381/202744516-c817e1de-e8cc-4aa0-87e1-c91275d22bc4.png)

### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

Im noticing pyre stacks overcap and other abillities will recommend use such as Shattering star followed by another azure strike then into pyre. i also notice when insta free cast avalible its not recommending pyre asap either, i was told if the ability pyre is free (procced) its good to use fast on aoe regardless of stacks. But could be wrong.

Will add some screeshots with some extra detail from a friend who tested aswell. 

![evoker1](https://user-images.githubusercontent.com/46112381/202744516-c817e1de-e8cc-4aa0-87e1-c91275d22bc4.png)
![evoker2](https://user-images.githubusercontent.com/46112381/202742589-e9f249ea-5ee6-4463-87a1-e970a66777ab.png)
![evoker3](https://user-images.githubusercontent.com/46112381/202742599-678a686f-1ff8-4453-84b0-38c0429fc97e.png)

### How to Reproduce

1. Enter game as dev evoker
2. Do AOE rotation on 3+ targets following sequence
3. Watch sequence till pyre overstack (sometimes) or not get used when insta essence on aoe.

### Talent Loadout

BsbBnWR3R1Z1HmbUKIpvm3XXhDIAAAAAAgWIJikQgEJlkkASLgESSAJJSESSC

### Snapshot

https://paste-bin.xyz/967144

**Comment by Hekili** [comment] 2022-11-18 15:47
Thanks for the Snapshot.  Fire Breath, Shattering Star, and Eternity Surge are much higher in priority than Pyre; it looks like Pyre is recommended as soon as they are out of the way in the snapshot you provided.

```
Devastation; Primary - Fire Breath(0.00), Shattering Star(0.82), Eternity Surge(1.74), Pyre(3.18), Pyre(4.40), Azure Strike(5.63), Azure Strike(6.86), Azure Strike(8.09)
```

So far, this makes sense because you'll want to use those ASAP such that their cooldowns can start regenerating sooner.

For reference, the priority list works by recommending the highest item in the list that has its conditions met, that is off cooldown, and that has its required resources available.

* The Fire Breath recommendation is effectively the 20th item in the list.
* The Shattering Star recommendation is the 23rd item in the list.
* The Eternity Surge recommendation is the 26th item in the list.
* The Pyre recommendation is the 30th item in the list.

That means, if all of these items were available at the start and had all their requirements met, these recommendations came out in the correct order.

A snapshot that matches those screenshots would be interesting.  Seeing Azure Strike over Pyre with max stacks definitely sounds wrong.  It's possible that is from an earlier release and has since been fixed, if you're not able to replicate it.

**Comment by mightymist3ry** [comment] 2022-11-18 15:56
> Thanks for the Snapshot. Fire Breath, Shattering Star, and Eternity Surge are much higher in priority than Pyre; it looks like Pyre is recommended as soon as they are out of the way in the snapshot you provided.
> 
> ```
> Devastation; Primary - Fire Breath(0.00), Shattering Star(0.82), Eternity Surge(1.74), Pyre(3.18), Pyre(4.40), Azure Strike(5.63), Azure Strike(6.86), Azure Strike(8.09)
> ```
> 
> So far, this makes sense because you'll want to use those ASAP such that their cooldowns can start regenerating sooner.
> 
> For reference, the priority list works by recommending the highest item in the list that has its conditions met, that is off cooldown, and that has its required resources available.
> 
> * The Fire Breath recommendation is effectively the 20th item in the list.
> * The Shattering Star recommendation is the 23rd item in the list.
> * The Eternity Surge recommendation is the 26th item in the list.
> * The Pyre recommendation is the 30th item in the list.
> 
> That means, if all of these items were available at the start and had all their requirements met, these recommendations came out in the correct order.
> 
> A snapshot that matches those screenshots would be interesting. Seeing Azure Strike over Pyre with max stacks definitely sounds wrong. It's possible that is from an earlier release and has since been fixed, if you're not able to replicate it.

He was using the same version as i was this test was about 2 hours ago in the screenshots above, im not sure i can get a snapshot of that at this time unelss i recreated the issue exactly. i think the event is rare but happens sometimes

**Comment by W8ink** [comment] 2022-11-18 16:50
this is due to a problem with Essence regeneration

**Comment by Hekili** [comment] 2022-11-18 16:51
> this is due to a problem with Essence regeneration

No, that is not settled.  There is an issue related to Essence regen as well that I'm testing a fix for, but that logic does not necessarily impact this at all.

edit:  I do see how it *can* be that; since Azure Strike has a higher priority entry when capping Essence isn't imminent.  I want data to confirm, though.

**Comment by Pulseonline** [comment] 2022-11-18 23:50
https://pastebin.com/347myDiy  - Think this is the best one.  I was at 20 stacks on Pyre, no essence burst.  Had 3 essences, I have 5 icons shown, it showed Azure strike x3, then shattering star, THEN Pyre.  So 5 actions later when I had 20 stacks of charged blast on pyre and 3 essence.  This was a 3 target count on Automatic on dummies.  I took 2 other snapshots though as well.

https://pastebin.com/RbXGYeB3

https://pastebin.com/1p3YbDMJ

**Comment by Pulseonline** [comment] 2022-11-18 23:54
Basically on 3 target count it should be 10 stack of charged blast, it should be recommending Pyre almost immediately, even before Fire Breath and Eternity Blast as this is AOE and packs die to fast.  At 4 target count it should be recommending Pyre ALL the time as long as we have the essence for it, doesn't matter the charged blast stacks at all.  At 4 targets its worth spending the essences on Pyre without any stacks.

**Comment by Ble43** [comment] 2022-11-19 00:47
I've been noticing the lack of prioritization for Pyre with charged blast too, thank you so much for posting this! There is tons of overcapping going on.

**Comment by Ble43** [comment] 2022-11-19 01:49
I think this logic may not be working correctly right now.
![image](https://user-images.githubusercontent.com/92388362/202828569-07346370-8262-484e-9f78-4b6651a46b4b.png)
https://www.wowhead.com/guide/classes/evoker/devastation/rotation-cooldowns-pve-dps

**Comment by Hekili** [comment] 2022-11-19 16:11
This has the same root cause as #1980 so I'm closing as a duplicate.  The next release will include a fix.

**Closed as completed by Hekili** 2022-11-19 16:11 UTC
Labels: duplicate, 📈 recommendations, 🧑‍⚕️ triage

**Comment by mightymist3ry** [comment] 2022-11-19 17:13
excitement!

**Comment by mightymist3ry** [comment] 2022-11-19 17:13
> This has the same root cause as #1980 so I'm closing as a duplicate. The next release will include a fix.

Excitement!

**Comment by Ble43** [comment] 2022-11-19 19:02
Thanks Hekili!

**Comment by mightymist3ry** [comment] 2022-11-21 02:20
Was doing a dungeon today and while i notice pyre is recommended more sense latest update. I did see today that me having my aoe targets set to 3 and while attacking 3 targets i am recommended to use Disintegrate vs pyre in one of the snapshots, then in the other i was fighting 4+ targets and essence came up and im recommended to do 4 more azure strikes and by that time the mob would have been down. I see alot of evokers just launching pyre so much in aoe 3+ compared to me while following hekili. Also if i set hekili to AOE vs Auto it never shows Disintegrate in it. So maybe something is up with the auto mode to? im unsure. Hopefully this data helps!

https://paste-bin.xyz/967404

https://paste-bin.xyz/967405

**Comment by mightymist3ry** [comment] 2022-11-21 02:21
> This has the same root cause as #1980 so I'm closing as a duplicate. The next release will include a fix.

Was doing a dungeon today and while i notice pyre is recommended more sense latest update. I did see today that me having my aoe targets set to 3 and while attacking 3 targets i am recommended to use Disintegrate vs pyre in one of the snapshots, then in the other i was fighting 4+ targets and essence came up and im recommended to do 4 more azure strikes and by that time the mob would have been down. I see alot of evokers just launching pyre so much in aoe 3+ compared to me while following hekili. Also if i set hekili to AOE vs Auto it never shows Disintegrate in it. So maybe something is up with the auto mode to? im unsure. Hopefully this data helps!

https://paste-bin.xyz/967404

https://paste-bin.xyz/967405

**Comment by Hekili** [comment] 2022-11-21 05:08
With Scintillation and Eternity's Span, you use Disintegrate at up to 3 targets.

The priority will probably continue to change, but this is what is available at the moment.  You can customize your priority if you want it to do different things.

**Comment by mightymist3ry** [comment] 2022-11-21 05:35
> With Scintillation and Eternity's Span, you use Disintegrate at up to 3 targets.

Is that cause of my talent setup?

**Comment by mightymist3ry** [comment] 2022-11-21 06:50
> With Scintillation and Eternity's Span, you use Disintegrate at up to 3 targets.
> 
> The priority will probably continue to change, but this is what is available at the moment. You can customize your priority if you want it to do different things.

I was told if Volatility talent is used then Pyre is much better on 3 target.
