### ISSUE TITLE
DH issue when starting fight

### ISSUE THREAD

**Issue by Zifrost** [Hekili/hekili#3476] opened 2024-08-12 13:00 UTC
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

When I enter combat I get this msg, never had this before yesterday

### How to Reproduce

Dunno, for me is just entering combat

### Snapshot (Link)

https://pastebin.com/FPRPHcDU

### Contact Information

Discord: zifrost

**Comment by Hekili** [comment] 2024-08-12 13:32
Hi, thanks for providing this snapshot.  It looks like the issue is that the `opener` Felblade usage has a `line_cd` of 60 seconds (to ensure it is only used once) and other Felblade entries are used later in the fight.  I will revise so that the `line_cd` doesn't apply when Felblade was used in a previous fight.

**Comment by Hekili** [comment] 2024-08-15 03:47
This should be resolved in v11.0.2-1.0.0.

**Closed as completed by Hekili** 2024-08-15 03:47 UTC
Labels: 📈 recommendations, 🧑‍⚕️ triage
