### ISSUE TITLE
[REC] Havoc: Inertia Trigger, Variables, Filler

### ISSUE THREAD

**Issue by sK4r4** [Hekili/hekili#3728] opened 2024-09-11 13:04 UTC
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

DH - Havoc

### Describe the Issue

The last update seems to have broken the rota again, leeding to no recommendations or recommendations that have a long cooldown

### How to Reproduce

cant describe exactly, just happens from time to time

### Snapshot (Link)

https://pastebin.com/RzbSwPb3

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/3czEnw2nwA2UwXGnh7Y9aj

### Contact Information

Skara#2856

**Comment by stev1bp** [comment] 2024-09-11 17:50
Also having the same issues. I may go a whole fight and it never suggests meta. It seems to just hardly ever recommend meta. In raid last night I was almost a min into a boss fight before I just gave up an cast meta anyway.

Current talents: CEkAEDLOxe3SEPP2R8Hw6bhoSYGMzMzgZmZMmJmZGAAAAAAwsMmxMMGLzMz2sNLjZGmZBLbwysYGDzmmGMzMzgN

**Comment by sudoalias** [comment] 2024-09-11 23:14
I also experienced this last night.  The fight in particular when I noticed it was The Silken Court.  Unfortunately, I also didn't remember to pause Hekili and grab a snapshot mid-fight.

**Comment by Hekili** [comment] 2024-09-11 23:17
Testfix will go into 1.0.12; some Demon Blades resource prediction is added and may resolve this at low Fury.

**Comment by Jacky7533** [comment] 2024-09-12 17:02
Currently, it doesn't reconemnd on using the mini burst combo of Vengenful Retreat + Eyebeam + Essence Break + Blade Dance even though they're not on CD and you have enough Fury for them.

https://pastebin.com/pfNDmY3G

Sometimes it is not reconmending Empowered Fel Rush during rotation while the buff Unbound Chaos is on, even though it's up.

https://pastebin.com/ntaCVfvd

During Opener, and from time to time, it is not reconmending me to use Vengenful Retreat + Meta even though that's the stable rotation

https://pastebin.com/Lk3nXSD5

And lastly
When I am low on Fury, for example under 90, it is not reconmending me Sigil of Flame even though it's not on CD
When I am low on Fury, for eample under 80, it is not reconmending me Felblade even though it's not on CD
It also doesn't reconmend Throw Glaive if I have no other available buttons to use.

**Comment by Hekili** [comment] 2024-09-12 18:25
@Jacky7533 Thanks for providing snapshots.  Can you add context to each?

> Currently, it doesn't reconemnd on using the mini burst combo of Vengenful Retreat + Eyebeam + Essence Break + Blade Dance even though they're not on CD and you have enough Fury for them.
> [pastebin.com/pfNDmY3G](https://pastebin.com/pfNDmY3G):
* Is it correct that you're expecting Vengeful Retreat (to start mini burst) at the time this snapshot was taken?  If so, Vengeful Retreat was ruled out here in `default - 17` because with Student of Suffering talented, Sigil of Flame must be on CD.  Sigil of Flame wasn't recommended/used because "Inertia Trigger" wasn't active, which is a new addition to the priority and is a virtual buff for determining if you can trigger Inertia, so this is *probably* the root cause here. 

> Sometimes it is not reconmending Empowered Fel Rush during rotation while the buff Unbound Chaos is on, even though it's up.
> [pastebin.com/ntaCVfvd](https://pastebin.com/ntaCVfvd):
* Fel Rush was ruled out in `default - 4` because that requires Unbound Chaos to be near expiration.
* `opener` list entries didn't fire because we're more than 15 seconds into combat.
* `default - 16` ruled out because Unbound Chaos will be up for several seconds after Eye Beam comes off CD (in 0.68 seconds).  There is an opportunity here to revise my recheck (timing) functionality so that it would successfully time the usage of Fel Rush in 6.17 seconds.
* `default - 20` ruled out because Blade Dance is on CD for 6.31 seconds, Eye Beam's CD is less than 5 seconds, and Immolation Aura isn't ready.
* `default - 21` ruled out because Momentum is not talented.
* My takeaway here is that the new variables in the priority need to be reviewed (by me).

> During Opener, and from time to time, it is not reconmending me to use Vengenful Retreat + Meta even though that's the stable rotation
> [pastebin.com/Lk3nXSD5](https://pastebin.com/Lk3nXSD5)
* Your snapshot is recommending Vengeful Retreat, so I assume you're wanting to see why Metamorphosis isn't recommended after Vengeful Retreat.
* `cooldown - 1` ruled out *mainly* because that entry is for non Inertia builds.
* `cooldown - 2` ruled out because Blade Dance is not on cooldown and we're not 15 seconds into the fight.
* `opener - 22` ruled out because Essence Break is down and Blade Dance isn't on CD.
* `opener - 23` also ruled out because Blade Dance isn't on CD (among other things).
* That leads to Blade Dance being selected, so let's look at why Metamorphosis isn't recommended after that.
* `cooldown - 2` ruled out because we're still not 15 seconds into the fight.
* Essence Break is still down so `opener - 22 & 23` still will not pass.  So why is Essence Break not recommended?
* `opener - 21` ruled out because Blade Rhapsody is down, you're Felscarred, and Metamorphosis isn't active (from Eye Beam).
* `opener - 28` ruled out because Blade Dance *isn't* coming off CD in 1 second and you're Felscarred and Metamorphosis is down.
* `opener - 29` ruled out because you don't have Restless Hunter talented.
* I think I need to see a sim of your character for comparison to see if the sim is also having issues with your build; I will also check if there are Havoc APL changes that have been missed to account for these scenarios.

> When I am low on Fury, for example under 90, it is not reconmending me Sigil of Flame even though it's not on CD
* Snapshot needed.

> When I am low on Fury, for eample under 80, it is not reconmending me Felblade even though it's not on CD
* Snapshot needed.

> It also doesn't reconmend Throw Glaive if I have no other available buttons to use.
* Snapshot needed.

**Comment by Jacky7533** [comment] 2024-09-12 20:17
> * Is it correct that you're expecting Vengeful Retreat (to start mini burst) at the time this snapshot was taken?  If so, Vengeful Retreat was ruled out here in `default - 17` because with Student of Suffering talented, Sigil of Flame must be on CD.  Sigil of Flame wasn't recommended/used because "Inertia Trigger" wasn't active, which is a new addition to the priority and is a virtual buff for determining if you can trigger Inertia, so this is _probably_ the root cause here.
> 

Yeah, you'd want to VR before the start of Eyebeam > Essence Break > Blade dance, as VR lines up with Essence break, you'd be able to do essentially another VR  for intertia/unbound chaos buff for fel rush, and then just in time for VR with another Essence break.

> * Your snapshot is recommending Vengeful Retreat, so I assume you're wanting to see why Metamorphosis isn't recommended after Vengeful Retreat.

I wasn't able to get the snapshot quick enough. Before it was just reconmending me Metamorphosis, instead of VR. But in that Opening Sense, you'd want to VR and Meta right after.

> * I think I need to see a sim of your character for comparison to see if the sim is also having issues with your build; I will also check if there are Havoc APL changes that have been missed to account for these scenarios.

Here's my current sim.

https://www.raidbots.com/simbot/report/6U2KDo1oVQpqJEZVK4yEF4

and SimC

https://pastebin.com/yaZvE5Tb

> 
> > When I am low on Fury, for example under 90, it is not reconmending me Sigil of Flame even though it's not on CD
> 
> * Snapshot needed.
> 
> > When I am low on Fury, for eample under 80, it is not reconmending me Felblade even though it's not on CD
> 
> * Snapshot needed.
> 

I think I got it correctly for under80/90 fury while it's not reconmending me Sigil nor Felblade.

https://pastebin.com/XZWazhkZ

> > It also doesn't reconmend Throw Glaive if I have no other available buttons to use.
> 
> * Snapshot needed.

I thnk I got the snapshot correctly for this one as well, I was low on Fury with everything on CD it wasn't reconmending me throw glaive.

https://pastebin.com/URCvBhYn

**Comment by sudoalias** [comment] 2024-09-13 01:14
Another issue that may be affecting the recommendation of Metamorphosis is that Hekili is currently displaying a value of 150 for cooldown.metamorphosis.remains when the ability is completely off CD.  Several places cooldown.metamorphosis.remains is used to represent the ability being ON cooldown, but because it is reading as 150 when off CD, it is being treated as ON cd when it isn't.  Additionally, it does not update the value when you do put Meta on CD.

Snapshot just idle with a targeting dummy selected:
https://pastebin.com/zKA2N2SG

Screenshot showing both the variable readout in Hekili, as well my bars in game showing it is off CD.:
https://imgur.com/a/s2tqOgW

**Comment by chevyn11** [comment] 2024-09-13 01:37
you have cooldowns toggled off, the way hekili treats this is to set everything on the cooldowns toggle to their max cooldown time to signify theyre unavailable.
```
toggles: cooldowns = false 
```

Not saying this is a fix, just answering why youre seeing cooldown.metamorphosis.remains as 150.

Whats more interesting in your snapshot is all the warnings like: 
```
warnings: [#1] Returned unknown string 'renewable' in state metatable [Vengeance (2):fiery_demise:2].
[string "@Interface/AddOns/Hekili/State.lua"]:2396: in function <Interface/AddOns/Hekili/State.lua:2023>
[string "return renewable"]:1: in main chunk
[string "=[C]"]: in function `pcall'
[string "@Interface/AddOns/Hekili/Scripts.lua"]:968: in function `EmulateSyntax'
[string "@Interface/AddOns/Hekili/Scripts.lua"]:1307: in function <Interface/AddOns/Hekili/Scripts.lua:1298>
[string "@Interface/AddOns/Hekili/Scripts.lua"]:1646: in function `LoadScripts'
[string "@Interface/AddOns/Hekili/Scripts.lua"]:1757: in function `LoadScripts'
[string "@Interface/AddOns/Hekili/Core.lua"]:1466: in function <Interface/AddOns/Hekili/Core.lua:1464>
```

**Comment by Hekili** [comment] 2024-09-13 06:43
Major overhaul of Demonsurge in 1.0.13; should be some notable improvements.

**Comment by Jacky7533** [comment] 2024-09-13 20:05
> Major overhaul of Demonsurge in 1.0.13; should be some notable improvements.

This broke more stuff since the change.

this is my talents
CEkAEDLOxe3SEPP2R8Hw6bhoSYGMzMzgZmZMzMhZGAAAAAAwsNMmZMGLzMz2sNLjZGmZBLbwysYGDzmmGMzMGsB

this is my simC
https://pastebin.com/0mXHdqJX

during opener of DH, after going Meta and doing the first Annhilation, it does not reconmend using Sigil of Flame/Sigil of Doom.

this is the snapshot
https://pastebin.com/VwvX8UmN

During the duration of Meta, it never once suggested to use Sigil of Flame/Sigil of Doom.

this is the snapshot
https://pastebin.com/vDn8FdMb

during the time I was doing single target target dummy, it failed to reconemnd me anything and did an auto snapshot.

this is the snapshot
https://pastebin.com/yEPjyNB8

**Comment by Hekili** [comment] 2024-09-13 21:01
> during opener of DH, after going Meta and doing the first Annhilation, it does not reconmend using Sigil of Flame/Sigil of Doom.
> this is the snapshot
> [pastebin.com/VwvX8UmN](https://pastebin.com/VwvX8UmN)

Your snapshot is recommending Sigil of Doom:
`Havoc; Primary - Sigil of Doom(0.00), Abyssal Gaze(1.00), Death Sweep(2.33), Essence Break(3.33)`

> During the duration of Meta, it never once suggested to use Sigil of Flame/Sigil of Doom.
> this is the snapshot
> [pastebin.com/vDn8FdMb](https://pastebin.com/vDn8FdMb)

Sigil of Doom is on CD for 9+ seconds.

> during the time I was doing single target target dummy, it failed to reconemnd me anything and did an auto snapshot.
> this is the snapshot
> [pastebin.com/yEPjyNB8](https://pastebin.com/yEPjyNB8)

That would not be the auto-snapshot for a failed recommendation:
`Havoc; Primary - Immolation Aura(1.34), Felblade(2.34), Chaos Strike(3.34), Vengeful Retreat(4.15)`

**Comment by Jacky7533** [comment] 2024-09-14 04:10
> > during opener of DH, after going Meta and doing the first Annhilation, it does not reconmend using Sigil of Flame/Sigil of Doom.
> > this is the snapshot
> > [pastebin.com/VwvX8UmN](https://pastebin.com/VwvX8UmN)
> 
> Your snapshot is recommending Sigil of Doom: `Havoc; Primary - Sigil of Doom(0.00), Abyssal Gaze(1.00), Death Sweep(2.33), Essence Break(3.33)`
> 
> > During the duration of Meta, it never once suggested to use Sigil of Flame/Sigil of Doom.
> > this is the snapshot
> > [pastebin.com/vDn8FdMb](https://pastebin.com/vDn8FdMb)
> 
> Sigil of Doom is on CD for 9+ seconds.
> 
> > during the time I was doing single target target dummy, it failed to reconemnd me anything and did an auto snapshot.
> > this is the snapshot
> > [pastebin.com/yEPjyNB8](https://pastebin.com/yEPjyNB8)
> 
> That would not be the auto-snapshot for a failed recommendation: `Havoc; Primary - Immolation Aura(1.34), Felblade(2.34), Chaos Strike(3.34), Vengeful Retreat(4.15)`

i just got it again just now

https://pastebin.com/uY0CZrjb
https://pastebin.com/utYKtwrD

not sure if i did it right.

**Comment by Hekili** [comment] 2024-09-16 00:49
> i just got it again just now

The last one looks informative.

* Chaos Strike would've been recommended at 80+ Fury or if Eye Beam were on CD.
* Eye Beam would've been recommended if Vengeful Retreat were on CD.
* Vengeful Retreat would've been recommended if Sigil of Flame were on CD.
* Sigil of Flame would've been recommended if Unbound Chaos were active (from Immolation Aura).
* Immolation Aura would've been recommended in 13 seconds.

The two underlying issues here are:

* Fury generation timing is a little wonky; the addon did a recheck at 80 Fury but the condition is actually `> 80`, so I need to adjust for that.
* The priority could probably use a "fall-through" condition for Sigil of Flame if Immolation Aura is going to be on CD for a while.

I'll address the first issue now and see if I end up needing to make adjustments for the second.  The risk with the second case is that Unbound Chaos and Inertia stay desynced and we don't want that.

**Comment by Hekili** [comment] 2024-09-16 00:56
These changes will be in 1.0.14; if there are additional issues, please create a new ticket since there are mechanical and priority changes in 1.0.14.

**Closed as completed by Hekili** 2024-09-16 00:56 UTC
Labels: 📈 recommendations, 🧑‍⚕️ triage
