### ISSUE TITLE
Blood DK Priority Issue: Recommending Tombstone before Death and decay with Shattering Bone talented. 

### ISSUE THREAD

**Issue by gnew95** [Hekili/hekili#2003] opened 2022-11-20 20:34 UTC
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### WoW Version

Retail (Dragonflight)

### Describe the Issue

Tombstone consumes 5 bone shards to give a shield, however it also acts as an offensive cooldown with Shattering Bone talented. Shattering bone's damage is greatly enhanced when you are inside Death and decay, however the priority helper often recommends casting death and decay after tombstone. I have also tested that this seems to occur when there are no Death and Decays active elsewhere as well.

### How to Reproduce

1. Enter Game as Blood DK
2. Talent into Tombstone and Shattering Bone
3. See that the priority helper will often recommend casting Tombstone before Death and Decay
5. Thank you as always for your incredibly hard work!
6. Example image:

![Example picture](https://user-images.githubusercontent.com/101494776/202924477-fcb21788-3c2c-4d9d-92b3-a9b305b1a776.png)

### Talent Loadout

BoPAdLUHklrTr3hBIcYWdbnCGDCJBhk4ASLASSiEJQSSkAAAAAAISCEJNhIBAAESSEAAAA

### Snapshot

https://pastebin.com/et7uj2Bk

**Comment by Hekili** [comment] 2022-11-20 20:49
If you are presenting multiple issues or scenarios, please provide a snapshot for each and label them accordingly.  Thanks!

**Comment by gnew95** [comment] 2022-11-20 20:49
Sorry will do! This particular snapshot is for the tombstone issue.

**Comment by Hekili** [comment] 2022-11-22 03:20
The root cause here looks the same as the other ticket; closing.

**Closed as completed by Hekili** 2022-11-22 03:20 UTC
Labels: 📈 recommendations, 🧑‍⚕️ triage
