### ISSUE TITLE
[REC] Hekili Not Recommending Key Abilities for Warrior Protection

### ISSUE THREAD

**Issue by SerhatSoruklu** [Hekili/hekili#3850] opened 2024-09-24 12:09 UTC
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Spec

Warrior - Protection

### Describe the Issue

For my Warrior Protection spec, the Hekili addon is not recommending several key abilities during combat. It only seems to focus on Ignore Pain, Shield Block, Revenge, and a few others, but it is consistently neglecting important abilities such as:

Rallying Cry
Shield Wall
Whirlwind Action Button
Rend
Slam
Impending Victory (even when my health is low)
This is affecting my ability to execute a proper rotation, as it does not guide me to use the full range of my toolkit. Additionally, it is not recommending my DPS trinket at all.

I would like to know how I can adjust the settings so that it incorporates these abilities and the use of my DPS trinket into the rotation recommendations.

### How to Reproduce

How to Reproduce:
Play as a Protection Warrior.
Set up the Hekili addon with default settings.
Enter combat and observe that abilities like Rallying Cry, Shield Wall, Whirlwind, Rend, Slam, and Impending Victory are not being recommended.
Try to use the DPS trinket, but notice it is not being suggested by the addon.

### Snapshot (Link)

https://pastebin.com/Uy8CvAG0

### Raidbots Sim Report (Link)

https://www.raidbots.com/simbot/report/ghRwkwavUSH2TvhbWSWaKL

### Additional Information

As you can see from the snap shot its only recommending thunder, ignore pain, shield block and a couple others

### Contact Information

Discord: Coupyn

**Comment by Spike2D** [comment] 2024-09-24 12:19
Duplicate of #3830 
Pull fix already submitted.
Rend, Slam and Whirlwind are not recommended on purpose, we don't and shouldn't actively use those skills for our rotation.

What DPS trinket you're using?

**Comment by SerhatSoruklu** [comment] 2024-09-24 12:21
Ahh right I see. Pull fix already submitted when will the addon update for these fixes cause I updated just now and restarted wow, still nothing.

Also Im using this trinket: 
https://www.wowhead.com/item=219915/foul-behemoths-chelicera

**Comment by Spike2D** [comment] 2024-09-24 12:22
@Hekili will need to review and merge it, so it's not live yet.

The pull also fixes Foul Behemoths trinket mismatched ID.

**Comment by Hekili** [comment] 2024-09-24 17:51
Will be fixed in next release.  Thanks for the PR.

**Closed as completed by Hekili** 2024-09-24 17:51 UTC
Labels: 📈 recommendations, retail, 🙏 pr pending, 🔝 escalated
