### ISSUE TITLE
[BUG] Scale Commander Evoker - Deep Breath appearing on rotation while on CD

### ISSUE THREAD

**Issue by CHogan0973** [Hekili/hekili#3523] opened 2024-08-23 21:40 UTC
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

On Devastation Evoker, Deep Breath is being prioritized when on cooldown.  It will continue to show up and force it's way into the top prio when it's on cd

<img width="843" alt="DeepBreath" src="https://github.com/user-attachments/assets/690da026-24a6-4f34-b4c7-973a7beed303">

### How to Reproduce

1. Enter game as Devastation Evoker
2. Be Max Level Maneuverability talented - Optional talents include Lay Waste/Onyx Legacy
3. Be ScaleCommander spec with 
4. Go to a target dummy and follow the rotation for either ST/AOE/Auto

### Player Information (Link)

No snapshots were able to be generated, I provided a picture in the description

### Error Messages (Link)

No errors

### Additional Information

This is only affecting ScaleCommander specced Evokers.

### Contact Information

CHogan73

**Comment by MatteoLombardi** [comment] 2024-08-24 00:38
Duplicate of #3450

**Closed as not planned** 2024-08-26 03:17 UTC
Labels: 🐛 Bug, 🧑‍⚕️ triage
