### ISSUE TITLE
[DF] Warlock Affliction, sometimes, Unstable Affliction is not in the rotation anymore.

### ISSUE THREAD

**Issue by KNP54** [Hekili/hekili#2464] opened 2023-03-09 15:38 UTC
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

It seems that after a certain amount of time, Unstable Affliction isn't recommened anymore as a spell.. /reload fixes it, but the bug comes back after doing several fights.

### How to Reproduce

1. Enter the game as an Affliction Warlock
2. Play normally until the spell Unstable Affliction isn't in the Hekili rotation anymore

### Snapshot (Link)

https://pastebin.com/Y7iF48sY

### Contact Information

Picoglad#7304 (discord)

**Comment by Hekili** [comment] 2023-03-09 15:53
In this snapshot, the addon is aware of a UA debuff applied to another target.  Is that inaccurate?  Was there no other target with UA applied?

**Comment by KNP54** [comment] 2023-03-09 16:14
When I did the snapshot, I was out of combat for several minutes. And I did the snapshot out of combat also.

**Comment by KNP54** [comment] 2023-03-09 17:21
It's quite hard to reproduce.... it may take hours of gameplay to trigger the bug, but once it's triggered, the bug stays until a /reload is executed. I don't know what triggers the bug yet.

**Comment by Hekili** [comment] 2023-03-09 17:42
I'm pretty sure it's related to recent changes to the "auditor" that looks to see that target and DOT information is still current.  I can resume having them purge after exiting combat, but I'm concerned about cases where it might occur while you are still in combat.

**Comment by KNP54** [comment] 2023-03-09 17:52
_One thing I noticed, when the bug occured this morning, I wasn't able to use items in my bags. When I use an item in my bags (ie heartstone) I get this LUA error:

4x [ADDON_ACTION_FORBIDDEN] AddOn 'Altoholic' tried to call the protected function 'UNKNOWN()'.
[string "@!BugGrabber/BugGrabber.lua"]:480: in function <!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: ?
[string "=[C]"]: in function `UseContainerItem'
[string "@FrameXML/ContainerFrame.lua"]:1402: in function <FrameXML/ContainerFrame.lua:1311>
[string "=[C]"]: in function `ContainerFrameItemButton_OnClick'
[string "@FrameXML/ContainerFrame.lua"]:1454: in function <FrameXML/ContainerFrame.lua:1441>

it says Altoholic, but it's never the same addon when this bug occurs (i've seen ElvUI, Auctionator, BTWQuests, PetTracker, etc)
I'm not sure if it's related somehow._

Edit: OK it's not related... Tonight we did prog on Sennarth mythic and every 2 or 3 pulls, the UA bug appeared and had to /reload every time. Item in bags where working all the time.

**Comment by dicarlo2** [comment] 2023-03-10 08:19
I think this is related to https://github.com/Hekili/hekili/issues/2461. I noticed that active_dot.flame_shock would get stuck at 5, even after the dots had fallen off. /reload would solve the issue.

**Comment by Hekili** [comment] 2023-03-13 21:01
Duplicate of #2461 (same underlying cause).  Should be addressed in latest release (1.0.23 and later).

**Closed as completed by Hekili** 2023-03-13 21:01 UTC
Labels: 🧑‍⚕️ triage, retail
