### ISSUE TITLE
[BUG] Prot Warrior 10.2 4Pv Tier Not working.

### ISSUE THREAD

**Issue by Ktthemage** [Hekili/hekili#3005] opened 2023-11-23 22:26 UTC
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for this issue and was not able to find one.
- [X] I edited the title of this bug report (above) so that it describes the issue I am reporting.

### Describe the Issue

Hey all, First time posting here.  I was playing my Protection Warrior today on Patch 10.2.0 and recently picked up 4Pc Tier from Amirdrassil.  Once I did this Hekili stopped working, the Add-on will show but it will not progress through the rotation, the add-on Freezes after using the first ability and tried to catch up randomly as you are in combat.  I have tried the add-on on 3 other classes I have (Frost Mage, Prot Paladin, Vengeance Demon hunter) and this issue does not effect them.  I have fully deleted all cache and add-on files and tried a fresh install as well.  I have tried disabling every add-on but Hekili and it still persists.  I believe this has to do with a recent update that went out any information would be appreciated.

### How to Reproduce

Enter Game as warrior 
Equip 4pc Tier
Enter combat
addon breaks. 

### Player Information (Link)

https://pastebin.com/SHktP6zy

### Error Messages (Link)

n/a

### Contact Information

Lucid_luck  Lucid#1762 bnet

**Comment by vetalgn** [comment] 2023-11-23 22:56
i have same issues with my arms warrior(but i dont think its depent of  4set). when i press first abbility rotation stop working(frezzes) and if i loze target(just press ESC) i can see next ability recomendation

**Comment by Str8Garbage** [comment] 2023-11-23 22:56
I can confirm its also doing the same for each spec and i dont have any tier gear.

**Comment by vetalgn** [comment] 2023-11-23 23:00
one more observation, changing abilities works correctly if I press them outside of combat. but as soon as I enter the battle everything freezes

**Comment by Warmason** [comment] 2023-11-23 23:01
My warrior is broken in all specs and I only have 1 of the new set pieces. Was working fine yesterday. I even tried going to older version and it is still broken.

**Comment by vetalgn** [comment] 2023-11-23 23:07
and one more observation, if you move a little distance from the target, then the abilities change, but as soon as you approach and press any ability, everything breaks

**Comment by Warmason** [comment] 2023-11-23 23:08
> and one more observation, if you move a little distance from the target, then the abilities change, but as soon as you approach and press any ability, everything breaks

I can confirm this as well.

**Comment by Vennort** [comment] 2023-11-24 01:28
Having the same issue since last night. Playing prot warrior

**Comment by psychopyc** [comment] 2023-11-24 01:28
For me Fury rotation stil working, protection is broken as described in original message.
Not depended of the set equipped

**Comment by Hekili** [comment] 2023-11-24 03:38
Fixed in 1.0.7 (with another modification to LibRangeCheck).

**Closed as completed by Hekili** 2023-11-24 03:38 UTC
Labels: 🐛 Bug, 🧑‍⚕️ triage
