### ISSUE TITLE
Game stutters when leaving combat.

### ISSUE THREAD

**Issue by Zankom** [Hekili/hekili#82] opened 2019-03-13 10:22 UTC
Ever since patch 8.1.5, every time i kill a mob, the game freezes for a split-second. ive disabled all my addons and singled out Hekili. it seems like it stutters when i leave combat.

**Comment by Hekili** [comment] 2019-03-13 13:12
I'll look into it, but I'm definitely not experiencing this myself.  Do you notice a difference in packs of enemies vs. single enemies?

If you go to /hekili > [your specialization] and scroll down to Performance, do you have this issue with Throttle Updates checked and Maximum Update Frequency set at 10 or higher?

**Comment by Tinyta** [comment] 2019-03-13 16:49
I'm having the same issue since the patch. There is no difference between packs of enemies vs. single enemies, it seems to happen every time you drop combat regardless.

I tried checking Throttle Updates and set it to 10 or higher and it didn't make any difference.

**Comment by Caelwn** [comment] 2019-03-13 18:35
I'm also seeing this problem since the patch - The game freezes for a brief period (under a second) when combat ends, so in a pack situation it doesn't happen until the final enemy is dead.

I've also seen it happen once or twice at the start of combat, with the longest pause being about 4 seconds. Just saw it when the UI first appeared when I landed after a flight as well.

I've tried the Max Frequency and that doesn't appear to make a difference. I've also shifted between the DX12 and DX11 graphics modes in case that caused it and that doesn't seem to help either. I also tried turning off all other mods and that doesn't seem to help either.

Quick update: Also just found that it's specifically combat state _ending_ that triggers it. Killed the last mob but was still in combat due to an effect, with no other enemies around, and as soon as the combat state ended the game froze for just under a second.

**Comment by Hekili** [comment] 2019-03-13 18:54
Thanks, this is helpful information.

What classes/specs are you all playing?  I can't replicate this on my Druid.

There are only a few functions that fire upon leaving combat:
1.  Gear is rechecked (to be excessively thorough).
2.  Combat time and weapon swings are reset.
3.  Display visibility is rechecked and recalculated.
4.  Time to die calculations are purged.

None of those involve particularly complex logic.  But I'll keep exploring.

**Comment by Caelwn** [comment] 2019-03-13 19:02
I'm playing Demon Hunter, Havoc.

One other thing (and I just posted this to the official forum too) - I reckon this might relate to some of the changes they made to overlay window rendering (thought I saw something in their notes about it).

I have also seen a very brief stutter when I'm on a flight path with the map open and I click/right click to change zones a lot. If it relates to overlay windows updating perhaps something the addon is doing with an update at the start/end of combat is similar to a map interaction and causing a pause?

**Comment by Hekili** [comment] 2019-03-13 19:28
Got a link re: overlay window rendering?

**Comment by Hekili** [comment] 2019-03-13 19:37
Updated the title here.  I need more info about people's addon settings and/or game settings to see if there's an interaction here that I can't identify.

**Comment by Tinyta** [comment] 2019-03-13 19:45
I'm also playing havoc demon hunter. Video settings on 5 (preset). Directx11 (not legacy) and on Windows 7. A friend of mine is not having any issues on Windows 10 so it could be something there...

This is what I saw posted from Blizzard, not sure if it's relevant: 

"In 8.1.5, we are making some improvements to how World of Warcraft uses DirectX. In essence, our old DirectX 11 is now called DirectX 11 Legacy, and our new DirectX 11 is multi-threaded. More details on each DirectX version is below:

DirectX 11 Legacy
A single-threaded rendering backend. This is provided to be the most compatible with older hardware, operating systems, and drivers. This is also the least performant. This is very similar to the functionality of DirectX 11 in 8.0.1.

DirectX 11
A new multi-threaded rendering backend using DirectX 11. This should improve performance for older GPUs or operating systems that don’t support DirectX 12. This is new for 8.1.5.

DirectX 12
A multi-threaded rendering backend using DirectX 12 for hardware, drivers, and operating systems that support it. There are some performance improvements in 8.1.5, but it is mainly the same as the 8.1.0 release."

**Comment by Hekili** [comment] 2019-03-13 19:46
Please try the v8.1.5-beta2 when it appears under Releases.  I may have found a redundancy to remove re: display visiblity.

**Comment by Hekili** [comment] 2019-03-13 19:46
Do you notice a difference with Max Foreground FPS checked?

![image](https://user-images.githubusercontent.com/9438134/54309780-39051480-45a7-11e9-9b28-a68c849b911a.png)

**Comment by Tinyta** [comment] 2019-03-13 19:52
I had it off but I just tried checking it and setting it to my max 144fps but it's still the same.

Will try the beta asap though.

**Comment by Caelwn** [comment] 2019-03-13 20:01
I'm currently not at my gaming machine so I can't try the beta yet but as for other info:

I reset my profile as part of troubleshooting so the mod is running at default settings (barring the mini map icon being hidden and the attempt at limiting max updates). I hadn't loaded any other profiles before the reset.

I capped my Max Foreground FPS to 60 to match refresh rate when I first saw the problem and hadn't realised what the trigger was.

Will try the beta as soon as I get a chance.

**Comment by Zankom** [comment] 2019-03-13 20:28
I was playing on my mid 70s dk while i first saw this issue, so i went on my 120 warrior to test it out and still the same proboem.

**Comment by Hekili** [comment] 2019-03-13 20:29
Did you update to the beta?  What about the other questions?

**Comment by Zankom** [comment] 2019-03-13 20:31
I cant currently update it because im not at home, but i will see if it improves.

**Comment by Zankom** [comment] 2019-03-13 20:33
Just and fyi, i was doing a quest where you have to shoot down alot of flying enemies on a plane, so the game was stuttering like crazy, and my fps was being reduced from 60 to 48 the whole time. Thats when i started playing around with the addons and found hekili to be causing the problem.

**Comment by Hekili** [comment] 2019-03-13 20:38
Please wait til you've updated to provide answers.

**Comment by domepower** [comment] 2019-03-13 22:15
Hello, I´m having the same issue and updated to beta1 and the game still stutters after leaving combat. But it seems the stutter milisecond is lower.

**Comment by Hekili** [comment] 2019-03-13 22:18
Try beta3.  A video would also be good, since this seems to be frequently reproducible for everyone but myself.

**Comment by domepower** [comment] 2019-03-13 22:33
Just installed beta3 and still happens but like I´ve said it´s a lower milisecond of screen freezing. That´s the main issue. Like if the game is about to crash but it doesn´t. I play a Ret Paladin if that helps.

**Comment by bobbutcher** [comment] 2019-03-13 23:29
I am having the same issue, I just installed beta3 but it still happens, playing Ret Paladin

**Comment by Hekili** [comment] 2019-03-14 01:42
Please review the thread so you can provide helpful information when commenting.

Knowing your processor and graphics settings would be helpful (screenshots!).  A video would also be helpful of this occurring.

Please also confirm if you experienced this before 8.1.5 or with an older version.  If you're still having the issue with 8.1.5-beta3, try reverting to an older version of the addon and let me know which version no longer has the issue.

**Comment by Hekili** [comment] 2019-03-14 01:55
Also, if you are having these spikes, please confirm that you have BugSack/BugGrabber installed and post any bugs it captures.  

I need usable data to fix this -- I am literally not experiencing the same issue on any of my characters.  And please answer the specific questions asked above.

**Comment by Tinyta** [comment] 2019-03-14 02:24
Edit: Video cards SLI

![image](https://user-images.githubusercontent.com/48527231/54327228-265eff80-45e8-11e9-9a23-a72dd03686c0.png)


I had BugSack/BugGrabber installed and they didn't pick up any bugs.

![image](https://user-images.githubusercontent.com/48527231/54326837-ae440a00-45e6-11e9-8203-c1b61377a50c.png)

![image](https://user-images.githubusercontent.com/48527231/54326887-e2b7c600-45e6-11e9-84da-d8b6b1186922.png)

![image](https://user-images.githubusercontent.com/48527231/54326911-f6fbc300-45e6-11e9-834e-a85d753c9ef9.png)



build: v8.1.5-01-beta3
level: 120
class: DEMONHUNTER
spec: havoc

talents: demonic
    demonic_appetite
    fel_eruption
    first_blood
    immolation_aura
    soul_rending
    trail_of_ruin

traits: azerite_empowered=1
    burning_soul=1
    eyes_of_rage=1
    furious_gaze=2
    gutripper=1
    heed_my_call=1
    overwhelming_power=1
    resounding_protection=1
    thirsting_blades=3
    vampiric_speed=1

sets/legendaries/artifacts: none

gear:     flashpowder_hood=1
    raiment_of_the_blighted_tribe=1
    loop_of_pulsing_veins=1
    spark_dampening_footpads=1
    phantom_stalker_shoulders=1
    lustrous_golden_plumage=1
    deathstalkers_bindings=1
    galecallers_boon=1
    bilestained_crawg_tusks=1
    drape_of_the_loyal_vassal=1
    pustule_bearers_pants=1
    unscrupulous_geologists_belt=1
    sharkhide_grips=1
    overseers_lost_seal=1
    heart_of_azeroth=1

**Comment by Hekili** [comment] 2019-03-14 02:25
Thanks!

**Comment by Tinyta** [comment] 2019-03-14 02:29
Also, I tried reverting to many different older versions to check (think I stopped at 8.1.0-14) and still had the split second freeze every time, very weird.

**Comment by Hekili** [comment] 2019-03-14 02:31
So, to confirm your timeline, you didn't start experiencing this stutter/lurch until 8.1.5, and it is still present going back to versions as old as 8.1.0-14?

**Comment by Tinyta** [comment] 2019-03-14 02:33
Exactly that, yep!

**Comment by Caelwn** [comment] 2019-03-14 03:32
Okay, I just started the game and a patch came down. I had installed Hekili-v8.1.5-01-beta3-1-gb5d324e and when I tried a combat I got no hitching when it ended (or when I landed after a flight path).

To double check, I reinstalled Hekili-v8.1.0-25 and did a /reload, then tried again: No hitching.

Unless the /reload didn't fully reset something it looks like the patch may have fixed it. I also notice that I'm not getting hitching when I flick through map screens while flying.

For the sake of data I've included my graphics settings but for me at least it looks like the problem was entirely at the game's end.

![Graphics_1](https://user-images.githubusercontent.com/48530080/54329441-91efae00-4676-11e9-81d1-01dd783f7b4a.jpg)

![Graphics_2](https://user-images.githubusercontent.com/48530080/54329451-974cf880-4676-11e9-99f1-727b12cfb5b9.jpg)

Win10, GTX 1080 Ti.

**Comment by Hekili** [comment] 2019-03-14 03:41
Thanks, yeah, I'm wondering if perhaps an API function or some aggressive garbage collection was left turned on in the public build of the game -- I have a tiny memory leak that *eventually* gets caught by the garbage collector, but perhaps the GC was firing whenever leaving combat.

I'm going to leave this ticket open to see if people are still having problems.  Questions for future responders:

1.  Is it happening every time you exit combat, or only sometimes?
2.  Is it happening when you land at a flight point?
3.  Does it happen in either of those situations with the addon disabled?  With the addon paused?
4.  IF it doesn't happen every time, when does it appear to be more likely to occur?

**Comment by bobbutcher** [comment] 2019-03-14 03:54
I have Hekili-v8.1.5-01-beta3-1-gb5d324e  installed and the problem is still happening even after the game update. Happens whenever I leave combat dosnt happen when landing at a flight point. Still happens when addon is paused.


![WoWScrnShot_031419_145630](https://user-images.githubusercontent.com/48536113/54330354-792ccb80-4669-11e9-994d-f1cda1db8847.jpg)
![WoWScrnShot_031419_145634](https://user-images.githubusercontent.com/48536113/54330355-7a5df880-4669-11e9-9dc3-4f0a1e58d649.jpg)

**Comment by praiseshiva** [comment] 2019-03-14 04:06
Still happening for me - using v8.1.5-01 - no bugs in bug catcher - has only started doing this since WoW's 8.1. 5 update - Ret Paladin - Windows 8.1
1. Happens every time I exit combat
2. It is not happening when landing at a flight path
3. Does not happen when addon is disabled
4. Always happens when exiting combat
![display](https://user-images.githubusercontent.com/48541522/54330474-d847fd00-45e3-11e9-8f2c-eca078590271.jpg)
![advanced](https://user-images.githubusercontent.com/48541522/54330500-f150ae00-45e3-11e9-9b80-7326909ed5e9.jpg)

**Comment by Tinyta** [comment] 2019-03-14 04:26
Yeah, I just tested it with latest beta and it's still happening to me as well. It seems to be affecting people with Windows 7 cause my friend doesn't have this on Windows 10 and the guy above who fixed itself is also W10. Everybody should specify which Windows version they're using to try and rule this out.

1. It happens every time.
2. Does not happen when I land.
3. It doesn't happen with the addon disabled but it *does* happen with the addon paused.
4. Always happen when I drop combat.

**Comment by bobbutcher** [comment] 2019-03-14 04:29
Im on windows 10

intel I7-7700k @4.20
Nvidia GTX 1080

**Comment by praiseshiva** [comment] 2019-03-14 04:56
Windows 8.1 for me

**Comment by Zankom** [comment] 2019-03-14 05:39
Windows 10

**Comment by Zankom** [comment] 2019-03-14 07:18
i installed the latest version, and the stuttering still happens when leaving combat, and now the game seems to stutter at random times. now when im walking around and even fighting mobs it stutters like crazy. so now its not only when leaving combat.

**Comment by meatbag101** [comment] 2019-03-14 09:13
I can confirm with the latest update I have fps drops when something dies/when I loot, up to 30 fps dropped. I have turned off every single addon I use and tested with only Hekili and found out this addon was the reason for my fps drops. I have not tested it on other classes, only Havoc Demon Hunter. Seem to me the latest WoW update has broken this addon, I will try earlier versions(the one released before the new WoW patch) and come back with more info if its better or not.

**Comment by meatbag101** [comment] 2019-03-14 09:16
Allright, so I installed an earlier version and the problem is still there.

**Comment by meatbag101** [comment] 2019-03-14 09:28
**1. Is it happening every time you exit combat, or only sometimes?** Everytime.
**2. Is it happening when you land at a flight point?** No.
**3. Does it happen in either of those situations with the addon disabled? With the addon paused?** It only happens with the addon active/turned on.

**Comment by Cootie76** [comment] 2019-03-14 10:45
Windows 7.0. 
Ret pally.
Happens every time the last mob of a combat dies. Game freezes for about 0.25 sec.
Game freezes when party member kills last mob, and i am in combat but doing nothing.
Game DOES NOT freeze when some random guy kills mob in my vicinity but I am not in combat.
Not freezing when porting/landing/flying fast through zones.

Freezing happens an all available Hekili versions (I checked last 5 i had on my disc).
Freezing started exactly when 8.1.5 went live, didnt happen just the evening before patch.

Lowered Hekili options to absolute minimum (refresh 4 times per second, minimal fps, etc).
No change whatsoever. Game still freezes for exactly the same period of time. 
100% sure its hekili. After hekili is turned off, game plays normally despite me having
20 different addons piled up and active.
Also, the other way around, with only Hekili active and the other addons off, 
the freezing happens for exactly the same amount of time, about 0.25 seconds.

cheers and thanks for the good work.
Cootie@Lightbringer

**Comment by Hekili** [comment] 2019-03-14 13:19
Please try both v8.1.5-02-alpha1 and -alpha2.  Still exploring whether this is something on the Blizzard side.

I'm exploring *everything* the addon does when exiting combat, but still stuck given that the issue doesn't appear on my end.

**Comment by Zankom** [comment] 2019-03-14 13:25
i tried the latest version and the problem is still present.

**Comment by Hekili** [comment] 2019-03-14 13:26
Try both.  They are different solutions/ideas.

**Comment by Zankom** [comment] 2019-03-14 13:36
ok so, i downloaded v8.1.5-02-alpha1-1-g6782ec3, and im not sure if im tripping out or not, but i think its fixed.

**Comment by Tifflez** [comment] 2019-03-14 14:07
Was having the same issues as others with the fps drop/stutter after combat.
v8.1.5-02-alpha1-1-g6782ec3 has fixed the issue.Only tested for a few minutes but no stutter at all.
Thanks

**Comment by Tinyta** [comment] 2019-03-14 14:07
Yay! I can confirm that on build v8.1.5-02-alpha1-1-g6782ec3 the problem is fixed for me as well.

**Comment by Hekili** [comment] 2019-03-14 14:10
Thanks for continuing to test.  I'm still not confident *I* fixed it -- this all coincides nicely with Blizzard deploying a patch this morning as well, but I'll take the win.

Can you let me know if the issue reappears with -02-alpha2?

**Comment by Tinyta** [comment] 2019-03-14 14:13
Of course, will do.

**Comment by Cootie76** [comment] 2019-03-14 14:31
v8.1.5-02-alpha1-1-g6782ec3 fixes the game freezing problem.
Dont belittle yourself, its all you.
Morning Blizz patch on thursday did nothing to change the issue, its your version uploaded right now, 8 hours after the patch, that fixed everthing. 

sincere thanks, you are the best!

**Comment by meatbag101** [comment] 2019-03-14 14:43
Can confirm "-02-alpha2" has zero lag issues aswell, seem to work like it did before the latest wow patch. GG well done, if I could I would pat you on the shoulder.

**Comment by Tinyta** [comment] 2019-03-14 16:58
Build v8.1.5-02 working without any issues for me. Thank you very much!

**Closed as completed** 2019-03-14 17:48 UTC

**Comment by Zankom** [comment] 2019-03-14 20:08
Thanks for fixing it. Your addon is the best. Continue  the good work.

**Comment by bobbutcher** [comment] 2019-03-14 21:13
def huge thx for all the work fixing this..love ur addon

**Comment by praiseshiva** [comment] 2019-03-14 23:55
I know its fixed and you've closed this issue but i wanted to say **THANKS**! I turn into JoJo the idiot circus boy when I get into combat and your addon really helps me focus and enjoy the game more.

**Comment by Hekili** [comment] 2019-03-14 23:56
Thanks for all the help sorting out this issue and the feedback y'all have provided.  I will say that I didn't do an amazing job of asking questions to get answers, but I appreciate that y'all worked with me and kept providing information that helped to resolve this.

So, thanks again, to everyone, for your help and support.  Please update me if you run into other problems!
