### ISSUE TITLE
Survival Hunter issues

### ISSUE THREAD

**Issue by FogTheHunter** [Hekili/hekili#702] opened 2020-12-16 13:02 UTC
I assume with the start of 9.0.2-1.0.24, the Survival Hunter is broken. I never used the Survival build before, so this took some investigation. Nothing shows up at any display (remaining 13 other characters with their spec's work, including Hunter BM and MM). Running thru the settings, the first thing that sticks out is, that in 'Settings - Survival' the dropdown under Priority is Empty. The next thing that looks odd is, that under 'Settings - Priorities - + - Survival' The Priority Name is Beast Master and the Decription also includes Beast Master. Copying Survival from the default does not change results. Done the following:

- Removed all settings for Hekili (from SavedVariables) and then started WOW with the Survival Hunter again. Same problem.
- Removed all settings AND the Hekili and reinstalled 9.0.2-1.0.24beta4, started WOW with Surv Hunter. Same problem.
- Removed all settings, Hekili and reinstalled 9.0.2-1.0.23 (release), started WOW with Surv Hunter. Problem solved !!!
- Updated (as a try) to 9.0.2-1.0.24beta4, problem reoccurs again !!

So somewhere between 1.0.23 release and the current beta, the Survival Hunter broke. I see in earlier tickets that at some time the Surv was accidentally replaced by BM and I guess something like that happened again. Running with 1.0.23 until I see some reference of fixing in the changelog of newer versions or like to hear where I went wrong (if that is the case).

**Comment by Hekili** [comment] 2020-12-16 13:09
I'll look.  But also, you should fill out the ticket form:

**BEFORE SUBMITTING AN ISSUE:**

1.  Check to see if you are using the latest version of the addon.  If there is a newer alpha/beta/release version, see if your problem exists with the new version.

2.  Check to see if someone else has already opened an issue report here.  Please don't submit repeat reports.

**Describe the Bug/Issue**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
- Go to '...'
- Click on '....'
- Scroll down to '....'
- See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**WHEN SUBMITTING AN ISSUE:**

Please provide the following information.  Leaving it out may result in your ticket being ignored (because I won't have the information needed to explore your report).

1.  The information from the Issue Reporting tab ( /hekili > Issue Reporting ).  This provides your talent and gear information.  You can paste it to pastebin.com and provide a link here.

**PUT ISSUE REPORT LINK HERE:**

2.  If reporting a disagreement with the addon's recommendations, please take a snapshot when you observe the issue and provide the snapshot.  This is not a screenshot.  A snapshot can be generated by binding the Pause feature on the Toggles tab.  When you press Pause, a snapshot of how the addon decided on its CURRENT recommendations is generated and saved to the Snapshots tab.  Copy and paste this to pastebin.com and provide the link here.
 
**PUT SNAPSHOT LINK HERE:**

3.  If reporting an error (i.e., the addon freezes and/or disables itself), please install the BugSack and BugGrabber addons as they will enable you to paste the exact error message, with detail that will help me identify where the code error is located.  You can paste the error information here or use pastebin.com for that as well.

**PUT ERROR MESSAGE(S) HERE:**

**Comment by Hekili** [comment] 2020-12-16 13:29
Alright, quick check shows the priority hadn't loaded properly.  Will be fixed in next release (later this morning).

**Closed as completed by Hekili** 2020-12-16 13:29 UTC
