### ISSUE TITLE
Demo: Not recommending CD's after opening sequence

### ISSUE THREAD

**Issue by Catabolik** [Hekili/hekili#2930] opened 2023-11-16 19:02 UTC
### Before You Begin

- [X] I confirm that I have downloaded the latest version of the addon.
- [X] I am not playing on a private server.
- [X] I checked for an [existing, open ticket](https://github.com/Hekili/hekili/labels/recommendation) for this issue and was not able to find one.
- [X] I edited the title of this issue (above) so that it describes the issue I am reporting.
- [X] I am reporting an issue with the default priority included with the specialization (imported or edited priorities are not supported).

### Describe the Issue

After opening sequence, priority rotation stops recommending all CD's (including minor) until Grimoire: Felguard is off CD (Call Dreadstalkers, Summon Vilefiend, Guillotine, Demonic Strength, Summon Demonic Tyrant, Grimoire: Felguard, Power Siphon)

### How to Reproduce

1. Enter game as a Demonology Warlock
2. Take talents mentioned in the "Describe the Issue" section.
3. Run a 3 minute sequence.
4. See recommendations

### Snapshot (Link)

https://pastebin.com/SYRsXLQs

**Comment by Hekili** [comment] 2023-11-27 15:42
I haven't been able to replicate this, though there are other demo issues.  Is this still occurring?

**Comment by Catabolik** [comment] 2023-11-27 17:37
After tinkering around with different builds, I have only been noticing these issues when Grand Warlock's Design is talented.

**Comment by kris-hamade** [comment] 2023-11-29 06:40
Mine never recommends tyrant or felguard regardless of talents

**Comment by Hekili** [comment] 2023-11-29 19:42
> Mine never recommends tyrant or felguard regardless of talents

This is probably a matter of having cooldowns toggled off by default.  Look at /hekili > Toggles.

**Comment by kris-hamade** [comment] 2023-11-29 23:36
This fixed it! Thank you so much

**Comment by Kharn87** [comment] 2023-11-30 07:58
Even with cooldowns toggled while in demo spec it is no longer recommending anything with a cooldown of 1 min or longer after the initial opener. It was working yesterday just fine for me.

**Comment by Hekili** [comment] 2023-11-30 12:48
> Even with cooldowns toggled while in demo spec it is no longer recommending anything with a cooldown of 1 min or longer after the initial opener. It was working yesterday just fine for me.

To investigate, I'll need you to snapshot this when it's happening and post a link.

**Comment by Kharn87** [comment] 2023-11-30 17:26
> > Even with cooldowns toggled while in demo spec it is no longer recommending anything with a cooldown of 1 min or longer after the initial opener. It was working yesterday just fine for me.
> 
> To investigate, I'll need you to snapshot this when it's happening and post a link.

See pastebin snapshot below. Let me know if you need any more info. Its so strange, Demo was working just fine on Tuesday, but suddenly on Wednesday it was broken. 

https://pastebin.com/nnuTgDQJ

**Comment by xxxj2kxxx** [comment] 2023-12-16 08:55
I have identical issue to Kharn87 above. Updated Hekili today and now after the opener it never recommends a cooldown of 1 minute or more again. Cooldowns are enabled in addon both major and minor.

Update: Actually it won't even recommend Vilefiend or Dreadstalker's after the opener.
Update 2: It does however recommend Demonic Strength every 1 minute, but completely ignores Tyrant and Vilefiend beyond the first cast...
Update 3: It is waiting for Grimoire: Felguard to use vilefiend/dreadstalkers and tyrant even when spec into Grand Warlock's design

**Comment by Hekili** [comment] 2023-12-16 14:58
> I have identical issue to Kharn87 above. Updated Hekili today and now after the opener it never recommends a cooldown of 1 minute or more again. Cooldowns are enabled in addon both major and minor.
> 
> Update: Actually it won't even recommend Vilefiend or Dreadstalker's after the opener. Update 2: It does however recommend Demonic Strength every 1 minute, but completely ignores Tyrant and Vilefiend beyond the first cast... Update 3: It is waiting for Grimoire: Felguard to use vilefiend/dreadstalkers and tyrant even when spec into Grand Warlock's design

Thanks; please post the snapshot so I can look at the details.  Thanks!

**Comment by xxxj2kxxx** [comment] 2023-12-30 17:05
https://pastebin.com/uNh9KgCM

**Comment by Freiszcze** [comment] 2024-01-08 08:42
I still think that especially in AoE situations, insta Demon Bolt is not recommended a lot.

**Comment by Hekili** [comment] 2024-01-08 14:07
Please test with v10.2.0-1.1.0 and provide new snapshots if you are experiencing the same or similar issues.

**Comment by xxxj2kxxx** [comment] 2024-01-20 07:40
Same problem. Hadn't played demo in a while since I can't stand it without Hekili. Latest version of Hekili in 10.2.5 is still identical problem, after the first opening sequence it never recommends Vile fiend, Call dreadstalker's, demonc strength etc...

**Comment by xxxj2kxxx** [comment] 2024-01-20 07:43
https://pastebin.com/u6pg8Mrt

**Comment by phatzz** [comment] 2024-01-29 20:10
I'm seeing the same thing when using grand warlock's design. It seems to want to play 2 min tyrants even though the player is specced into grand warlock's design

**Comment by xxxj2kxxx** [comment] 2024-01-31 05:02
Problem still not fixed as of 31st january 2024

**Comment by Hekili** [comment] 2024-02-07 15:41
The only person who needs to post status updates in a ticket thread is me.  :)  The issue is that the way that the sim handles desynced cooldowns does not translate easily to the addon.  I've been trying to think of a simpler way to do it that still sims comparably, and will update when I have a solution.

**Closed as completed** 2024-07-27 17:03 UTC
Labels: 📈 recommendations, 🧑‍⚕️ triage
